<div class="c20_35"> 
<div id="v20.35.1"><span class="H4872 s">And Moses</span><span class="H6950 s"> gathered</span><span class="H5712 s"> all the congregation</span><span class="H1121 s"> of the children</span><span class="H3478 s"> of Israel</span><span class="H6950 s"> together</span><span class="H559 s">, and said</span><span class="H1697 s"> unto them, These <i>are</i> the words</span><span class="H3068 s"> which the LORD</span><span class="H6680 s"> hath commanded</span><span class="H6213 s">, that <i>ye</i> should do</span> them.</div> 
<div id="v20.35.2"><span class="H8337 s">Six</span><span class="H3117 s"> days</span><span class="H4399 s"> shall work</span><span class="H6213 s"> be done</span><span class="H7637 s">, but on the seventh</span><span class="H3117 s"> day</span><span class="H6944 s"> there shall be to you an holy day</span><span class="H7676 s">, a sabbath</span><span class="H7677 s"> of rest</span><span class="H3068 s"> to the LORD</span><span class="H6213 s">: whosoever doeth</span><span class="H4399 s"> work</span><span class="H4191 s"> therein shall be put to death</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (an…: Heb. holiness)</span></div> 
<div id="v20.35.3"><span class="H1197 s">Ye shall kindle</span><span class="H784 s"> no fire</span><span class="H4186 s"> throughout your habitations</span><span class="H7676 s"> upon the sabbath</span><span class="H3117 s"> day</span>.</div> 
<div id="v20.35.4"><span class="H4872 s">And Moses</span><span class="H559 s"> spake</span><span class="H5712 s"> unto all the congregation</span><span class="H1121 s"> of the children</span><span class="H3478 s"> of Israel</span><span class="H559 s">, saying</span><span class="H1697 s">, This <i>is</i> the thing</span><span class="H3068 s"> which the LORD</span><span class="H6680 s"> commanded</span><span class="H559 s">, saying</span>,</div> 
<div id="v20.35.5"><span class="H3947 s">Take</span><span class="H8641 s"> ye from among you an offering</span><span class="H3068 s"> unto the LORD</span><span class="H3605 s">: whosoever</span><span class="H5081 s"> <i>is</i> of a willing</span><span class="H3820 s"> heart</span><span class="H935 s">, let him bring</span><span class="H8641 s"> it, an offering</span><span class="H3068 s"> of the LORD</span><span class="H2091 s">; gold</span><span class="H3701 s">, and silver</span><span class="H5178 s">, and brass</span>,</div> 
<div id="v20.35.6"><span class="H8504 s">And blue</span><span class="H713 s">, and purple</span><span class="H8144 s">, and scarlet</span><span class="H8438 s"> †</span><span class="H8336 s">, and fine linen</span><span class="H5795 s fixed">, and goats' <i>hair</i>,</div> 
<div id="v20.35.7"><span class="H352 s fixed">And rams'</span><span class="H5785 s"> skins</span><span class="H119 s"> dyed red</span><span class="H8476 s fixed">, and badgers'</span><span class="H5785 s"> skins</span><span class="H7848 s">, and shittim</span><span class="H6086 s"> wood</span>,</div> 
<div id="v20.35.8"><span class="H8081 s">And oil</span><span class="H3974 s"> for the light</span><span class="H1314 s">, and spices</span><span class="H4888 s"> for anointing</span><span class="H8081 s"> oil</span><span class="H5561 s">, and for the sweet</span><span class="H7004 s"> incense</span>,</div> 
<div id="v20.35.9"><span class="H7718 s">And onyx</span><span class="H68 s"> stones</span><span class="H68 s">, and stones</span><span class="H4394 s"> to be set</span><span class="H646 s"> for the ephod</span><span class="H2833 s">, and for the breastplate</span>.</div> 
<div id="v20.35.10"><span class="H2450 s">And every wise</span><span class="H3820 s"> hearted</span><span class="H935 s"> among you shall come</span><span class="H6213 s">, and make</span><span class="H3068 s"> all that the LORD</span><span class="H6680 s"> hath commanded</span>;</div> 
<div id="v20.35.11"><span class="H4908 s">The tabernacle</span><span class="H168 s">, his tent</span><span class="H4372 s">, and his covering</span><span class="H7165 s">, his taches</span><span class="H7175 s">, and his boards</span><span class="H1280 s">, his bars</span><span class="H5982 s">, his pillars</span><span class="H134 s">, and his sockets</span>,</div> 
<div id="v20.35.12"><span class="H727 s">The ark</span><span class="H905 s">, and the staves</span><span class="H3727 s"> thereof, <i>with</i> the mercy seat</span><span class="H6532 s">, and the vail</span><span class="H4539 s"> of the covering</span>,</div> 
<div id="v20.35.13"><span class="H7979 s">The table</span><span class="H905 s">, and his staves</span><span class="H3627 s">, and all his vessels</span><span class="H6440 s">, and the shewbread</span><span class="H3899 s"> †</span>,</div> 
<div id="v20.35.14"><span class="H4501 s">The candlestick</span><span class="H3974 s"> also for the light</span><span class="H3627 s">, and his furniture</span><span class="H5216 s">, and his lamps</span><span class="H8081 s">, with the oil</span><span class="H3974 s"> for the light</span>,</div> 
<div id="v20.35.15"><span class="H7004 s">And the incense</span><span class="H4196 s"> altar</span><span class="H905 s">, and his staves</span><span class="H4888 s">, and the anointing</span><span class="H8081 s"> oil</span><span class="H5561 s">, and the sweet</span><span class="H7004 s"> incense</span><span class="H4539 s">, and the hanging</span><span class="H6607 s"> for the door at the entering in</span><span class="H4908 s"> of the tabernacle</span>,</div> 
<div id="v20.35.16"><span class="H4196 s">The altar</span><span class="H5930 s"> of burnt offering</span><span class="H5178 s">, with his brasen</span><span class="H4345 s"> grate</span><span class="H905 s">, his staves</span><span class="H3627 s">, and all his vessels</span><span class="H3595 s">, the laver</span><span class="H3653 s"> and his foot</span>,</div> 
<div id="v20.35.17"><span class="H7050 s">The hangings</span><span class="H2691 s"> of the court</span><span class="H5982 s">, his pillars</span><span class="H134 s">, and their sockets</span><span class="H4539 s">, and the hanging</span><span class="H8179 s"> for the door</span><span class="H2691 s"> of the court</span>,</div> 
<div id="v20.35.18"><span class="H3489 s">The pins</span><span class="H4908 s"> of the tabernacle</span><span class="H3489 s">, and the pins</span><span class="H2691 s"> of the court</span><span class="H4340 s">, and their cords</span>,</div> 
<div id="v20.35.19"><span class="H899 s">The cloths</span><span class="H8278 s"> of service</span><span class="H8334 s">, to do service</span><span class="H6944 s"> in the holy</span><span class="H6944 s"> <i>place</i>, the holy</span><span class="H899 s"> garments</span><span class="H175 s"> for Aaron</span><span class="H3548 s"> the priest</span><span class="H899 s">, and the garments</span><span class="H1121 s"> of his sons</span><span class="H3547 s">, to minister in the priest's office</span>.</div> 
<div id="v20.35.20"><span class="H5712 s">And all the congregation</span><span class="H1121 s"> of the children</span><span class="H3478 s"> of Israel</span><span class="H3318 s"> departed</span><span class="H6440 s"> from the presence</span><span class="H4872 s"> of Moses</span>.</div> 
<div id="v20.35.21"><span class="H935 s">And they came</span><span class="H376 s">, every one</span><span class="H834 s"> whose</span><span class="H3820 s"> heart</span><span class="H5375 s"> stirred him up</span><span class="H7307 s">, and every one whom his spirit</span><span class="H5068 s"> made willing</span><span class="H935 s">, <i>and</i> they brought</span><span class="H3068 s"> the LORD'S</span><span class="H8641 s"> offering</span><span class="H4399 s"> to the work</span><span class="H168 s"> of the tabernacle</span><span class="H4150 s"> of the congregation</span><span class="H5656 s">, and for all his service</span><span class="H6944 s">, and for the holy</span><span class="H899 s"> garments</span>.</div> 
<div id="v20.35.22"><span class="H935 s">And they came</span><span class="H5921 s">, both</span><span class="H582 s"> men</span><span class="H802 s"> and women</span><span class="H3605 s">, as many as</span><span class="H5081 s"> were willing</span><span class="H3820 s"> hearted</span><span class="H935 s">, <i>and</i> brought</span><span class="H2397 s"> bracelets</span><span class="H5141 s">, and earrings</span><span class="H2885 s">, and rings</span><span class="H3558 s">, and tablets</span><span class="H3627 s">, all jewels</span><span class="H2091 s"> of gold</span><span class="H376 s">: and every man</span><span class="H5130 s"> that offered</span><span class="H8573 s"> <i>offered</i> an offering</span><span class="H2091 s"> of gold</span><span class="H3068 s"> unto the LORD</span>.</div> 
<div id="v20.35.23"><span class="H376 s">And every man</span><span class="H4672 s">, with whom was found</span><span class="H8504 s"> blue</span><span class="H713 s">, and purple</span><span class="H8144 s">, and scarlet</span><span class="H8438 s"> †</span><span class="H8336 s">, and fine linen</span><span class="H5795 s fixed">, and goats'</span><span class="H119 s"> <i>hair</i>, and red</span><span class="H5785 s"> skins</span><span class="H352 s"> of rams</span><span class="H8476 s fixed">, and badgers'</span><span class="H5785 s"> skins</span><span class="H935 s">, brought</span> <i>them</i>.</div> 
<div id="v20.35.24"><span class="H7311 s">Every one that did offer</span><span class="H8641 s"> an offering</span><span class="H3701 s"> of silver</span><span class="H5178 s"> and brass</span><span class="H935 s"> brought</span><span class="H3068 s"> the LORD'S</span><span class="H8641 s"> offering</span><span class="H4672 s">: and every man, with whom was found</span><span class="H7848 s"> shittim</span><span class="H6086 s"> wood</span><span class="H4399 s"> for any work</span><span class="H5656 s"> of the service</span><span class="H935 s">, brought</span> <i>it</i>.</div> 
<div id="v20.35.25"><span class="H802 s">And all the women</span><span class="H2450 s"> that were wise</span><span class="H3820 s"> hearted</span><span class="H2901 s"> did spin</span><span class="H3027 s"> with their hands</span><span class="H935 s">, and brought</span><span class="H4299 s"> that which they had spun</span><span class="H8504 s">, <i>both</i> of blue</span><span class="H713 s">, and of purple</span><span class="H8144 s">, <i>and</i> of scarlet</span><span class="H8438 s"> †</span><span class="H8336 s">, and of fine linen</span>.</div> 
<div id="v20.35.26"><span class="H802 s">And all the women</span><span class="H3820 s"> whose heart</span><span class="H5375 s"> stirred</span><span class="H2451 s"> them up in wisdom</span><span class="H2901 s"> spun</span><span class="H5795 s fixed"> goats' <i>hair</i>.</div> 
<div id="v20.35.27"><span class="H5387 s">And the rulers</span><span class="H935 s"> brought</span><span class="H7718 s"> onyx</span><span class="H68 s"> stones</span><span class="H68 s">, and stones</span><span class="H4394 s"> to be set</span><span class="H646 s">, for the ephod</span><span class="H2833 s">, and for the breastplate</span>;</div> 
<div id="v20.35.28"><span class="H1314 s">And spice</span><span class="H8081 s">, and oil</span><span class="H3974 s"> for the light</span><span class="H4888 s">, and for the anointing</span><span class="H8081 s"> oil</span><span class="H5561 s">, and for the sweet</span><span class="H7004 s"> incense</span>.</div> 
<div id="v20.35.29"><span class="H1121 s">The children</span><span class="H3478 s"> of Israel</span><span class="H935 s"> brought</span><span class="H5071 s"> a willing offering</span><span class="H3068 s"> unto the LORD</span><span class="H376 s">, every man</span><span class="H802 s"> and woman</span><span class="H834 s">, whose</span><span class="H3820 s"> heart</span><span class="H5068 s"> made them willing</span><span class="H935 s"> to bring</span><span class="H4399 s"> for all manner of work</span><span class="H3068 s">, which the LORD</span><span class="H6680 s"> had commanded</span><span class="H6213 s"> to be made</span><span class="H3027 s"> by the hand</span><span class="H4872 s"> of Moses</span>.</div> 
<div id="v20.35.30"><span class="H4872 s">And Moses</span><span class="H559 s"> said</span><span class="H1121 s"> unto the children</span><span class="H3478 s"> of Israel</span><span class="H7200 s">, See</span><span class="H3068 s">, the LORD</span><span class="H7121 s"> hath called</span><span class="H8034 s"> by name</span><span class="H1212 s"> Bezaleel</span><span class="H1121 s"> the son</span><span class="H221 s"> of Uri</span><span class="H1121 s">, the son</span><span class="H2354 s"> of Hur</span><span class="H4294 s">, of the tribe</span><span class="H3063 s"> of Judah</span>;</div> 
<div id="v20.35.31"><span class="H4390 s">And he hath filled</span><span class="H7307 s"> him with the spirit</span><span class="H430 s"> of God</span><span class="H2451 s">, in wisdom</span><span class="H8394 s">, in understanding</span><span class="H1847 s">, and in knowledge</span><span class="H4399 s">, and in all manner of workmanship</span>;</div> 
<div id="v20.35.32"><span class="H2803 s">And to devise</span><span class="H4284 s"> curious works</span><span class="H6213 s">, to work</span><span class="H2091 s"> in gold</span><span class="H3701 s">, and in silver</span><span class="H5178 s">, and in brass</span>,</div> 
<div id="v20.35.33"><span class="H2799 s">And in the cutting</span><span class="H68 s"> of stones</span><span class="H4390 s">, to set</span><span class="H2799 s"> <i>them</i>, and in carving</span><span class="H6086 s"> of wood</span><span class="H6213 s">, to make</span><span class="H4284 s"> any manner of cunning</span><span class="H4399 s"> work</span>.</div> 
<div id="v20.35.34"><span class="H5414 s">And he hath put</span><span class="H3820 s"> in his heart</span><span class="H3384 s"> that he may teach</span><span class="H171 s">, <i>both</i> he, and Aholiab</span><span class="H1121 s">, the son</span><span class="H294 s"> of Ahisamach</span><span class="H4294 s">, of the tribe</span><span class="H1835 s"> of Dan</span>.</div> 
<div id="v20.35.35"><span class="H4390 s">Them hath he filled</span><span class="H2451 s"> with wisdom</span><span class="H3820 s"> of heart</span><span class="H6213 s">, to work</span><span class="H4399 s"> all manner of work</span><span class="H2796 s">, of the engraver</span><span class="H2803 s">, and of the cunning workman</span><span class="H7551 s">, and of the embroiderer</span><span class="H8504 s">, in blue</span><span class="H713 s">, and in purple</span><span class="H8144 s">, in scarlet</span><span class="H8438 s"> †</span><span class="H8336 s">, and in fine linen</span><span class="H707 s">, and of the weaver</span><span class="H6213 s">, <i>even</i> of them that do</span><span class="H3605 s"> any</span><span class="H4399 s"> work</span><span class="H2803 s">, and of those that devise</span><span class="H4284 s"> cunning work</span>.</div></div> 
