<div class="c300_33"> 
<div id="v300.33.1"><span class="H1697 s">Moreover the word</span><span class="H3068 s"> of the LORD</span><span class="H3414 s"> came unto Jeremiah</span><span class="H8145 s"> the second</span><span class="H6113 s"> time, while he was yet shut up</span><span class="H2691 s"> in the court</span><span class="H4307 s"> of the prison</span><span class="H559 s">, saying</span>,</div> 
<div id="v300.33.2"><span class="H559 s">Thus saith</span><span class="H3068 s"> the LORD</span><span class="H6213 s"> the maker</span><span class="H3068 s"> thereof, the LORD</span><span class="H3335 s"> that formed</span><span class="H3559 s"> it, to establish</span><span class="H3068 s"> it; the LORD</span><span class="H8034 s"> <i>is</i> his name</span>; <span class="notes">Notes by the 1611 King James Bible Translators: (the LORD is: or, JEHOVAH, etc)</span></div> 
<div id="v300.33.3"><span class="H7121 s">Call</span><span class="H6030 s"> unto me, and I will answer</span><span class="H5046 s"> thee, and shew</span><span class="H1419 s"> thee great</span><span class="H1219 s"> and mighty things</span><span class="H3045 s">, which thou knowest</span> not. <span class="notes">Notes by the 1611 King James Bible Translators: (mighty: or, hidden)</span></div> 
<div id="v300.33.4"><span class="H559 s">For thus saith</span><span class="H3068 s"> the LORD</span><span class="H430 s">, the God</span><span class="H3478 s"> of Israel</span><span class="H1004 s">, concerning the houses</span><span class="H5892 s"> of this city</span><span class="H1004 s">, and concerning the houses</span><span class="H4428 s"> of the kings</span><span class="H3063 s"> of Judah</span><span class="H5422 s">, which are thrown down</span><span class="H5550 s"> by the mounts</span><span class="H2719 s">, and by the sword</span>;</div> 
<div id="v300.33.5"><span class="H935 s">They come</span><span class="H3898 s"> to fight</span><span class="H3778 s"> with the Chaldeans</span><span class="H4390 s">, but <i>it is</i> to fill</span><span class="H6297 s"> them with the dead bodies</span><span class="H120 s"> of men</span><span class="H5221 s">, whom I have slain</span><span class="H639 s"> in mine anger</span><span class="H2534 s"> and in my fury</span><span class="H7451 s">, and for all whose wickedness</span><span class="H5641 s"> I have hid</span><span class="H6440 s"> my face</span><span class="H5892 s"> from this city</span>.</div> 
<div id="v300.33.6"><span class="H5927 s">Behold, I will bring</span><span class="H724 s"> it health</span><span class="H4832 s"> and cure</span><span class="H7495 s">, and I will cure</span><span class="H1540 s"> them, and will reveal</span><span class="H6283 s"> unto them the abundance</span><span class="H7965 s"> of peace</span><span class="H571 s"> and truth</span>.</div> 
<div id="v300.33.7"><span class="H7622 s">And I will cause the captivity</span><span class="H3063 s"> of Judah</span><span class="H7622 s"> and the captivity</span><span class="H3478 s"> of Israel</span><span class="H7725 s"> to return</span><span class="H1129 s">, and will build</span><span class="H7223 s"> them, as at the first</span>.</div> 
<div id="v300.33.8"><span class="H2891 s">And I will cleanse</span><span class="H5771 s"> them from all their iniquity</span><span class="H2398 s">, whereby they have sinned</span><span class="H5545 s"> against me; and I will pardon</span><span class="H5771 s"> all their iniquities</span><span class="H2398 s">, whereby they have sinned</span><span class="H6586 s">, and whereby they have transgressed</span> against me.</div> 
<div id="v300.33.9"><span class="H8034 s">And it shall be to me a name</span><span class="H8342 s"> of joy</span><span class="H8416 s">, a praise</span><span class="H8597 s"> and an honour</span><span class="H1471 s"> before all the nations</span><span class="H776 s"> of the earth</span><span class="H8085 s">, which shall hear</span><span class="H2896 s"> all the good</span><span class="H6213 s"> that I do</span><span class="H6342 s"> unto them: and they shall fear</span><span class="H7264 s"> and tremble</span><span class="H2896 s"> for all the goodness</span><span class="H7965 s"> and for all the prosperity</span><span class="H6213 s"> that I procure</span> unto it.</div> 
<div id="v300.33.10"><span class="H559 s">Thus saith</span><span class="H3068 s"> the LORD</span><span class="H8085 s">; Again there shall be heard</span><span class="H4725 s"> in this place</span><span class="H559 s">, which ye say</span><span class="H2720 s"> <i>shall be</i> desolate</span><span class="H120 s"> without man</span><span class="H929 s"> and without beast</span><span class="H5892 s">, <i>even</i> in the cities</span><span class="H3063 s"> of Judah</span><span class="H2351 s">, and in the streets</span><span class="H3389 s"> of Jerusalem</span><span class="H8074 s">, that are desolate</span><span class="H120 s">, without man</span><span class="H3427 s">, and without inhabitant</span><span class="H929 s">, and without beast</span>,</div> 
<div id="v300.33.11"><span class="H6963 s">The voice</span><span class="H8342 s"> of joy</span><span class="H6963 s">, and the voice</span><span class="H8057 s"> of gladness</span><span class="H6963 s">, the voice</span><span class="H2860 s"> of the bridegroom</span><span class="H6963 s">, and the voice</span><span class="H3618 s"> of the bride</span><span class="H6963 s">, the voice</span><span class="H559 s"> of them that shall say</span><span class="H3034 s">, Praise</span><span class="H3068 s"> the LORD</span><span class="H6635 s"> of hosts</span><span class="H3068 s">: for the LORD</span><span class="H2896 s"> <i>is</i> good</span><span class="H2617 s">; for his mercy</span><span class="H5769 s"> <i>endureth</i> for ever</span><span class="H935 s">: <i>and</i> of them that shall bring</span><span class="H8426 s"> the sacrifice of praise</span><span class="H1004 s"> into the house</span><span class="H3068 s"> of the LORD</span><span class="H7725 s">. For I will cause to return</span><span class="H7622 s"> the captivity</span><span class="H776 s"> of the land</span><span class="H7223 s">, as at the first</span><span class="H559 s">, saith</span><span class="H3068 s"> the LORD</span>.</div> 
<div id="v300.33.12"><span class="H559 s">Thus saith</span><span class="H3068 s"> the LORD</span><span class="H6635 s"> of hosts</span><span class="H4725 s">; Again in this place</span><span class="H2720 s">, which is desolate</span><span class="H120 s"> without man</span><span class="H929 s"> and without beast</span><span class="H5892 s">, and in all the cities</span><span class="H5116 s"> thereof, shall be an habitation</span><span class="H7462 s"> of shepherds</span><span class="H6629 s"> causing <i>their</i> flocks</span><span class="H7257 s"> to lie down</span>.</div> 
<div id="v300.33.13"><span class="H5892 s">In the cities</span><span class="H2022 s"> of the mountains</span><span class="H5892 s">, in the cities</span><span class="H8219 s"> of the vale</span><span class="H5892 s">, and in the cities</span><span class="H5045 s"> of the south</span><span class="H776 s">, and in the land</span><span class="H1144 s"> of Benjamin</span><span class="H5439 s">, and in the places about</span><span class="H3389 s"> Jerusalem</span><span class="H5892 s">, and in the cities</span><span class="H3063 s"> of Judah</span><span class="H6629 s">, shall the flocks</span><span class="H5674 s"> pass again</span><span class="H3027 s"> under the hands</span><span class="H4487 s"> of him that telleth</span><span class="H559 s"> <i>them</i>, saith</span><span class="H3068 s"> the LORD</span>.</div> 
<div id="v300.33.14"><span class="H3117 s">Behold, the days</span><span class="H935 s"> come</span><span class="H5002 s">, saith</span><span class="H3068 s"> the LORD</span><span class="H6965 s">, that I will perform</span><span class="H2896 s"> that good</span><span class="H1697 s"> thing</span><span class="H1696 s"> which I have promised</span><span class="H1004 s"> unto the house</span><span class="H3478 s"> of Israel</span><span class="H1004 s"> and to the house</span><span class="H3063 s"> of Judah</span>.</div> 
<div id="v300.33.15"><span class="H3117 s">In those days</span><span class="H6256 s">, and at that time</span><span class="H6780 s">, will I cause the Branch</span><span class="H6666 s"> of righteousness</span><span class="H6779 s"> to grow up</span><span class="H1732 s"> unto David</span><span class="H6213 s">; and he shall execute</span><span class="H4941 s"> judgment</span><span class="H6666 s"> and righteousness</span><span class="H776 s"> in the land</span>.</div> 
<div id="v300.33.16"><span class="H3117 s">In those days</span><span class="H3063 s"> shall Judah</span><span class="H3467 s"> be saved</span><span class="H3389 s">, and Jerusalem</span><span class="H7931 s"> shall dwell</span><span class="H983 s"> safely</span><span class="H7121 s">: and this <i>is the name</i> wherewith she shall be called</span><span class="H3072 s">, The LORD our righteousness</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (The LORD…: Heb. Jehovahtsidkenu)</span></div> 
<div id="v300.33.17"><span class="H559 s">For thus saith</span><span class="H3068 s"> the LORD</span><span class="H1732 s">; David</span><span class="H3808 s"> shall never</span><span class="H3772 s"> want</span><span class="H376 s"> a man</span><span class="H3427 s"> to sit</span><span class="H3678 s"> upon the throne</span><span class="H1004 s"> of the house</span><span class="H3478 s"> of Israel</span>; <span class="notes">Notes by the 1611 King James Bible Translators: (David…: Heb. There shall not be cut off from David)</span></div> 
<div id="v300.33.18"><span class="H3548 s">Neither shall the priests</span><span class="H3881 s"> the Levites</span><span class="H3772 s"> want</span><span class="H376 s"> a man</span><span class="H6440 s"> before</span><span class="H5927 s"> me to offer</span><span class="H5930 s"> burnt offerings</span><span class="H6999 s">, and to kindle</span><span class="H4503 s"> meat offerings</span><span class="H6213 s">, and to do</span><span class="H2077 s"> sacrifice</span><span class="H3117 s"> continually</span>.</div> 
<div id="v300.33.19"><span class="H1697 s">And the word</span><span class="H3068 s"> of the LORD</span><span class="H3414 s"> came unto Jeremiah</span><span class="H559 s">, saying</span>,</div> 
<div id="v300.33.20"><span class="H559 s">Thus saith</span><span class="H3068 s"> the LORD</span><span class="H6565 s">; If ye can break</span><span class="H1285 s"> my covenant</span><span class="H3117 s"> of the day</span><span class="H1285 s">, and my covenant</span><span class="H3915 s"> of the night</span><span class="H3119 s">, and that there should not be day</span><span class="H3915 s"> and night</span><span class="H6256 s"> in their season</span>;</div> 
<div id="v300.33.21"><span class="H1285 s"><i>Then</i> may also my covenant</span><span class="H6565 s"> be broken</span><span class="H1732 s"> with David</span><span class="H5650 s"> my servant</span><span class="H1121 s">, that he should not have a son</span><span class="H4427 s"> to reign</span><span class="H3678 s"> upon his throne</span><span class="H3881 s">; and with the Levites</span><span class="H3548 s"> the priests</span><span class="H8334 s">, my ministers</span>.</div> 
<div id="v300.33.22"><span class="H6635 s">As the host</span><span class="H8064 s"> of heaven</span><span class="H5608 s"> cannot be numbered</span><span class="H2344 s">, neither the sand</span><span class="H3220 s"> of the sea</span><span class="H4058 s"> measured</span><span class="H7235 s">: so will I multiply</span><span class="H2233 s"> the seed</span><span class="H1732 s"> of David</span><span class="H5650 s"> my servant</span><span class="H3881 s">, and the Levites</span><span class="H8334 s"> that minister</span> unto me.</div> 
<div id="v300.33.23"><span class="H1697 s">Moreover the word</span><span class="H3068 s"> of the LORD</span><span class="H3414 s"> came to Jeremiah</span><span class="H559 s">, saying</span>,</div> 
<div id="v300.33.24"><span class="H7200 s">Considerest</span><span class="H5971 s"> thou not what this people</span><span class="H1696 s"> have spoken</span><span class="H559 s">, saying</span><span class="H8147 s">, The two</span><span class="H4940 s"> families</span><span class="H3068 s"> which the LORD</span><span class="H977 s"> hath chosen</span><span class="H3988 s">, he hath even cast them off</span><span class="H5006 s">? thus they have despised</span><span class="H5971 s"> my people</span><span class="H1471 s">, that they should be no more a nation</span><span class="H6440 s"> before</span> them.</div> 
<div id="v300.33.25"><span class="H559 s">Thus saith</span><span class="H3068 s"> the LORD</span><span class="H1285 s">; If my covenant</span><span class="H3119 s"> <i>be</i> not with day</span><span class="H3915 s"> and night</span><span class="H7760 s">, <i>and if</i> I have not appointed</span><span class="H2708 s"> the ordinances</span><span class="H8064 s"> of heaven</span><span class="H776 s"> and earth</span>;</div> 
<div id="v300.33.26"><span class="H1571 s">Then</span><span class="H3988 s"> will I cast away</span><span class="H2233 s"> the seed</span><span class="H3290 s"> of Jacob</span><span class="H1732 s">, and David</span><span class="H5650 s"> my servant</span><span class="H3947 s">, <i>so</i> that I will not take</span><span class="H2233 s"> <i>any</i> of his seed</span><span class="H4910 s"> <i>to be</i> rulers</span><span class="H2233 s"> over the seed</span><span class="H85 s"> of Abraham</span><span class="H3446 s">, Isaac</span><span class="H3290 s">, and Jacob</span><span class="H7622 s">: for I will cause their captivity</span><span class="H7725 s"> to return</span><span class="H7725 s"> †</span><span class="H7355 s">, and have mercy</span> on them.</div></div> 
