<div class="c290_47">
<div id="v290.47.1"><span class="H3381 s">Come down</span><span class="H3427 s">, and sit</span><span class="H6083 s"> in the dust</span><span class="H1330 s">, O virgin</span><span class="H1323 s"> daughter</span><span class="H894 s"> of Babylon</span><span class="H3427 s">, sit</span><span class="H776 s"> on the ground</span><span class="H3678 s">: <i>there is</i> no throne</span><span class="H1323 s">, O daughter</span><span class="H3778 s"> of the Chaldeans</span><span class="H3254 s">: for thou shalt no more</span><span class="H7121 s"> be called</span><span class="H7390 s"> tender</span><span class="H6028 s"> and delicate</span>.</div>
<div id="v290.47.2"><span class="H3947 s">Take</span><span class="H7347 s"> the millstones</span><span class="H2912 s">, and grind</span><span class="H7058 s"> meal</span><span class="H1540 s">: uncover</span><span class="H6777 s"> thy locks</span><span class="H2834 s">, make bare</span><span class="H7640 s"> the leg</span><span class="H1540 s">, uncover</span><span class="H7785 s"> the thigh</span><span class="H5674 s">, pass over</span><span class="H5104 s"> the rivers</span>.</div>
<div id="v290.47.3"><span class="H6172 s">Thy nakedness</span><span class="H1540 s"> shall be uncovered</span><span class="H2781 s">, yea, thy shame</span><span class="H7200 s"> shall be seen</span><span class="H3947 s">: I will take</span><span class="H5359 s"> vengeance</span><span class="H6293 s">, and I will not meet</span><span class="H120 s"> <i>thee as</i> a man</span>.</div>
<div id="v290.47.4"><span class="H1350 s"><i>As for</i> our redeemer</span><span class="H3068 s">, the LORD</span><span class="H6635 s"> of hosts</span><span class="H8034 s"> <i>is</i> his name</span><span class="H6918 s">, the Holy One</span><span class="H3478 s"> of Israel</span>.</div>
<div id="v290.47.5"><span class="H3427 s">Sit</span><span class="H1748 s"> thou silent</span><span class="H935 s">, and get</span><span class="H2822 s"> thee into darkness</span><span class="H1323 s">, O daughter</span><span class="H3778 s"> of the Chaldeans</span><span class="H3254 s">: for thou shalt no more</span><span class="H7121 s"> be called</span><span class="H1404 s">, The lady</span><span class="H4467 s"> of kingdoms</span>.</div>
<div id="v290.47.6"><span class="H7107 s">I was wroth</span><span class="H5971 s"> with my people</span><span class="H2490 s">, I have polluted</span><span class="H5159 s"> mine inheritance</span><span class="H5414 s">, and given</span><span class="H3027 s"> them into thine hand</span><span class="H7760 s">: thou didst shew</span><span class="H7356 s"> them no mercy</span><span class="H2205 s">; upon the ancient</span><span class="H3966 s"> hast thou very</span><span class="H3513 s"> heavily</span><span class="H5923 s"> laid thy yoke</span>.</div>
<div id="v290.47.7"><span class="H559 s">And thou saidst</span><span class="H1404 s">, I shall be a lady</span><span class="H5769 s"> for ever</span><span class="H7760 s">: <i>so</i> that thou didst not lay</span><span class="H3820 s"> these <i>things</i> to thy heart</span><span class="H2142 s">, neither didst remember</span><span class="H319 s"> the latter end</span> of it.</div>
<div id="v290.47.8"><span class="H8085 s">Therefore hear</span><span class="H5719 s"> now this, <i>thou that art</i> given to pleasures</span><span class="H3427 s">, that dwellest</span><span class="H983 s"> carelessly</span><span class="H559 s">, that sayest</span><span class="H3824 s"> in thine heart</span><span class="H657 s">, I <i>am</i>, and none else</span><span class="H3427 s"> beside me; I shall not sit</span><span class="H490 s"> <i>as</i> a widow</span><span class="H3045 s">, neither shall I know</span><span class="H7908 s"> the loss of children</span>:</div>
<div id="v290.47.9"><span class="H8147 s">But these two</span><span class="H935 s"> <i>things</i> shall come</span><span class="H7281 s"> to thee in a moment</span><span class="H259 s"> in one</span><span class="H3117 s"> day</span><span class="H7908 s">, the loss of children</span><span class="H489 s">, and widowhood</span><span class="H935 s">: they shall come</span><span class="H8537 s"> upon thee in their perfection</span><span class="H7230 s"> for the multitude</span><span class="H3785 s"> of thy sorceries</span><span class="H3966 s">, <i>and</i> for the great</span><span class="H6109 s"> abundance</span><span class="H2267 s"> of thine enchantments</span>.</div>
<div id="v290.47.10"><span class="H982 s">For thou hast trusted</span><span class="H7451 s"> in thy wickedness</span><span class="H559 s">: thou hast said</span><span class="H7200 s">, None seeth</span><span class="H2451 s"> me. Thy wisdom</span><span class="H1847 s"> and thy knowledge</span><span class="H7725 s">, it hath perverted</span><span class="H559 s"> thee; and thou hast said</span><span class="H3820 s"> in thine heart</span><span class="H657 s">, I <i>am</i>, and none else</span> beside me. <span class="notes">Notes by the 1611 King James Bible Translators: (perverted…: or, caused thee to turn away)</span></div>
<div id="v290.47.11"><span class="H7451 s">Therefore shall evil</span><span class="H935 s"> come</span><span class="H3045 s"> upon thee; thou shalt not know</span><span class="H7837 s"> from whence it riseth</span><span class="H1943 s">: and mischief</span><span class="H5307 s"> shall fall</span><span class="H3201 s"> upon thee; thou shalt not be able</span><span class="H3722 s"> to put it off</span><span class="H7722 s">: and desolation</span><span class="H935 s"> shall come</span><span class="H6597 s"> upon thee suddenly</span><span class="H3045 s">, <i>which</i> thou shalt not know</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (from…: Heb. the morning thereof) (put: Heb. expiate)</span></div>
<div id="v290.47.12"><span class="H5975 s">Stand</span><span class="H2267 s"> now with thine enchantments</span><span class="H7230 s">, and with the multitude</span><span class="H3785 s"> of thy sorceries</span><span class="H834 s">, wherein</span><span class="H3021 s"> thou hast laboured</span><span class="H5271 s"> from thy youth</span><span class="H3201 s">; if so be thou shalt be able</span><span class="H3276 s"> to profit</span><span class="H6206 s">, if so be thou mayest prevail</span>.</div>
<div id="v290.47.13"><span class="H3811 s">Thou art wearied</span><span class="H7230 s"> in the multitude</span><span class="H6098 s"> of thy counsels</span><span class="H1895 s">. Let now the astrologers</span><span class="H8064 s"> †</span><span class="H2374 s">, the stargazers</span><span class="H3556 s"> †</span><span class="H2320 s">, the monthly</span><span class="H3045 s"> prognosticators</span><span class="H5975 s">, stand up</span><span class="H3467 s">, and save</span><span class="H935 s"> thee from <i>these things</i> that shall come</span> upon thee. <span class="notes">Notes by the 1611 King James Bible Translators: (astrologers: Heb. viewers of the heavens) (the monthly…: Heb. that give knowledge concerning the months)</span></div>
<div id="v290.47.14"><span class="H7179 s">Behold, they shall be as stubble</span><span class="H784 s">; the fire</span><span class="H8313 s"> shall burn</span><span class="H5337 s"> them; they shall not deliver</span><span class="H5315 s"> themselves</span><span class="H3027 s"> from the power</span><span class="H3852 s"> of the flame</span><span class="H1513 s">: <i>there shall</i> not <i>be</i> a coal</span><span class="H2552 s"> to warm</span><span class="H217 s"> at, <i>nor</i> fire</span><span class="H3427 s"> to sit</span> before it. <span class="notes">Notes by the 1611 King James Bible Translators: (themselves: Heb. their souls)</span></div>
<div id="v290.47.15"><span class="H3021 s">Thus shall they be unto thee with whom thou hast laboured</span><span class="H5503 s">, <i>even</i> thy merchants</span><span class="H5271 s">, from thy youth</span><span class="H8582 s">: they shall wander</span><span class="H376 s"> every one</span><span class="H5676 s"> to his quarter</span><span class="H3467 s">; none shall save</span> thee.</div></div>
