<div class="c300_2">
<div id="v300.2.1"><span class="H1697 s">Moreover the word</span><span class="H3068 s"> of the LORD</span><span class="H559 s"> came to me, saying</span>,</div>
<div id="v300.2.2"><span class="H1980 s">Go</span><span class="H7121 s"> and cry</span><span class="H241 s"> in the ears</span><span class="H3389 s"> of Jerusalem</span><span class="H559 s">, saying</span><span class="H559 s">, Thus saith</span><span class="H3068 s"> the LORD</span><span class="H2142 s">; I remember</span><span class="H2617 s"> thee, the kindness</span><span class="H5271 s"> of thy youth</span><span class="H160 s">, the love</span><span class="H3623 s"> of thine espousals</span><span class="H3212 s">, when thou wentest</span><span class="H310 s"> after</span><span class="H4057 s"> me in the wilderness</span><span class="H776 s">, in a land</span><span class="H2232 s"> <i>that was</i> not sown</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (thee: or, for thy sake)</span></div>
<div id="v300.2.3"><span class="H3478 s">Israel</span><span class="H6944 s"> <i>was</i> holiness</span><span class="H3068 s"> unto the LORD</span><span class="H7225 s">, <i>and</i> the firstfruits</span><span class="H8393 s"> of his increase</span><span class="H398 s">: all that devour</span><span class="H816 s"> him shall offend</span><span class="H7451 s">; evil</span><span class="H935 s"> shall come</span><span class="H5002 s"> upon them, saith</span><span class="H3068 s"> the LORD</span>.</div>
<div id="v300.2.4"><span class="H8085 s">Hear</span><span class="H1697 s"> ye the word</span><span class="H3068 s"> of the LORD</span><span class="H1004 s">, O house</span><span class="H3290 s"> of Jacob</span><span class="H4940 s">, and all the families</span><span class="H1004 s"> of the house</span><span class="H3478 s"> of Israel</span>:</div>
<div id="v300.2.5"><span class="H559 s">Thus saith</span><span class="H3068 s"> the LORD</span><span class="H5766 s">, What iniquity</span><span class="H1 s"> have your fathers</span><span class="H4672 s"> found</span><span class="H7368 s"> in me, that they are gone far</span><span class="H3212 s"> from me, and have walked</span><span class="H310 s"> after</span><span class="H1892 s"> vanity</span><span class="H1891 s">, and are become vain</span>?</div>
<div id="v300.2.6"><span class="H559 s">Neither said</span><span class="H3068 s"> they, Where <i>is</i> the LORD</span><span class="H5927 s"> that brought us up</span><span class="H776 s"> out of the land</span><span class="H4714 s"> of Egypt</span><span class="H3212 s">, that led</span><span class="H4057 s"> us through the wilderness</span><span class="H776 s">, through a land</span><span class="H6160 s"> of deserts</span><span class="H7745 s"> and of pits</span><span class="H776 s">, through a land</span><span class="H6723 s"> of drought</span><span class="H6757 s">, and of the shadow of death</span><span class="H776 s">, through a land</span><span class="H376 s"> that no man</span><span class="H5674 s"> passed through</span><span class="H120 s">, and where no man</span><span class="H3427 s"> dwelt</span>?</div>
<div id="v300.2.7"><span class="H935 s">And I brought</span><span class="H3759 s"> you into a plentiful</span><span class="H776 s"> country</span><span class="H398 s">, to eat</span><span class="H6529 s"> the fruit</span><span class="H2898 s"> thereof and the goodness</span><span class="H935 s"> thereof; but when ye entered</span><span class="H2930 s">, ye defiled</span><span class="H776 s"> my land</span><span class="H7760 s">, and made</span><span class="H5159 s"> mine heritage</span><span class="H8441 s"> an abomination</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (a plentiful…: or, the land of Carmel)</span></div>
<div id="v300.2.8"><span class="H3548 s">The priests</span><span class="H559 s"> said</span><span class="H3068 s"> not, Where <i>is</i> the LORD</span><span class="H8610 s">? and they that handle</span><span class="H8451 s"> the law</span><span class="H3045 s"> knew</span><span class="H7462 s"> me not: the pastors</span><span class="H6586 s"> also transgressed</span><span class="H5030 s"> against me, and the prophets</span><span class="H5012 s"> prophesied</span><span class="H1168 s"> by Baal</span><span class="H1980 s">, and walked</span><span class="H310 s"> after</span><span class="H3276 s"> <i>things that</i> do not profit</span>.</div>
<div id="v300.2.9"><span class="H7378 s">Wherefore I will yet plead</span><span class="H5002 s"> with you, saith</span><span class="H3068 s"> the LORD</span><span class="H1121 s">, and with your children's</span><span class="H1121 s"> children</span><span class="H7378 s"> will I plead</span>.</div>
<div id="v300.2.10"><span class="H5674 s">For pass over</span><span class="H339 s"> the isles</span><span class="H3794 s"> of Chittim</span><span class="H7200 s">, and see</span><span class="H7971 s">; and send</span><span class="H6938 s"> unto Kedar</span><span class="H995 s">, and consider</span><span class="H3966 s"> diligently</span><span class="H7200 s">, and see</span> if there be such a thing. <span class="notes">Notes by the 1611 King James Bible Translators: (over: or, over to)</span></div>
<div id="v300.2.11"><span class="H1471 s">Hath a nation</span><span class="H3235 s"> changed</span><span class="H430 s"> <i>their</i> gods</span><span class="H430 s">, which <i>are</i> yet no gods</span><span class="H5971 s">? but my people</span><span class="H4171 s"> have changed</span><span class="H3519 s"> their glory</span><span class="H3276 s"> for <i>that which</i> doth not profit</span>.</div>
<div id="v300.2.12"><span class="H8074 s">Be astonished</span><span class="H8064 s">, O ye heavens</span><span class="H8175 s">, at this, and be horribly afraid</span><span class="H3966 s">, be ye very</span><span class="H2717 s"> desolate</span><span class="H5002 s">, saith</span><span class="H3068 s"> the LORD</span>.</div>
<div id="v300.2.13"><span class="H5971 s">For my people</span><span class="H6213 s"> have committed</span><span class="H8147 s"> two</span><span class="H7451 s"> evils</span><span class="H5800 s">; they have forsaken</span><span class="H4726 s"> me the fountain</span><span class="H2416 s"> of living</span><span class="H4325 s"> waters</span><span class="H2672 s">, <i>and</i> hewed them out</span><span class="H877 s"> cisterns</span><span class="H7665 s">, broken</span><span class="H877 s"> cisterns</span><span class="H3557 s">, that can hold</span><span class="H4325 s"> no water</span>.</div>
<div id="v300.2.14"><span class="H3478 s"><i>Is</i> Israel</span><span class="H5650 s"> a servant</span><span class="H1004 s">? <i>is</i> he a homeborn</span><span class="H3211 s"> †</span><span class="H4069 s"> <i>slave</i>? why</span><span class="H957 s"> is he spoiled</span>? <span class="notes">Notes by the 1611 King James Bible Translators: (spoiled: Heb. become a spoil?)</span></div>
<div id="v300.2.15"><span class="H3715 s">The young lions</span><span class="H7580 s"> roared</span><span class="H5414 s"> upon him, <i>and</i> yelled</span><span class="H6963 s"> †</span><span class="H7896 s">, and they made</span><span class="H776 s"> his land</span><span class="H8047 s"> waste</span><span class="H5892 s">: his cities</span><span class="H3341 s"> are burned</span><span class="H3427 s"> without inhabitant</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (yelled: Heb. gave out their voice)</span></div>
<div id="v300.2.16"><span class="H1121 s">Also the children</span><span class="H5297 s"> of Noph</span><span class="H8471 s"> and Tahapanes</span><span class="H7462 s"> have broken</span><span class="H6936 s"> the crown of thy head</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (have…: or, feed on thy crown)</span></div>
<div id="v300.2.17"><span class="H6213 s">Hast thou not procured</span><span class="H5800 s"> this unto thyself, in that thou hast forsaken</span><span class="H3068 s"> the LORD</span><span class="H430 s"> thy God</span><span class="H6256 s">, when</span><span class="H3212 s"> he led</span><span class="H1870 s"> thee by the way</span>?</div>
<div id="v300.2.18"><span class="H1870 s">And now what hast thou to do in the way</span><span class="H4714 s"> of Egypt</span><span class="H8354 s">, to drink</span><span class="H4325 s"> the waters</span><span class="H7883 s"> of Sihor</span><span class="H1870 s">? or what hast thou to do in the way</span><span class="H804 s"> of Assyria</span><span class="H8354 s">, to drink</span><span class="H4325 s"> the waters</span><span class="H5104 s"> of the river</span>?</div>
<div id="v300.2.19"><span class="H7451 s">Thine own wickedness</span><span class="H3256 s"> shall correct</span><span class="H4878 s"> thee, and thy backslidings</span><span class="H3198 s"> shall reprove</span><span class="H3045 s"> thee: know</span><span class="H7200 s"> therefore and see</span><span class="H7451 s"> that <i>it is</i> an evil</span><span class="H4751 s"> <i>thing</i> and bitter</span><span class="H5800 s">, that thou hast forsaken</span><span class="H3068 s"> the LORD</span><span class="H430 s"> thy God</span><span class="H6345 s">, and that my fear</span><span class="H5002 s"> <i>is</i> not in thee, saith</span><span class="H136 s"> the Lord</span><span class="H3069 s"> GOD</span><span class="H6635 s"> of hosts</span>.</div>
<div id="v300.2.20"><span class="H5769 s">For of old time</span><span class="H7665 s"> I have broken</span><span class="H5923 s"> thy yoke</span><span class="H5423 s">, <i>and</i> burst</span><span class="H4147 s"> thy bands</span><span class="H559 s">; and thou saidst</span><span class="H5674 s">, I will not transgress</span><span class="H5647 s"> †</span><span class="H1364 s">; when upon every high</span><span class="H1389 s"> hill</span><span class="H7488 s"> and under every green</span><span class="H6086 s"> tree</span><span class="H6808 s"> thou wanderest</span><span class="H2181 s">, playing the harlot</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (transgress: or, serve)</span></div>
<div id="v300.2.21"><span class="H5193 s">Yet I had planted</span><span class="H8321 s"> thee a noble vine</span><span class="H571 s">, wholly a right</span><span class="H2233 s"> seed</span><span class="H2015 s">: how then art thou turned</span><span class="H5494 s"> into the degenerate plant</span><span class="H5237 s"> of a strange</span><span class="H1612 s"> vine</span> unto me?</div>
<div id="v300.2.22"><span class="H3526 s">For though thou wash</span><span class="H5427 s"> thee with nitre</span><span class="H7235 s">, and take thee much</span><span class="H1287 s"> soap</span><span class="H5771 s">, <i>yet</i> thine iniquity</span><span class="H3799 s"> is marked</span><span class="H6440 s"> before</span><span class="H5002 s"> me, saith</span><span class="H136 s"> the Lord</span><span class="H3069 s"> GOD</span>.</div>
<div id="v300.2.23"><span class="H559 s">How canst thou say</span><span class="H2930 s">, I am not polluted</span><span class="H1980 s">, I have not gone</span><span class="H310 s"> after</span><span class="H1168 s"> Baalim</span><span class="H7200 s">? see</span><span class="H1870 s"> thy way</span><span class="H1516 s"> in the valley</span><span class="H3045 s">, know</span><span class="H6213 s"> what thou hast done</span><span class="H7031 s">: <i>thou art</i> a swift</span><span class="H1072 s"> dromedary</span><span class="H8308 s"> traversing</span><span class="H1870 s"> her ways</span>; <span class="notes">Notes by the 1611 King James Bible Translators: (thou art…: or, O swift dromedary)</span></div>
<div id="v300.2.24"><span class="H6501 s">A wild ass</span><span class="H3928 s"> used</span><span class="H4057 s"> to the wilderness</span><span class="H7602 s">, <i>that</i> snuffeth up</span><span class="H7307 s"> the wind</span><span class="H185 s"> at her pleasure</span><span class="H5315 s"> †</span><span class="H8385 s">; in her occasion</span><span class="H7725 s"> who can turn her away</span><span class="H1245 s">? all they that seek</span><span class="H3286 s"> her will not weary</span><span class="H2320 s"> themselves; in her month</span><span class="H4672 s"> they shall find</span> her. <span class="notes">Notes by the 1611 King James Bible Translators: (A wild…: or, O wild ass, etc) (used: Heb. taught) (her pleasure: Heb. the desire of her heart) (turn…: or, reverse it?)</span></div>
<div id="v300.2.25"><span class="H4513 s">Withhold</span><span class="H7272 s"> thy foot</span><span class="H3182 s"> from being unshod</span><span class="H1627 s">, and thy throat</span><span class="H6773 s"> from thirst</span><span class="H559 s">: but thou saidst</span><span class="H2976 s">, There is no hope</span><span class="H157 s">: no; for I have loved</span><span class="H2114 s"> strangers</span><span class="H310 s">, and after</span><span class="H3212 s"> them will I go</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (There…: or, Is the case desperate?)</span></div>
<div id="v300.2.26"><span class="H1590 s">As the thief</span><span class="H1322 s"> is ashamed</span><span class="H4672 s"> when he is found</span><span class="H1004 s">, so is the house</span><span class="H3478 s"> of Israel</span><span class="H3001 s"> ashamed</span><span class="H4428 s">; they, their kings</span><span class="H8269 s">, their princes</span><span class="H3548 s">, and their priests</span><span class="H5030 s">, and their prophets</span>,</div>
<div id="v300.2.27"><span class="H559 s">Saying</span><span class="H6086 s"> to a stock</span><span class="H1 s">, Thou <i>art</i> my father</span><span class="H68 s">; and to a stone</span><span class="H3205 s">, Thou hast brought me forth</span><span class="H6437 s">: for they have turned</span><span class="H6203 s"> <i>their</i> back</span><span class="H6440 s"> unto me, and not <i>their</i> face</span><span class="H6256 s">: but in the time</span><span class="H7451 s"> of their trouble</span><span class="H559 s"> they will say</span><span class="H6965 s">, Arise</span><span class="H3467 s">, and save</span> us. <span class="notes">Notes by the 1611 King James Bible Translators: (brought…: or, begotten me) (their back: Heb. the hinder part of the neck)</span></div>
<div id="v300.2.28"><span class="H430 s">But where <i>are</i> thy gods</span><span class="H6213 s"> that thou hast made</span><span class="H6965 s"> thee? let them arise</span><span class="H3467 s">, if they can save</span><span class="H6256 s"> thee in the time</span><span class="H7451 s"> of thy trouble</span><span class="H4557 s">: for <i>according to</i> the number</span><span class="H5892 s"> of thy cities</span><span class="H430 s"> are thy gods</span><span class="H3063 s">, O Judah</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (trouble: Heb. evil)</span></div>
<div id="v300.2.29"><span class="H7378 s">Wherefore will ye plead</span><span class="H6586 s"> with me? ye all have transgressed</span><span class="H5002 s"> against me, saith</span><span class="H3068 s"> the LORD</span>.</div>
<div id="v300.2.30"><span class="H7723 s">In vain</span><span class="H5221 s"> have I smitten</span><span class="H1121 s"> your children</span><span class="H3947 s">; they received</span><span class="H4148 s"> no correction</span><span class="H2719 s">: your own sword</span><span class="H398 s"> hath devoured</span><span class="H5030 s"> your prophets</span><span class="H7843 s">, like a destroying</span><span class="H738 s"> lion</span>.</div>
<div id="v300.2.31"><span class="H1755 s">O generation</span><span class="H7200 s">, see</span><span class="H1697 s"> ye the word</span><span class="H3068 s"> of the LORD</span><span class="H4057 s">. Have I been a wilderness</span><span class="H3478 s"> unto Israel</span><span class="H776 s">? a land</span><span class="H3991 s"> of darkness</span><span class="H559 s">? wherefore say</span><span class="H5971 s"> my people</span><span class="H7300 s">, We are lords</span><span class="H935 s">; we will come</span> no more unto thee? <span class="notes">Notes by the 1611 King James Bible Translators: (We are…: Heb. We have dominion)</span></div>
<div id="v300.2.32"><span class="H1330 s">Can a maid</span><span class="H7911 s"> forget</span><span class="H5716 s"> her ornaments</span><span class="H3618 s">, <i>or</i> a bride</span><span class="H7196 s"> her attire</span><span class="H5971 s">? yet my people</span><span class="H7911 s"> have forgotten</span><span class="H3117 s"> me days</span><span class="H4557 s"> without number</span>.</div>
<div id="v300.2.33"><span class="H3190 s">Why trimmest</span><span class="H1870 s"> thou thy way</span><span class="H1245 s"> to seek</span><span class="H160 s"> love</span><span class="H3925 s">? therefore hast thou also taught</span><span class="H7451 s"> the wicked ones</span><span class="H1870 s"> thy ways</span>.</div>
<div id="v300.2.34"><span class="H3671 s">Also in thy skirts</span><span class="H4672 s"> is found</span><span class="H1818 s"> the blood</span><span class="H5315 s"> of the souls</span><span class="H34 s"> of the poor</span><span class="H5355 s"> innocents</span><span class="H4672 s">: I have not found</span><span class="H4290 s"> it by secret search</span>, but upon all these. <span class="notes">Notes by the 1611 King James Bible Translators: (secret…: Heb. digging)</span></div>
<div id="v300.2.35"><span class="H559 s">Yet thou sayest</span><span class="H5352 s">, Because I am innocent</span><span class="H639 s">, surely his anger</span><span class="H7725 s"> shall turn</span><span class="H8199 s"> from me. Behold, I will plead</span><span class="H559 s"> with thee, because thou sayest</span><span class="H2398 s">, I have not sinned</span>.</div>
<div id="v300.2.36"><span class="H235 s">Why gaddest thou about</span><span class="H3966 s"> so much</span><span class="H8138 s"> to change</span><span class="H1870 s"> thy way</span><span class="H954 s">? thou also shalt be ashamed</span><span class="H4714 s"> of Egypt</span><span class="H954 s">, as thou wast ashamed</span><span class="H804 s"> of Assyria</span>.</div>
<div id="v300.2.37"><span class="H3318 s">Yea, thou shalt go forth</span><span class="H3027 s"> from him, and thine hands</span><span class="H7218 s"> upon thine head</span><span class="H3068 s">: for the LORD</span><span class="H3988 s"> hath rejected</span><span class="H4009 s"> thy confidences</span><span class="H6743 s">, and thou shalt not prosper</span> in them.</div></div>
