<div class="c240_30">
<div id="v240.30.1"><span class="H1697 s">The words</span><span class="H94 s"> of Agur</span><span class="H1121 s"> the son</span><span class="H3348 s"> of Jakeh</span><span class="H4853 s">, <i>even</i> the prophecy</span><span class="H1397 s">: the man</span><span class="H5002 s"> spake</span><span class="H384 s"> unto Ithiel</span><span class="H384 s">, even unto Ithiel</span><span class="H401 s"> and Ucal</span>,</div>
<div id="v240.30.2"><span class="H1198 s">Surely I <i>am</i> more brutish</span><span class="H376 s"> than <i>any</i> man</span><span class="H998 s">, and have not the understanding</span><span class="H120 s"> of a man</span>.</div>
<div id="v240.30.3"><span class="H3925 s">I neither learned</span><span class="H2451 s"> wisdom</span><span class="H3045 s">, nor have</span><span class="H1847 s"> the knowledge</span><span class="H6918 s"> of the holy</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (have: Heb. know)</span></div>
<div id="v240.30.4"><span class="H5927 s">Who hath ascended up</span><span class="H8064 s"> into heaven</span><span class="H3381 s">, or descended</span><span class="H622 s">? who hath gathered</span><span class="H7307 s"> the wind</span><span class="H2651 s"> in his fists</span><span class="H6887 s">? who hath bound</span><span class="H4325 s"> the waters</span><span class="H8071 s"> in a garment</span><span class="H6965 s">? who hath established</span><span class="H657 s"> all the ends</span><span class="H776 s"> of the earth</span><span class="H8034 s">? what <i>is</i> his name</span><span class="H1121 s">, and what <i>is</i> his son's</span><span class="H8034 s"> name</span><span class="H3045 s">, if thou canst tell</span>?</div>
<div id="v240.30.5"><span class="H565 s">Every word</span><span class="H433 s"> of God</span><span class="H6884 s"> <i>is</i> pure</span><span class="H4043 s">: he <i>is</i> a shield</span><span class="H2620 s"> unto them that put their trust</span> in him. <span class="notes">Notes by the 1611 King James Bible Translators: (pure: Heb. purified)</span></div>
<div id="v240.30.6"><span class="H3254 s">Add</span><span class="H1697 s"> thou not unto his words</span><span class="H3198 s">, lest he reprove</span><span class="H3576 s"> thee, and thou be found a liar</span>.</div>
<div id="v240.30.7"><span class="H8147 s">Two</span><span class="H7592 s"> <i>things</i> have I required</span><span class="H4513 s"> of thee; deny</span><span class="H4191 s"> me <i>them</i> not before I die</span>: <span class="notes">Notes by the 1611 King James Bible Translators: (deny…: Heb. withhold not from me)</span></div>
<div id="v240.30.8"><span class="H7368 s">Remove far</span><span class="H7723 s"> from me vanity</span><span class="H1697 s"> and lies</span><span class="H3577 s"> †</span><span class="H5414 s">: give</span><span class="H7389 s"> me neither poverty</span><span class="H6239 s"> nor riches</span><span class="H2963 s">; feed</span><span class="H3899 s"> me with food</span><span class="H2706 s"> convenient</span> for me: <span class="notes">Notes by the 1611 King James Bible Translators: (convenient…: Heb. of my allowance)</span></div>
<div id="v240.30.9"><span class="H7646 s">Lest I be full</span><span class="H3584 s">, and deny</span><span class="H559 s"> <i>thee</i>, and say</span><span class="H3068 s">, Who <i>is</i> the LORD</span><span class="H3423 s">? or lest I be poor</span><span class="H1589 s">, and steal</span><span class="H8610 s">, and take</span><span class="H8034 s"> the name</span><span class="H430 s"> of my God</span> <i>in vain</i>. <span class="notes">Notes by the 1611 King James Bible Translators: (deny…: Heb. belie thee)</span></div>
<div id="v240.30.10"><span class="H3960 s">Accuse</span><span class="H5650 s"> not a servant</span><span class="H113 s"> unto his master</span><span class="H7043 s">, lest he curse</span><span class="H816 s"> thee, and thou be found guilty</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (Accuse…: Heb. Hurt not with thy tongue)</span></div>
<div id="v240.30.11"><span class="H1755 s"><i>There is</i> a generation</span><span class="H7043 s"> <i>that</i> curseth</span><span class="H1 s"> their father</span><span class="H1288 s">, and doth not bless</span><span class="H517 s"> their mother</span>.</div>
<div id="v240.30.12"><span class="H1755 s"><i>There is</i> a generation</span><span class="H2889 s"> <i>that are</i> pure</span><span class="H5869 s"> in their own eyes</span><span class="H7364 s">, and <i>yet</i> is not washed</span><span class="H6675 s"> from their filthiness</span>.</div>
<div id="v240.30.13"><span class="H1755 s"><i>There is</i> a generation</span><span class="H7311 s">, O how lofty</span><span class="H5869 s"> are their eyes</span><span class="H6079 s">! and their eyelids</span><span class="H5375 s"> are lifted up</span>.</div>
<div id="v240.30.14"><span class="H1755 s"><i>There is</i> a generation</span><span class="H8127 s">, whose teeth</span><span class="H2719 s"> <i>are as</i> swords</span><span class="H4973 s">, and their jaw teeth</span><span class="H3979 s"> <i>as</i> knives</span><span class="H398 s">, to devour</span><span class="H6041 s"> the poor</span><span class="H776 s"> from off the earth</span><span class="H34 s">, and the needy</span><span class="H120 s"> from <i>among</i> men</span>.</div>
<div id="v240.30.15"><span class="H5936 s">The horseleach</span><span class="H8147 s"> hath two</span><span class="H1323 s"> daughters</span><span class="H3051 s">, <i>crying</i>, Give</span><span class="H3051 s">, give</span><span class="H7969 s">. There are three</span><span class="H7646 s"> <i>things that</i> are never satisfied</span><span class="H702 s">, <i>yea</i>, four</span><span class="H559 s"> <i>things</i> say</span><span class="H1952 s"> not, <i>It is</i> enough</span>: <span class="notes">Notes by the 1611 King James Bible Translators: (It is…: Heb. Wealth)</span></div>
<div id="v240.30.16"><span class="H7585 s">The grave</span><span class="H6115 s">; and the barren</span><span class="H7356 s"> womb</span><span class="H776 s">; the earth</span><span class="H7646 s"> <i>that</i> is not filled</span><span class="H4325 s"> with water</span><span class="H784 s">; and the fire</span><span class="H559 s"> <i>that</i> saith</span><span class="H1952 s"> not, <i>It is</i> enough</span>.</div>
<div id="v240.30.17"><span class="H5869 s">The eye</span><span class="H3932 s"> <i>that</i> mocketh</span><span class="H1 s"> at <i>his</i> father</span><span class="H936 s">, and despiseth</span><span class="H3349 s"> to obey</span><span class="H517 s"> <i>his</i> mother</span><span class="H6158 s">, the ravens</span><span class="H5158 s"> of the valley</span><span class="H5365 s"> shall pick it out</span><span class="H1121 s">, and the young</span><span class="H5404 s"> eagles</span><span class="H398 s"> shall eat</span> it. <span class="notes">Notes by the 1611 King James Bible Translators: (the valley: or, the brook)</span></div>
<div id="v240.30.18"><span class="H7969 s">There be three</span><span class="H6381 s"> <i>things which</i> are too wonderful</span><span class="H702 s"> for me, yea, four</span><span class="H3045 s"> which I know</span> not:</div>
<div id="v240.30.19"><span class="H1870 s">The way</span><span class="H5404 s"> of an eagle</span><span class="H8064 s"> in the air</span><span class="H1870 s">; the way</span><span class="H5175 s"> of a serpent</span><span class="H6697 s"> upon a rock</span><span class="H1870 s">; the way</span><span class="H591 s"> of a ship</span><span class="H3820 s"> in the midst</span><span class="H3220 s"> of the sea</span><span class="H1870 s">; and the way</span><span class="H1397 s"> of a man</span><span class="H5959 s"> with a maid</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (midst: Heb. heart)</span></div>
<div id="v240.30.20"><span class="H1870 s">Such <i>is</i> the way</span><span class="H5003 s"> of an adulterous</span><span class="H802 s"> woman</span><span class="H398 s">; she eateth</span><span class="H4229 s">, and wipeth</span><span class="H6310 s"> her mouth</span><span class="H559 s">, and saith</span><span class="H6466 s">, I have done</span><span class="H205 s"> no wickedness</span>.</div>
<div id="v240.30.21"><span class="H7969 s">For three</span><span class="H776 s"> <i>things</i> the earth</span><span class="H7264 s"> is disquieted</span><span class="H702 s">, and for four</span><span class="H3201 s"> <i>which</i> it cannot</span><span class="H5375 s"> bear</span>:</div>
<div id="v240.30.22"><span class="H5650 s">For a servant</span><span class="H4427 s"> when he reigneth</span><span class="H5036 s">; and a fool</span><span class="H7646 s"> when he is filled</span><span class="H3899 s"> with meat</span>;</div>
<div id="v240.30.23"><span class="H8130 s">For an odious</span><span class="H1166 s"> <i>woman</i> when she is married</span><span class="H8198 s">; and an handmaid</span><span class="H3423 s"> that is heir</span><span class="H1404 s"> to her mistress</span>.</div>
<div id="v240.30.24"><span class="H702 s">There be four</span><span class="H6996 s"> <i>things which are</i> little</span><span class="H776 s"> upon the earth</span><span class="H2449 s">, but they <i>are</i> exceeding</span><span class="H2450 s"> wise</span>: <span class="notes">Notes by the 1611 King James Bible Translators: (exceeding…: Heb. wise, made wise)</span></div>
<div id="v240.30.25"><span class="H5244 s">The ants</span><span class="H5971 s"> <i>are</i> a people</span><span class="H5794 s"> not strong</span><span class="H3559 s">, yet they prepare</span><span class="H3899 s"> their meat</span><span class="H7019 s"> in the summer</span>;</div>
<div id="v240.30.26"><span class="H8227 s">The conies</span><span class="H6099 s"> <i>are but</i> a feeble</span><span class="H5971 s"> folk</span><span class="H7760 s">, yet make</span><span class="H1004 s"> they their houses</span><span class="H5553 s"> in the rocks</span>;</div>
<div id="v240.30.27"><span class="H697 s">The locusts</span><span class="H4428 s"> have no king</span><span class="H3318 s">, yet go they forth</span><span class="H2686 s"> all of them by bands</span>; <span class="notes">Notes by the 1611 King James Bible Translators: (by…: Heb. gathered together)</span></div>
<div id="v240.30.28"><span class="H8079 s">The spider</span><span class="H8610 s"> taketh hold</span><span class="H3027 s"> with her hands</span><span class="H1964 s">, and is in kings' H4428 palaces</span>.</div>
<div id="v240.30.29"><span class="H7969 s">There be three</span><span class="H6806 s"> <i>things</i> which go</span><span class="H3190 s"> well</span><span class="H702 s">, yea, four</span><span class="H2895 s"> are comely</span><span class="H3212 s"> in going</span>:</div>
<div id="v240.30.30"><span class="H3918 s">A lion</span><span class="H1368 s"> <i>which is</i> strongest</span><span class="H929 s"> among beasts</span><span class="H7725 s">, and turneth not away</span><span class="H6440 s"> for</span> any;</div>
<div id="v240.30.31"><span class="H4975 s">A greyhound</span><span class="H2223 s"> †</span><span class="H8495 s">; an he goat</span><span class="H176 s"> also</span><span class="H4428 s">; and a king</span><span class="H510 s">, against whom <i>there is</i> no rising up</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (greyhound: or, horse: Heb. girt in the loins)</span></div>
<div id="v240.30.32"><span class="H5034 s">If thou hast done foolishly</span><span class="H5375 s"> in lifting up</span><span class="H2161 s"> thyself, or if thou hast thought evil</span><span class="H3027 s">, <i>lay</i> thine hand</span><span class="H6310 s"> upon thy mouth</span>.</div>
<div id="v240.30.33"><span class="H4330 s">Surely the churning</span><span class="H2461 s"> of milk</span><span class="H3318 s"> bringeth forth</span><span class="H2529 s"> butter</span><span class="H4330 s">, and the wringing</span><span class="H639 s"> of the nose</span><span class="H3318 s"> bringeth forth</span><span class="H1818 s"> blood</span><span class="H4330 s">: so the forcing</span><span class="H639 s"> of wrath</span><span class="H3318 s"> bringeth forth</span><span class="H7379 s"> strife</span>.</div></div>
