<div class="c80_1">
<div id="v80.1.1"><span class="H3117 s">Now it came to pass in the days</span><span class="H8199 s"> when the judges</span><span class="H8199 s"> ruled</span><span class="H7458 s">, that there was a famine</span><span class="H776 s"> in the land</span><span class="H376 s">. And a certain man</span><span class="H1035 s"> of Bethlehemjudah</span><span class="H3063 s"> †</span><span class="H3212 s"> went</span><span class="H1481 s"> to sojourn</span><span class="H7704 s"> in the country</span><span class="H4124 s"> of Moab</span><span class="H802 s">, he, and his wife</span><span class="H8147 s">, and his two</span><span class="H1121 s"> sons</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (ruled: Heb. judged)</span></div>
<div id="v80.1.2"><span class="H8034 s">And the name</span><span class="H376 s"> of the man</span><span class="H458 s"> <i>was</i> Elimelech</span><span class="H8034 s">, and the name</span><span class="H802 s"> of his wife</span><span class="H5281 s"> Naomi</span><span class="H8034 s">, and the name</span><span class="H8147 s"> of his two</span><span class="H1121 s"> sons</span><span class="H4248 s"> Mahlon</span><span class="H3630 s"> and Chilion</span><span class="H673 s">, Ephrathites</span><span class="H1035 s"> of Bethlehemjudah</span><span class="H3063 s"> †</span><span class="H935 s">. And they came</span><span class="H7704 s"> into the country</span><span class="H4124 s"> of Moab</span>, and continued there. <span class="notes">Notes by the 1611 King James Bible Translators: (continued: Heb. were)</span></div>
<div id="v80.1.3"><span class="H458 s">And Elimelech</span><span class="H5281 s"> Naomi's</span><span class="H376 s"> husband</span><span class="H4191 s"> died</span><span class="H7604 s">; and she was left</span><span class="H8147 s">, and her two</span><span class="H1121 s"> sons</span>.</div>
<div id="v80.1.4"><span class="H5375 s">And they took</span><span class="H802 s"> them wives</span><span class="H802 s"> of the women</span><span class="H4125 s"> of Moab</span><span class="H8034 s">; the name</span><span class="H259 s"> of the one</span><span class="H6204 s"> <i>was</i> Orpah</span><span class="H8034 s">, and the name</span><span class="H8145 s"> of the other</span><span class="H7327 s"> Ruth</span><span class="H3427 s">: and they dwelled</span><span class="H6235 s"> there about ten</span><span class="H8141 s"> years</span>.</div>
<div id="v80.1.5"><span class="H4248 s">And Mahlon</span><span class="H3630 s"> and Chilion</span><span class="H4191 s"> died</span><span class="H8147 s"> also both</span><span class="H802 s"> of them; and the woman</span><span class="H7604 s"> was left</span><span class="H8147 s"> of her two</span><span class="H3206 s"> sons</span><span class="H376 s"> and her husband</span>.</div>
<div id="v80.1.6"><span class="H6965 s">Then she arose</span><span class="H3618 s"> with her daughters in law</span><span class="H7725 s">, that she might return</span><span class="H7704 s"> from the country</span><span class="H4124 s"> of Moab</span><span class="H8085 s">: for she had heard</span><span class="H7704 s"> in the country</span><span class="H4124 s"> of Moab</span><span class="H3068 s"> how that the LORD</span><span class="H6485 s"> had visited</span><span class="H5971 s"> his people</span><span class="H5414 s"> in giving</span><span class="H3899 s"> them bread</span>.</div>
<div id="v80.1.7"><span class="H3318 s">Wherefore she went forth</span><span class="H4725 s"> out of the place</span><span class="H8147 s"> where she was, and her two</span><span class="H3618 s"> daughters in law</span><span class="H3212 s"> with her; and they went</span><span class="H1870 s"> on the way</span><span class="H7725 s"> to return</span><span class="H776 s"> unto the land</span><span class="H3063 s"> of Judah</span>.</div>
<div id="v80.1.8"><span class="H5281 s">And Naomi</span><span class="H559 s"> said</span><span class="H8147 s"> unto her two</span><span class="H3618 s"> daughters in law</span><span class="H3212 s">, Go</span><span class="H7725 s">, return</span><span class="H802 s"> each</span><span class="H517 s"> to her mother's</span><span class="H1004 s"> house</span><span class="H3068 s">: the LORD</span><span class="H6213 s"> deal</span><span class="H2617 s"> kindly</span><span class="H6213 s"> with you, as ye have dealt</span><span class="H4191 s"> with the dead</span>, and with me.</div>
<div id="v80.1.9"><span class="H3068 s">The LORD</span><span class="H5414 s"> grant</span><span class="H4672 s"> you that ye may find</span><span class="H4496 s"> rest</span><span class="H802 s">, each</span><span class="H1004 s"> <i>of you</i> in the house</span><span class="H376 s"> of her husband</span><span class="H5401 s">. Then she kissed</span><span class="H5375 s"> them; and they lifted up</span><span class="H6963 s"> their voice</span><span class="H1058 s">, and wept</span>.</div>
<div id="v80.1.10"><span class="H559 s">And they said</span><span class="H7725 s"> unto her, Surely we will return</span><span class="H5971 s"> with thee unto thy people</span>.</div>
<div id="v80.1.11"><span class="H5281 s">And Naomi</span><span class="H559 s"> said</span><span class="H7725 s">, Turn again</span><span class="H1323 s">, my daughters</span><span class="H3212 s">: why will ye go</span><span class="H1121 s"> with me? <i>are</i> there yet <i>any more</i> sons</span><span class="H4578 s"> in my womb</span><span class="H582 s">, that they may be your husbands</span>?</div>
<div id="v80.1.12"><span class="H7725 s">Turn again</span><span class="H1323 s">, my daughters</span><span class="H3212 s">, go</span><span class="H2204 s"> <i>your way</i>; for I am too old</span><span class="H376 s"> to have an husband</span><span class="H559 s">. If I should say</span><span class="H3426 s">, I have</span><span class="H8615 s"> hope</span><span class="H376 s">, <i>if</i> I should have an husband</span><span class="H3915 s"> also to night</span><span class="H3205 s">, and should also bear</span><span class="H1121 s"> sons</span>; <span class="notes">Notes by the 1611 King James Bible Translators: (should have…: or were with an husband)</span></div>
<div id="v80.1.13"><span class="H7663 s">Would ye tarry</span><span class="H3860 s"> for them</span><span class="H1431 s"> till they were grown</span><span class="H5702 s">? would ye stay</span><span class="H3860 s"> for them</span><span class="H376 s"> from having husbands</span><span class="H1323 s">? nay, my daughters</span><span class="H4843 s">; for it grieveth</span><span class="H3966 s"> me much</span><span class="H3027 s"> for your sakes that the hand</span><span class="H3068 s"> of the LORD</span><span class="H3318 s"> is gone out</span> against me. <span class="notes">Notes by the 1611 King James Bible Translators: (tarry: Heb. hope) (it grieveth…: Heb. I have much bitterness)</span></div>
<div id="v80.1.14"><span class="H5375 s">And they lifted up</span><span class="H6963 s"> their voice</span><span class="H1058 s">, and wept again</span><span class="H6204 s">: and Orpah</span><span class="H5401 s"> kissed</span><span class="H2545 s"> her mother in law</span><span class="H7327 s">; but Ruth</span><span class="H1692 s"> clave</span> unto her.</div>
<div id="v80.1.15"><span class="H559 s">And she said</span><span class="H2994 s">, Behold, thy sister in law</span><span class="H7725 s"> is gone back</span><span class="H5971 s"> unto her people</span><span class="H430 s">, and unto her gods</span><span class="H7725 s">: return</span><span class="H310 s"> thou after</span><span class="H2994 s"> thy sister in law</span>.</div>
<div id="v80.1.16"><span class="H7327 s">And Ruth</span><span class="H559 s"> said</span><span class="H6293 s">, Intreat</span><span class="H5800 s"> me not to leave</span><span class="H7725 s"> thee, <i>or</i> to return</span><span class="H310 s"> from following after</span><span class="H3212 s"> thee: for whither thou goest</span><span class="H3212 s">, I will go</span><span class="H3885 s">; and where thou lodgest</span><span class="H3885 s">, I will lodge</span><span class="H5971 s">: thy people</span><span class="H5971 s"> <i>shall be</i> my people</span><span class="H430 s">, and thy God</span><span class="H430 s"> my God</span>: <span class="notes">Notes by the 1611 King James Bible Translators: (Intreat…: or, Be not against me)</span></div>
<div id="v80.1.17"><span class="H4191 s">Where thou diest</span><span class="H4191 s">, will I die</span><span class="H6912 s">, and there will I be buried</span><span class="H3068 s">: the LORD</span><span class="H6213 s"> do</span><span class="H3254 s"> so to me, and more</span><span class="H4194 s"> also, <i>if ought</i> but death</span><span class="H6504 s"> part</span> thee and me.</div>
<div id="v80.1.18"><span class="H7200 s">When she saw</span><span class="H553 s"> that she was stedfastly minded</span><span class="H3212 s"> to go</span><span class="H2308 s"> with her, then she left</span><span class="H1696 s"> speaking</span> unto her. <span class="notes">Notes by the 1611 King James Bible Translators: (was…: Heb. strengthened herself)</span></div>
<div id="v80.1.19"><span class="H8147 s">So they two</span><span class="H3212 s"> went</span><span class="H935 s"> until they came</span><span class="H1035 s"> to Bethlehem</span><span class="H935 s">. And it came to pass, when they were come</span><span class="H1035 s"> to Bethlehem</span><span class="H5892 s">, that all the city</span><span class="H1949 s"> was moved</span><span class="H559 s"> about them, and they said</span><span class="H5281 s">, <i>Is</i> this Naomi</span>?</div>
<div id="v80.1.20"><span class="H559 s">And she said</span><span class="H7121 s"> unto them, Call</span><span class="H5281 s"> me not Naomi</span><span class="H7121 s">, call</span><span class="H4755 s"> me Mara</span><span class="H7706 s">: for the Almighty</span><span class="H3966 s"> hath dealt very</span><span class="H4843 s"> bitterly</span> with me. <span class="notes">Notes by the 1611 King James Bible Translators: (Naomi: that is, Pleasant) (Mara: that is, Bitter)</span></div>
<div id="v80.1.21"><span class="H1980 s">I went out</span><span class="H4392 s"> full</span><span class="H3068 s">, and the LORD</span><span class="H7725 s"> hath brought me home again</span><span class="H7387 s"> empty</span><span class="H7121 s">: why <i>then</i> call</span><span class="H5281 s"> ye me Naomi</span><span class="H3068 s">, seeing the LORD</span><span class="H6030 s"> hath testified</span><span class="H7706 s"> against me, and the Almighty</span><span class="H7489 s"> hath afflicted</span> me?</div>
<div id="v80.1.22"><span class="H5281 s">So Naomi</span><span class="H7725 s"> returned</span><span class="H7327 s">, and Ruth</span><span class="H4125 s"> the Moabitess</span><span class="H3618 s">, her daughter in law</span><span class="H7725 s">, with her, which returned</span><span class="H7704 s"> out of the country</span><span class="H4124 s"> of Moab</span><span class="H935 s">: and they came</span><span class="H1035 s"> to Bethlehem</span><span class="H8462 s"> in the beginning</span><span class="H8184 s"> of barley</span><span class="H7105 s"> harvest</span>.</div></div>
