<div class="c220_42">
<div id="v220.42.1"><span class="H347 s">Then Job</span><span class="H6030 s"> answered</span><span class="H3068 s"> the LORD</span><span class="H559 s">, and said</span>,</div>
<div id="v220.42.2"><span class="H3045 s">I know</span><span class="H3201 s"> that thou canst do</span><span class="H4209 s"> every <i>thing</i>, and <i>that</i> no thought</span><span class="H1219 s"> can be withholden</span> from thee. <span class="notes">Notes by the 1611 King James Bible Translators: (no thought can be…: or, no thought of thine can be hindered)</span></div>
<div id="v220.42.3"><span class="H5956 s">Who <i>is</i> he that hideth</span><span class="H6098 s"> counsel</span><span class="H1847 s"> without knowledge</span><span class="H5046 s">? therefore have I uttered</span><span class="H995 s"> that I understood</span><span class="H6381 s"> not; things too wonderful</span><span class="H3045 s"> for me, which I knew</span> not.</div>
<div id="v220.42.4"><span class="H8085 s">Hear</span><span class="H1696 s">, I beseech thee, and I will speak</span><span class="H7592 s">: I will demand</span><span class="H3045 s"> of thee, and declare</span> thou unto me.</div>
<div id="v220.42.5"><span class="H8085 s">I have heard</span><span class="H8088 s"> of thee by the hearing</span><span class="H241 s"> of the ear</span><span class="H5869 s">: but now mine eye</span><span class="H7200 s"> seeth</span> thee.</div>
<div id="v220.42.6"><span class="H3988 s">Wherefore I abhor</span><span class="H5162 s"> <i>myself</i>, and repent</span><span class="H6083 s"> in dust</span><span class="H665 s"> and ashes</span>.</div>
<div id="v220.42.7"><span class="H310 s">And it was <i>so</i>, that after</span><span class="H3068 s"> the LORD</span><span class="H1696 s"> had spoken</span><span class="H1697 s"> these words</span><span class="H347 s"> unto Job</span><span class="H3068 s">, the LORD</span><span class="H559 s"> said</span><span class="H464 s"> to Eliphaz</span><span class="H8489 s"> the Temanite</span><span class="H639 s">, My wrath</span><span class="H2734 s"> is kindled</span><span class="H8147 s"> against thee, and against thy two</span><span class="H7453 s"> friends</span><span class="H1696 s">: for ye have not spoken</span><span class="H3559 s"> of me <i>the thing that is</i> right</span><span class="H5650 s">, as my servant</span><span class="H347 s"> Job</span> <i>hath</i>.</div>
<div id="v220.42.8"><span class="H3947 s">Therefore take</span><span class="H7651 s"> unto you now seven</span><span class="H6499 s"> bullocks</span><span class="H7651 s"> and seven</span><span class="H352 s"> rams</span><span class="H3212 s">, and go</span><span class="H5650 s"> to my servant</span><span class="H347 s"> Job</span><span class="H5927 s">, and offer up</span><span class="H5930 s"> for yourselves a burnt offering</span><span class="H5650 s">; and my servant</span><span class="H347 s"> Job</span><span class="H6419 s"> shall pray</span><span class="H6440 s"> for you: for him</span><span class="H5375 s"> will I accept</span><span class="H6213 s">: lest I deal</span><span class="H5039 s"> with you <i>after your</i> folly</span><span class="H1696 s">, in that ye have not spoken</span><span class="H3559 s"> of me <i>the thing which is</i> right</span><span class="H5650 s">, like my servant</span><span class="H347 s"> Job</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (him: Heb. his face, or, person)</span></div>
<div id="v220.42.9"><span class="H464 s">So Eliphaz</span><span class="H8489 s"> the Temanite</span><span class="H1085 s"> and Bildad</span><span class="H7747 s"> the Shuhite</span><span class="H6691 s"> <i>and</i> Zophar</span><span class="H5284 s"> the Naamathite</span><span class="H3212 s"> went</span><span class="H6213 s">, and did</span><span class="H3068 s"> according as the LORD</span><span class="H1696 s"> commanded</span><span class="H3068 s"> them: the LORD</span><span class="H5375 s"> also accepted</span><span class="H6440 s"> Job</span><span class="H347 s"> †</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (Job: Heb. the face of Job)</span></div>
<div id="v220.42.10"><span class="H3068 s">And the LORD</span><span class="H7725 s"> turned</span><span class="H7622 s"> the captivity</span><span class="H7622 s"> †</span><span class="H347 s"> of Job</span><span class="H6419 s">, when he prayed</span><span class="H7453 s"> for his friends</span><span class="H3068 s">: also the LORD</span><span class="H3254 s"> gave</span><span class="H347 s"> Job</span><span class="H4932 s"> twice as much</span> as he had before. <span class="notes">Notes by the 1611 King James Bible Translators: (gave…: Heb. added all that had been to Job unto the double)</span></div>
<div id="v220.42.11"><span class="H935 s">Then came</span><span class="H251 s"> there unto him all his brethren</span><span class="H269 s">, and all his sisters</span><span class="H3045 s">, and all they that had been of his acquaintance</span><span class="H6440 s"> before</span><span class="H398 s">, and did eat</span><span class="H3899 s"> bread</span><span class="H1004 s"> with him in his house</span><span class="H5110 s">: and they bemoaned</span><span class="H5162 s"> him, and comforted</span><span class="H7451 s"> him over all the evil</span><span class="H3068 s"> that the LORD</span><span class="H935 s"> had brought</span><span class="H376 s"> upon him: every man</span><span class="H5414 s"> also gave</span><span class="H259 s"> him a</span><span class="H7192 s"> piece of money</span><span class="H376 s">, and every one</span><span class="H5141 s"> an earring</span><span class="H2091 s"> of gold</span>.</div>
<div id="v220.42.12"><span class="H3068 s">So the LORD</span><span class="H1288 s"> blessed</span><span class="H319 s"> the latter end</span><span class="H347 s"> of Job</span><span class="H7225 s"> more than his beginning</span><span class="H702 s">: for he had fourteen</span><span class="H6240 s"> †</span><span class="H505 s"> thousand</span><span class="H6629 s"> sheep</span><span class="H8337 s">, and six</span><span class="H505 s"> thousand</span><span class="H1581 s"> camels</span><span class="H505 s">, and a thousand</span><span class="H6776 s"> yoke</span><span class="H1241 s"> of oxen</span><span class="H505 s">, and a thousand</span><span class="H860 s"> she asses</span>.</div>
<div id="v220.42.13"><span class="H7658 s">He had also seven</span><span class="H1121 s"> sons</span><span class="H7969 s"> and three</span><span class="H1323 s"> daughters</span>.</div>
<div id="v220.42.14"><span class="H7121 s">And he called</span><span class="H8034 s"> the name</span><span class="H259 s"> of the first</span><span class="H3224 s">, Jemima</span><span class="H8034 s">; and the name</span><span class="H8145 s"> of the second</span><span class="H7103 s">, Kezia</span><span class="H8034 s">; and the name</span><span class="H7992 s"> of the third</span><span class="H7163 s">, Kerenhappuch</span>.</div>
<div id="v220.42.15"><span class="H776 s">And in all the land</span><span class="H802 s"> were no women</span><span class="H4672 s"> found</span><span class="H3303 s"> <i>so</i> fair</span><span class="H1323 s"> as the daughters</span><span class="H347 s"> of Job</span><span class="H1 s">: and their father</span><span class="H5414 s"> gave</span><span class="H5159 s"> them inheritance</span><span class="H8432 s"> among</span><span class="H251 s"> their brethren</span>.</div>
<div id="v220.42.16"><span class="H310 s">After</span><span class="H2421 s"> this lived</span><span class="H347 s"> Job</span><span class="H3967 s"> an hundred</span><span class="H705 s"> and forty</span><span class="H8141 s"> years</span><span class="H7200 s">, and saw</span><span class="H1121 s"> his sons</span><span class="H1121 s">, and his sons' H1121 sons</span><span class="H702 s">, <i>even</i> four</span><span class="H1755 s"> generations</span>.</div>
<div id="v220.42.17"><span class="H347 s">So Job</span><span class="H4191 s"> died</span><span class="H2205 s">, <i>being</i> old</span><span class="H7649 s"> and full</span><span class="H3117 s"> of days</span>.</div></div>
