<div class="c290_33">
<div id="v290.33.1"><span class="H1945 s">Woe</span><span class="H7703 s"> to thee that spoilest</span><span class="H7703 s">, and thou <i>wast</i> not spoiled</span><span class="H898 s">; and dealest treacherously</span><span class="H898 s">, and they dealt not treacherously</span><span class="H8552 s"> with thee! when thou shalt cease</span><span class="H7703 s"> to spoil</span><span class="H7703 s">, thou shalt be spoiled</span><span class="H5239 s">; <i>and</i> when thou shalt make an end</span><span class="H898 s"> to deal treacherously</span><span class="H898 s">, they shall deal treacherously</span> with thee.</div>
<div id="v290.33.2"><span class="H3068 s">O LORD</span><span class="H2603 s">, be gracious</span><span class="H6960 s"> unto us; we have waited</span><span class="H2220 s"> for thee: be thou their arm</span><span class="H1242 s"> every morning</span><span class="H3444 s">, our salvation</span><span class="H6256 s"> also in the time</span><span class="H6869 s"> of trouble</span>.</div>
<div id="v290.33.3"><span class="H6963 s">At the noise</span><span class="H1995 s"> of the tumult</span><span class="H5971 s"> the people</span><span class="H5074 s"> fled</span><span class="H7427 s">; at the lifting up</span><span class="H1471 s"> of thyself the nations</span><span class="H5310 s"> were scattered</span>.</div>
<div id="v290.33.4"><span class="H7998 s">And your spoil</span><span class="H622 s"> shall be gathered</span><span class="H625 s"> <i>like</i> the gathering</span><span class="H2625 s"> of the caterpiller</span><span class="H4944 s">: as the running to and fro</span><span class="H1357 s"> of locusts</span><span class="H8264 s"> shall he run</span> upon them.</div>
<div id="v290.33.5"><span class="H3068 s">The LORD</span><span class="H7682 s"> is exalted</span><span class="H7931 s">; for he dwelleth</span><span class="H4791 s"> on high</span><span class="H4390 s">: he hath filled</span><span class="H6726 s"> Zion</span><span class="H4941 s"> with judgment</span><span class="H6666 s"> and righteousness</span>.</div>
<div id="v290.33.6"><span class="H2451 s">And wisdom</span><span class="H1847 s"> and knowledge</span><span class="H530 s"> shall be the stability</span><span class="H6256 s"> of thy times</span><span class="H2633 s">, <i>and</i> strength</span><span class="H3444 s"> of salvation</span><span class="H3374 s">: the fear</span><span class="H3068 s"> of the LORD</span><span class="H214 s"> <i>is</i> his treasure</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (salvation: Heb. salvations)</span></div>
<div id="v290.33.7"><span class="H691 s">Behold, their valiant ones</span><span class="H6817 s"> shall cry</span><span class="H2351 s"> without</span><span class="H4397 s">: the ambassadors</span><span class="H7965 s"> of peace</span><span class="H1058 s"> shall weep</span><span class="H4751 s"> bitterly</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (valiant…: or, messengers)</span></div>
<div id="v290.33.8"><span class="H4546 s">The highways</span><span class="H8074 s"> lie waste</span><span class="H5674 s">, the wayfaring man</span><span class="H734 s"> †</span><span class="H7673 s"> ceaseth</span><span class="H6565 s">: he hath broken</span><span class="H1285 s"> the covenant</span><span class="H3988 s">, he hath despised</span><span class="H5892 s"> the cities</span><span class="H2803 s">, he regardeth</span><span class="H582 s"> no man</span>.</div>
<div id="v290.33.9"><span class="H776 s">The earth</span><span class="H56 s"> mourneth</span><span class="H535 s"> <i>and</i> languisheth</span><span class="H3844 s">: Lebanon</span><span class="H2659 s"> is ashamed</span><span class="H7060 s"> <i>and</i> hewn down</span><span class="H8289 s">: Sharon</span><span class="H6160 s"> is like a wilderness</span><span class="H1316 s">; and Bashan</span><span class="H3760 s"> and Carmel</span><span class="H5287 s"> shake off</span> <i>their fruits</i>. <span class="notes">Notes by the 1611 King James Bible Translators: (hewn…: or, withered away)</span></div>
<div id="v290.33.10"><span class="H6965 s">Now will I rise</span><span class="H559 s">, saith</span><span class="H3068 s"> the LORD</span><span class="H7426 s">; now will I be exalted</span><span class="H5375 s">; now will I lift up</span> myself.</div>
<div id="v290.33.11"><span class="H2029 s">Ye shall conceive</span><span class="H2842 s"> chaff</span><span class="H3205 s">, ye shall bring forth</span><span class="H7179 s"> stubble</span><span class="H7307 s">: your breath</span><span class="H784 s">, <i>as</i> fire</span><span class="H398 s">, shall devour</span> you.</div>
<div id="v290.33.12"><span class="H5971 s">And the people</span><span class="H4955 s"> shall be <i>as</i> the burnings</span><span class="H7875 s"> of lime</span><span class="H6975 s">: <i>as</i> thorns</span><span class="H3683 s"> cut up</span><span class="H3341 s"> shall they be burned</span><span class="H784 s"> in the fire</span>.</div>
<div id="v290.33.13"><span class="H8085 s">Hear</span><span class="H7350 s">, ye <i>that are</i> far off</span><span class="H6213 s">, what I have done</span><span class="H7138 s">; and, ye <i>that are</i> near</span><span class="H3045 s">, acknowledge</span><span class="H1369 s"> my might</span>.</div>
<div id="v290.33.14"><span class="H2400 s">The sinners</span><span class="H6726 s"> in Zion</span><span class="H6342 s"> are afraid</span><span class="H7461 s">; fearfulness</span><span class="H270 s"> hath surprised</span><span class="H2611 s"> the hypocrites</span><span class="H1481 s">. Who among us shall dwell</span><span class="H398 s"> with the devouring</span><span class="H784 s"> fire</span><span class="H1481 s">? who among us shall dwell</span><span class="H5769 s"> with everlasting</span><span class="H4168 s"> burnings</span>?</div>
<div id="v290.33.15"><span class="H1980 s">He that walketh</span><span class="H6666 s"> righteously</span><span class="H1696 s">, and speaketh</span><span class="H4339 s"> uprightly</span><span class="H3988 s">; he that despiseth</span><span class="H1215 s"> the gain</span><span class="H4642 s"> of oppressions</span><span class="H5287 s">, that shaketh</span><span class="H3709 s"> his hands</span><span class="H8551 s"> from holding</span><span class="H7810 s"> of bribes</span><span class="H331 s">, that stoppeth</span><span class="H241 s"> his ears</span><span class="H8085 s"> from hearing</span><span class="H1818 s"> of blood</span><span class="H6105 s">, and shutteth</span><span class="H5869 s"> his eyes</span><span class="H7200 s"> from seeing</span><span class="H7451 s"> evil</span>; <span class="notes">Notes by the 1611 King James Bible Translators: (righteously: Heb. in righteousnesses) (uprightly: Heb. uprightnesses) (oppressions: or, deceits) (blood: Heb. bloods)</span></div>
<div id="v290.33.16"><span class="H7931 s">He shall dwell</span><span class="H4791 s"> on high</span><span class="H4869 s">: his place of defence</span><span class="H4679 s"> <i>shall be</i> the munitions</span><span class="H5553 s"> of rocks</span><span class="H3899 s">: bread</span><span class="H5414 s"> shall be given</span><span class="H4325 s"> him; his waters</span><span class="H539 s"> <i>shall be</i> sure</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (high: Heb. heights, or, high places)</span></div>
<div id="v290.33.17"><span class="H5869 s">Thine eyes</span><span class="H2372 s"> shall see</span><span class="H4428 s"> the king</span><span class="H3308 s"> in his beauty</span><span class="H7200 s">: they shall behold</span><span class="H776 s"> the land</span><span class="H4801 s"> that is very far off</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (that…: Heb. of far distances)</span></div>
<div id="v290.33.18"><span class="H3820 s">Thine heart</span><span class="H1897 s"> shall meditate</span><span class="H367 s"> terror</span><span class="H5608 s">. Where <i>is</i> the scribe</span><span class="H8254 s">? where <i>is</i> the receiver</span><span class="H5608 s">? where <i>is</i> he that counted</span><span class="H4026 s"> the towers</span>? <span class="notes">Notes by the 1611 King James Bible Translators: (receiver: Heb. weigher?)</span></div>
<div id="v290.33.19"><span class="H7200 s">Thou shalt not see</span><span class="H3267 s"> a fierce</span><span class="H5971 s"> people</span><span class="H5971 s">, a people</span><span class="H6012 s"> of a deeper</span><span class="H8193 s"> speech</span><span class="H8085 s"> than thou canst perceive</span><span class="H3932 s">; of a stammering</span><span class="H3956 s"> tongue</span><span class="H998 s">, <i>that thou canst</i> not understand</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (stammering: or, ridiculous)</span></div>
<div id="v290.33.20"><span class="H2372 s">Look</span><span class="H6726 s"> upon Zion</span><span class="H7151 s">, the city</span><span class="H4150 s"> of our solemnities</span><span class="H5869 s">: thine eyes</span><span class="H7200 s"> shall see</span><span class="H3389 s"> Jerusalem</span><span class="H7600 s"> a quiet</span><span class="H5116 s"> habitation</span><span class="H168 s">, a tabernacle</span><span class="H6813 s"> <i>that</i> shall not be taken down</span><span class="H3489 s">; not one of the stakes</span><span class="H5331 s"> thereof shall ever</span><span class="H5265 s"> be removed</span><span class="H2256 s">, neither shall any of the cords</span><span class="H5423 s"> thereof be broken</span>.</div>
<div id="v290.33.21"><span class="H117 s">But there the glorious</span><span class="H3068 s"> LORD</span><span class="H4725 s"> <i>will be</i> unto us a place</span><span class="H7342 s"> of broad</span><span class="H3027 s"> †</span><span class="H5104 s"> rivers</span><span class="H2975 s"> <i>and</i> streams</span><span class="H3212 s">; wherein shall go</span><span class="H1077 s"> no</span><span class="H590 s"> galley</span><span class="H7885 s"> with oars</span><span class="H117 s">, neither shall gallant</span><span class="H6716 s"> ship</span><span class="H5674 s"> pass</span> thereby. <span class="notes">Notes by the 1611 King James Bible Translators: (of…: Heb. broad of spaces, or, hands)</span></div>
<div id="v290.33.22"><span class="H3068 s">For the LORD</span><span class="H8199 s"> <i>is</i> our judge</span><span class="H3068 s">, the LORD</span><span class="H2710 s"> <i>is</i> our lawgiver</span><span class="H3068 s">, the LORD</span><span class="H4428 s"> <i>is</i> our king</span><span class="H3467 s">; he will save</span> us. <span class="notes">Notes by the 1611 King James Bible Translators: (lawgiver: Heb. statutemaker)</span></div>
<div id="v290.33.23"><span class="H2256 s">Thy tacklings</span><span class="H5203 s"> are loosed</span><span class="H3653 s">; they could not well</span><span class="H2388 s"> strengthen</span><span class="H8650 s"> their mast</span><span class="H6566 s">, they could not spread</span><span class="H5251 s"> the sail</span><span class="H5706 s">: then is the prey</span><span class="H4766 s"> of a great</span><span class="H7998 s"> spoil</span><span class="H2505 s"> divided</span><span class="H6455 s">; the lame</span><span class="H962 s"> take</span><span class="H957 s"> the prey</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (Thy…: or, They have forsaken thy tacklings)</span></div>
<div id="v290.33.24"><span class="H7934 s">And the inhabitant</span><span class="H559 s"> shall not say</span><span class="H2470 s">, I am sick</span><span class="H5971 s">: the people</span><span class="H3427 s"> that dwell</span><span class="H5375 s"> therein <i>shall be</i> forgiven</span><span class="H5771 s"> <i>their</i> iniquity</span>.</div></div>
