<div class="c20_40">
<div id="v20.40.1"><span class="H3068 s">And the LORD</span><span class="H1696 s"> spake</span><span class="H4872 s"> unto Moses</span><span class="H559 s">, saying</span>,</div>
<div id="v20.40.2"><span class="H7223 s">On the first</span><span class="H3117 s"> day</span><span class="H259 s"> of the first</span><span class="H2320 s"> month</span><span class="H6965 s"> shalt thou set up</span><span class="H4908 s"> the tabernacle</span><span class="H168 s"> of the tent</span><span class="H4150 s"> of the congregation</span>.</div>
<div id="v20.40.3"><span class="H7760 s">And thou shalt put</span><span class="H8033 s"> therein</span><span class="H727 s"> the ark</span><span class="H5715 s"> of the testimony</span><span class="H5526 s">, and cover</span><span class="H727 s"> the ark</span><span class="H6532 s"> with the vail</span>.</div>
<div id="v20.40.4"><span class="H935 s">And thou shalt bring</span><span class="H7979 s"> in the table</span><span class="H6186 s">, and set in order</span><span class="H6187 s"> the things that are to be set in order</span><span class="H935 s"> upon it; and thou shalt bring</span><span class="H4501 s"> in the candlestick</span><span class="H5927 s">, and light</span><span class="H5216 s"> the lamps</span> thereof. <span class="notes">Notes by the 1611 King James Bible Translators: (the things…: Heb. the order thereof)</span></div>
<div id="v20.40.5"><span class="H5414 s">And thou shalt set</span><span class="H4196 s"> the altar</span><span class="H2091 s"> of gold</span><span class="H7004 s"> for the incense</span><span class="H6440 s"> before</span><span class="H727 s"> the ark</span><span class="H5715 s"> of the testimony</span><span class="H7760 s">, and put</span><span class="H4539 s"> the hanging</span><span class="H6607 s"> of the door</span><span class="H4908 s"> to the tabernacle</span>.</div>
<div id="v20.40.6"><span class="H5414 s">And thou shalt set</span><span class="H4196 s"> the altar</span><span class="H5930 s"> of the burnt offering</span><span class="H6440 s"> before</span><span class="H6607 s"> the door</span><span class="H4908 s"> of the tabernacle</span><span class="H168 s"> of the tent</span><span class="H4150 s"> of the congregation</span>.</div>
<div id="v20.40.7"><span class="H5414 s">And thou shalt set</span><span class="H3595 s"> the laver</span><span class="H168 s"> between the tent</span><span class="H4150 s"> of the congregation</span><span class="H4196 s"> and the altar</span><span class="H5414 s">, and shalt put</span><span class="H4325 s"> water</span> therein.</div>
<div id="v20.40.8"><span class="H7760 s">And thou shalt set up</span><span class="H2691 s"> the court</span><span class="H5439 s"> round about</span><span class="H5414 s">, and hang up</span><span class="H4539 s"> the hanging</span><span class="H2691 s"> at the court</span><span class="H8179 s"> gate</span>.</div>
<div id="v20.40.9"><span class="H3947 s">And thou shalt take</span><span class="H4888 s"> the anointing</span><span class="H8081 s"> oil</span><span class="H4886 s">, and anoint</span><span class="H4908 s"> the tabernacle</span><span class="H6942 s">, and all that <i>is</i> therein, and shalt hallow</span><span class="H3627 s"> it, and all the vessels</span><span class="H6944 s"> thereof: and it shall be holy</span>.</div>
<div id="v20.40.10"><span class="H4886 s">And thou shalt anoint</span><span class="H4196 s"> the altar</span><span class="H5930 s"> of the burnt offering</span><span class="H3627 s">, and all his vessels</span><span class="H6942 s">, and sanctify</span><span class="H4196 s"> the altar</span><span class="H4196 s">: and it shall be an altar</span><span class="H6944 s"> most</span><span class="H6944 s"> holy</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (most holy: Heb. holiness of holinesses)</span></div>
<div id="v20.40.11"><span class="H4886 s">And thou shalt anoint</span><span class="H3595 s"> the laver</span><span class="H3653 s"> and his foot</span><span class="H6942 s">, and sanctify</span> it.</div>
<div id="v20.40.12"><span class="H7126 s">And thou shalt bring</span><span class="H175 s"> Aaron</span><span class="H1121 s"> and his sons</span><span class="H6607 s"> unto the door</span><span class="H168 s"> of the tabernacle</span><span class="H4150 s"> of the congregation</span><span class="H7364 s">, and wash</span><span class="H4325 s"> them with water</span>.</div>
<div id="v20.40.13"><span class="H3847 s">And thou shalt put</span><span class="H175 s"> upon Aaron</span><span class="H6944 s"> the holy</span><span class="H899 s"> garments</span><span class="H4886 s">, and anoint</span><span class="H6942 s"> him, and sanctify</span><span class="H3547 s"> him; that he may minister unto me in the priest's office</span>.</div>
<div id="v20.40.14"><span class="H7126 s">And thou shalt bring</span><span class="H1121 s"> his sons</span><span class="H3847 s">, and clothe</span><span class="H3801 s"> them with coats</span>:</div>
<div id="v20.40.15"><span class="H4886 s">And thou shalt anoint</span><span class="H4886 s"> them, as thou didst anoint</span><span class="H1 s"> their father</span><span class="H3547 s">, that they may minister unto me in the priest's office</span><span class="H4888 s">: for their anointing</span><span class="H5769 s"> shall surely be an everlasting</span><span class="H3550 s"> priesthood</span><span class="H1755 s"> throughout their generations</span>.</div>
<div id="v20.40.16"><span class="H6213 s">Thus did</span><span class="H4872 s"> Moses</span><span class="H3068 s">: according to all that the LORD</span><span class="H6680 s"> commanded</span><span class="H6213 s"> him, so did</span> he.</div>
<div id="v20.40.17"><span class="H7223 s">And it came to pass in the first</span><span class="H2320 s"> month</span><span class="H8145 s"> in the second</span><span class="H8141 s"> year</span><span class="H259 s">, on the first</span><span class="H2320 s"> <i>day</i> of the month</span><span class="H4908 s">, <i>that</i> the tabernacle</span><span class="H6965 s"> was reared up</span>.</div>
<div id="v20.40.18"><span class="H4872 s">And Moses</span><span class="H6965 s"> reared up</span><span class="H4908 s"> the tabernacle</span><span class="H5414 s">, and fastened</span><span class="H134 s"> his sockets</span><span class="H7760 s">, and set up</span><span class="H7175 s"> the boards</span><span class="H5414 s"> thereof, and put</span><span class="H1280 s"> in the bars</span><span class="H6965 s"> thereof, and reared up</span><span class="H5982 s"> his pillars</span>.</div>
<div id="v20.40.19"><span class="H6566 s">And he spread abroad</span><span class="H168 s"> the tent</span><span class="H4908 s"> over the tabernacle</span><span class="H7760 s">, and put</span><span class="H4372 s"> the covering</span><span class="H168 s"> of the tent</span><span class="H4605 s"> above</span><span class="H3068 s"> upon it; as the LORD</span><span class="H6680 s"> commanded</span><span class="H4872 s"> Moses</span>.</div>
<div id="v20.40.20"><span class="H3947 s">And he took</span><span class="H5414 s"> and put</span><span class="H5715 s"> the testimony</span><span class="H727 s"> into the ark</span><span class="H7760 s">, and set</span><span class="H905 s"> the staves</span><span class="H727 s"> on the ark</span><span class="H5414 s">, and put</span><span class="H3727 s"> the mercy seat</span><span class="H4605 s"> above</span><span class="H727 s"> upon the ark</span>:</div>
<div id="v20.40.21"><span class="H935 s">And he brought</span><span class="H727 s"> the ark</span><span class="H4908 s"> into the tabernacle</span><span class="H7760 s">, and set up</span><span class="H6532 s"> the vail</span><span class="H4539 s"> of the covering</span><span class="H5526 s">, and covered</span><span class="H727 s"> the ark</span><span class="H5715 s"> of the testimony</span><span class="H3068 s">; as the LORD</span><span class="H6680 s"> commanded</span><span class="H4872 s"> Moses</span>.</div>
<div id="v20.40.22"><span class="H5414 s">And he put</span><span class="H7979 s"> the table</span><span class="H168 s"> in the tent</span><span class="H4150 s"> of the congregation</span><span class="H3409 s">, upon the side</span><span class="H4908 s"> of the tabernacle</span><span class="H6828 s"> northward</span><span class="H2351 s">, without</span><span class="H6532 s"> the vail</span>.</div>
<div id="v20.40.23"><span class="H6187 s">And he set</span><span class="H3899 s"> the bread</span><span class="H6186 s"> in order</span><span class="H6440 s"> upon it before</span><span class="H3068 s"> the LORD</span><span class="H3068 s">; as the LORD</span><span class="H6680 s"> had commanded</span><span class="H4872 s"> Moses</span>.</div>
<div id="v20.40.24"><span class="H7760 s">And he put</span><span class="H4501 s"> the candlestick</span><span class="H168 s"> in the tent</span><span class="H4150 s"> of the congregation</span><span class="H5227 s">, over against</span><span class="H7979 s"> the table</span><span class="H3409 s">, on the side</span><span class="H4908 s"> of the tabernacle</span><span class="H5045 s"> southward</span>.</div>
<div id="v20.40.25"><span class="H5927 s">And he lighted</span><span class="H5216 s"> the lamps</span><span class="H6440 s"> before</span><span class="H3068 s"> the LORD</span><span class="H3068 s">; as the LORD</span><span class="H6680 s"> commanded</span><span class="H4872 s"> Moses</span>.</div>
<div id="v20.40.26"><span class="H7760 s">And he put</span><span class="H2091 s"> the golden</span><span class="H4196 s"> altar</span><span class="H168 s"> in the tent</span><span class="H4150 s"> of the congregation</span><span class="H6440 s"> before</span><span class="H6532 s"> the vail</span>:</div>
<div id="v20.40.27"><span class="H6999 s">And he burnt</span><span class="H5561 s"> sweet</span><span class="H7004 s"> incense</span><span class="H3068 s"> thereon; as the LORD</span><span class="H6680 s"> commanded</span><span class="H4872 s"> Moses</span>.</div>
<div id="v20.40.28"><span class="H7760 s">And he set up</span><span class="H4539 s"> the hanging</span><span class="H6607 s"> <i>at</i> the door</span><span class="H4908 s"> of the tabernacle</span>.</div>
<div id="v20.40.29"><span class="H7760 s">And he put</span><span class="H4196 s"> the altar</span><span class="H5930 s"> of burnt offering</span><span class="H6607 s"> <i>by</i> the door</span><span class="H4908 s"> of the tabernacle</span><span class="H168 s"> of the tent</span><span class="H4150 s"> of the congregation</span><span class="H5927 s">, and offered</span><span class="H5930 s"> upon it the burnt offering</span><span class="H4503 s"> and the meat offering</span><span class="H3068 s">; as the LORD</span><span class="H6680 s"> commanded</span><span class="H4872 s"> Moses</span>.</div>
<div id="v20.40.30"><span class="H7760 s">And he set</span><span class="H3595 s"> the laver</span><span class="H168 s"> between the tent</span><span class="H4150 s"> of the congregation</span><span class="H4196 s"> and the altar</span><span class="H5414 s">, and put</span><span class="H4325 s"> water</span><span class="H7364 s"> there, to wash</span> <i>withal</i>.</div>
<div id="v20.40.31"><span class="H4872 s">And Moses</span><span class="H175 s"> and Aaron</span><span class="H1121 s"> and his sons</span><span class="H7364 s"> washed</span><span class="H3027 s"> their hands</span><span class="H7272 s"> and their feet</span> thereat:</div>
<div id="v20.40.32"><span class="H935 s">When they went</span><span class="H168 s"> into the tent</span><span class="H4150 s"> of the congregation</span><span class="H7126 s">, and when they came near</span><span class="H4196 s"> unto the altar</span><span class="H7364 s">, they washed</span><span class="H3068 s">; as the LORD</span><span class="H6680 s"> commanded</span><span class="H4872 s"> Moses</span>.</div>
<div id="v20.40.33"><span class="H6965 s">And he reared up</span><span class="H2691 s"> the court</span><span class="H5439 s"> round about</span><span class="H4908 s"> the tabernacle</span><span class="H4196 s"> and the altar</span><span class="H5414 s">, and set up</span><span class="H4539 s"> the hanging</span><span class="H2691 s"> of the court</span><span class="H8179 s"> gate</span><span class="H4872 s">. So Moses</span><span class="H3615 s"> finished</span><span class="H4399 s"> the work</span>.</div>
<div id="v20.40.34"><span class="H6051 s">Then a cloud</span><span class="H3680 s"> covered</span><span class="H168 s"> the tent</span><span class="H4150 s"> of the congregation</span><span class="H3519 s">, and the glory</span><span class="H3068 s"> of the LORD</span><span class="H4390 s"> filled</span><span class="H4908 s"> the tabernacle</span>.</div>
<div id="v20.40.35"><span class="H4872 s">And Moses</span><span class="H3201 s"> was not able</span><span class="H935 s"> to enter</span><span class="H168 s"> into the tent</span><span class="H4150 s"> of the congregation</span><span class="H6051 s">, because the cloud</span><span class="H7931 s"> abode</span><span class="H3519 s"> thereon, and the glory</span><span class="H3068 s"> of the LORD</span><span class="H4390 s"> filled</span><span class="H4908 s"> the tabernacle</span>.</div>
<div id="v20.40.36"><span class="H6051 s">And when the cloud</span><span class="H5927 s"> was taken up</span><span class="H5921 s"> from</span><span class="H4908 s"> over the tabernacle</span><span class="H1121 s">, the children</span><span class="H3478 s"> of Israel</span><span class="H5265 s"> went onward</span><span class="H4550 s"> in all their journeys</span>: <span class="notes">Notes by the 1611 King James Bible Translators: (went onward: Heb. journeyed)</span></div>
<div id="v20.40.37"><span class="H6051 s">But if the cloud</span><span class="H5927 s"> were not taken up</span><span class="H5265 s">, then they journeyed</span><span class="H3117 s"> not till the day</span><span class="H5927 s"> that it was taken up</span>.</div>
<div id="v20.40.38"><span class="H6051 s">For the cloud</span><span class="H3068 s"> of the LORD</span><span class="H4908 s"> <i>was</i> upon the tabernacle</span><span class="H3119 s"> by day</span><span class="H784 s">, and fire</span><span class="H3915 s"> was on it by night</span><span class="H5869 s">, in the sight</span><span class="H1004 s"> of all the house</span><span class="H3478 s"> of Israel</span><span class="H4550 s">, throughout all their journeys</span>.</div></div>
