<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c330_1"> 
<div id="v330.1.1"><span class="H7970 s">Now it came to pass in the thirtieth</span><span class="H8141 s"> year</span><span class="H7243 s">, in the fourth</span><span class="H2568 s"> <i>month</i>, in the fifth</span><span class="H2320 s"> <i>day</i> of the month</span><span class="H8432 s">, as I <i>was</i> among</span><span class="H1473 s"> the captives</span><span class="H5104 s"> by the river</span><span class="H3529 s"> of Chebar</span><span class="H8064 s">, <i>that</i> the heavens</span><span class="H6605 s"> were opened</span><span class="H7200 s">, and I saw</span><span class="H4759 s"> visions</span><span class="H430 s"> of God</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (captives: Heb. captivity)</span></div> 
<div id="v330.1.2"><span class="H2568 s">In the fifth</span><span class="H2320 s"> <i>day</i> of the month</span><span class="H2549 s">, which <i>was</i> the fifth</span><span class="H8141 s"> year</span><span class="H4428 s"> of king</span><span class="H3112 s"> Jehoiachin's</span><span class="H1546 s"> captivity</span>,</div> 
<div id="v330.1.3"><span class="H1697 s">The word</span><span class="H3068 s"> of the LORD</span><span class="H3168 s"> came expressly unto Ezekiel</span><span class="H3548 s"> the priest</span><span class="H1121 s">, the son</span><span class="H941 s"> of Buzi</span><span class="H776 s">, in the land</span><span class="H3778 s"> of the Chaldeans</span><span class="H5104 s"> by the river</span><span class="H3529 s"> Chebar</span><span class="H3027 s">; and the hand</span><span class="H3068 s"> of the LORD</span> was there upon him. <span class="notes">Notes by the 1611 King James Bible Translators: (Ezekiel: Heb. Jehezkel)</span></div> 
<div id="v330.1.4"><span class="H7200 s">And I looked</span><span class="H7307 s">, and, behold, a whirlwind</span><span class="H5591 s"> †</span><span class="H935 s"> came</span><span class="H6828 s"> out of the north</span><span class="H1419 s">, a great</span><span class="H6051 s"> cloud</span><span class="H784 s">, and a fire</span><span class="H3947 s"> infolding</span><span class="H5051 s"> itself, and a brightness</span><span class="H5439 s"> <i>was</i> about</span><span class="H8432 s"> it, and out of the midst</span><span class="H5869 s"> thereof as the colour</span><span class="H2830 s"> of amber</span><span class="H8432 s">, out of the midst</span><span class="H784 s"> of the fire</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (infolding…: Heb. catching itself)</span></div> 
<div id="v330.1.5"><span class="H8432 s">Also out of the midst</span><span class="H1823 s"> thereof <i>came</i> the likeness</span><span class="H702 s"> of four</span><span class="H2416 s"> living creatures</span><span class="H4758 s">. And this <i>was</i> their appearance</span><span class="H2007 s">; they</span><span class="H1823 s"> had the likeness</span><span class="H120 s"> of a man</span>.</div> 
<div id="v330.1.6"><span class="H259 s">And every one</span><span class="H702 s"> had four</span><span class="H6440 s"> faces</span><span class="H259 s">, and every one</span><span class="H702 s"> had four</span><span class="H3671 s"> wings</span>.</div> 
<div id="v330.1.7"><span class="H7272 s">And their feet</span><span class="H3477 s"> <i>were</i> straight</span><span class="H7272 s"> feet</span><span class="H3709 s">; and the sole</span><span class="H7272 s"> of their feet</span><span class="H3709 s"> <i>was</i> like the sole</span><span class="H5695 s"> of a calf's</span><span class="H7272 s"> foot</span><span class="H5340 s">: and they sparkled</span><span class="H5869 s"> like the colour</span><span class="H7044 s"> of burnished</span><span class="H5178 s"> brass</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (straight…: Heb. a straight foot)</span></div> 
<div id="v330.1.8"><span class="H3027 s">And <i>they had</i> the hands</span><span class="H120 s"> of a man</span><span class="H3671 s"> under their wings</span><span class="H702 s"> on their four</span><span class="H7253 s"> sides</span><span class="H702 s">; and they four</span><span class="H6440 s"> had their faces</span><span class="H3671 s"> and their wings</span>.</div> 
<div id="v330.1.9"><span class="H3671 s">Their wings</span><span class="H2266 s"> <i>were</i> joined</span><span class="H802 s"> one</span><span class="H269 s"> to another</span><span class="H5437 s">; they turned</span><span class="H3212 s"> not when they went</span><span class="H3212 s">; they went</span><span class="H376 s"> every one</span><span class="H5676 s"> straight</span><span class="H6440 s"> forward</span>.</div> 
<div id="v330.1.10"><span class="H1823 s">As for the likeness</span><span class="H6440 s"> of their faces</span><span class="H702 s">, they four</span><span class="H6440 s"> had the face</span><span class="H120 s"> of a man</span><span class="H6440 s">, and the face</span><span class="H738 s"> of a lion</span><span class="H3225 s">, on the right side</span><span class="H702 s">: and they four</span><span class="H6440 s"> had the face</span><span class="H7794 s"> of an ox</span><span class="H8040 s"> on the left side</span><span class="H702 s">; they four</span><span class="H6440 s"> also had the face</span><span class="H5404 s"> of an eagle</span>.</div> 
<div id="v330.1.11"><span class="H6440 s">Thus <i>were</i> their faces</span><span class="H3671 s">: and their wings</span><span class="H6504 s"> <i>were</i> stretched</span><span class="H4605 s"> upward</span><span class="H8147 s">; two</span><span class="H376 s"> <i>wings</i> of every one</span><span class="H2266 s"> <i>were</i> joined</span><span class="H376 s"> one</span><span class="H376 s"> to another</span><span class="H8147 s">, and two</span><span class="H3680 s"> covered</span><span class="H1472 s"> their bodies</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (stretched…: or, divided above)</span></div> 
<div id="v330.1.12"><span class="H3212 s">And they went</span><span class="H376 s"> every one</span><span class="H5676 s"> straight</span><span class="H6440 s"> forward</span><span class="H7307 s">: whither the spirit</span><span class="H3212 s"> was to go</span><span class="H3212 s">, they went</span><span class="H5437 s">; <i>and</i> they turned</span><span class="H3212 s"> not when they went</span>.</div> 
<div id="v330.1.13"><span class="H1823 s">As for the likeness</span><span class="H2416 s"> of the living creatures</span><span class="H4758 s">, their appearance</span><span class="H1197 s"> <i>was</i> like burning</span><span class="H1513 s"> coals</span><span class="H784 s"> of fire</span><span class="H4758 s">, <i>and</i> like the appearance</span><span class="H3940 s"> of lamps</span><span class="H1980 s">: it went up and down</span><span class="H2416 s"> among the living creatures</span><span class="H784 s">; and the fire</span><span class="H5051 s"> was bright</span><span class="H784 s">, and out of the fire</span><span class="H3318 s"> went forth</span><span class="H1300 s"> lightning</span>.</div> 
<div id="v330.1.14"><span class="H2416 s">And the living creatures</span><span class="H7519 s"> ran</span><span class="H7725 s"> and returned</span><span class="H4758 s"> as the appearance</span><span class="H965 s"> of a flash of lightning</span>.</div> 
<div id="v330.1.15"><span class="H7200 s">Now as I beheld</span><span class="H2416 s"> the living creatures</span><span class="H259 s">, behold one</span><span class="H212 s"> wheel</span><span class="H776 s"> upon the earth</span><span class="H681 s"> by</span><span class="H2416 s"> the living creatures</span><span class="H702 s">, with his four</span><span class="H6440 s"> faces</span>.</div> 
<div id="v330.1.16"><span class="H4758 s">The appearance</span><span class="H212 s"> of the wheels</span><span class="H4639 s"> and their work</span><span class="H5869 s"> <i>was</i> like unto the colour</span><span class="H8658 s"> of a beryl</span><span class="H702 s">: and they four</span><span class="H259 s"> had one</span><span class="H1823 s"> likeness</span><span class="H4758 s">: and their appearance</span><span class="H4639 s"> and their work</span><span class="H212 s"> <i>was</i> as it were a wheel</span><span class="H8432 s"> in the middle</span><span class="H212 s"> of a wheel</span>.</div> 
<div id="v330.1.17"><span class="H3212 s">When they went</span><span class="H3212 s">, they went</span><span class="H702 s"> upon their four</span><span class="H7253 s"> sides</span><span class="H5437 s">: <i>and</i> they turned</span><span class="H3212 s"> not when they went</span>.</div> 
<div id="v330.1.18"><span class="H1354 s">As for their rings</span><span class="H1363 s">, they were so high</span><span class="H3374 s"> that they were dreadful</span><span class="H1354 s">; and their rings</span><span class="H4392 s"> <i>were</i> full</span><span class="H5869 s"> of eyes</span><span class="H5439 s"> round about</span><span class="H702 s"> them four</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (and their rings: or, and their strakes)</span></div> 
<div id="v330.1.19"><span class="H2416 s">And when the living creatures</span><span class="H3212 s"> went</span><span class="H212 s">, the wheels</span><span class="H3212 s"> went</span><span class="H681 s"> by them</span><span class="H2416 s">: and when the living creatures</span><span class="H5375 s"> were lifted up</span><span class="H776 s"> from the earth</span><span class="H212 s">, the wheels</span><span class="H5375 s"> were lifted up</span>.</div> 
<div id="v330.1.20"><span class="H7307 s">Whithersoever the spirit</span><span class="H3212 s"> was to go</span><span class="H3212 s">, they went</span><span class="H7307 s">, thither <i>was their</i> spirit</span><span class="H3212 s"> to go</span><span class="H212 s">; and the wheels</span><span class="H5375 s"> were lifted up</span><span class="H5980 s"> over against</span><span class="H7307 s"> them: for the spirit</span><span class="H2416 s"> of the living creature</span><span class="H212 s"> <i>was</i> in the wheels</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (of…: or, of life)</span></div> 
<div id="v330.1.21"><span class="H3212 s">When those went</span><span class="H3212 s">, <i>these</i> went</span><span class="H5975 s">; and when those stood</span><span class="H5975 s">, <i>these</i> stood</span><span class="H5375 s">; and when those were lifted up</span><span class="H776 s"> from the earth</span><span class="H212 s">, the wheels</span><span class="H5375 s"> were lifted up</span><span class="H5980 s"> over against</span><span class="H7307 s"> them: for the spirit</span><span class="H2416 s"> of the living creature</span><span class="H212 s"> <i>was</i> in the wheels</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (of…: or, of life)</span></div> 
<div id="v330.1.22"><span class="H1823 s">And the likeness</span><span class="H7549 s"> of the firmament</span><span class="H7218 s"> upon the heads</span><span class="H2416 s"> of the living creature</span><span class="H5869 s"> <i>was</i> as the colour</span><span class="H3372 s"> of the terrible</span><span class="H7140 s"> crystal</span><span class="H5186 s">, stretched forth</span><span class="H7218 s"> over their heads</span><span class="H4605 s"> above</span>.</div> 
<div id="v330.1.23"><span class="H7549 s">And under the firmament</span><span class="H3671 s"> <i>were</i> their wings</span><span class="H3477 s"> straight</span><span class="H802 s">, the one</span><span class="H269 s"> toward the other</span><span class="H376 s">: every one</span><span class="H8147 s"> had two</span><span class="H3680 s">, which covered</span><span class="H2007 s"> on this side</span><span class="H376 s">, and every one</span><span class="H8147 s"> had two</span><span class="H3680 s">, which covered</span><span class="H2007 s"> on that side</span><span class="H1472 s">, their bodies</span>.</div> 
<div id="v330.1.24"><span class="H3212 s">And when they went</span><span class="H8085 s">, I heard</span><span class="H6963 s"> the noise</span><span class="H3671 s"> of their wings</span><span class="H6963 s">, like the noise</span><span class="H7227 s"> of great</span><span class="H4325 s"> waters</span><span class="H6963 s">, as the voice</span><span class="H7706 s"> of the Almighty</span><span class="H6963 s">, the voice</span><span class="H1999 s"> of speech</span><span class="H6963 s">, as the noise</span><span class="H4264 s"> of an host</span><span class="H5975 s">: when they stood</span><span class="H7503 s">, they let down</span><span class="H3671 s"> their wings</span>.</div> 
<div id="v330.1.25"><span class="H6963 s">And there was a voice</span><span class="H7549 s"> from the firmament</span><span class="H7218 s"> that <i>was</i> over their heads</span><span class="H5975 s">, when they stood</span><span class="H7503 s">, <i>and</i> had let down</span><span class="H3671 s"> their wings</span>.</div> 
<div id="v330.1.26"><span class="H4605 s">And above</span><span class="H7549 s"> the firmament</span><span class="H7218 s"> that <i>was</i> over their heads</span><span class="H1823 s"> <i>was</i> the likeness</span><span class="H3678 s"> of a throne</span><span class="H4758 s">, as the appearance</span><span class="H5601 s"> of a sapphire</span><span class="H68 s"> stone</span><span class="H1823 s">: and upon the likeness</span><span class="H3678 s"> of the throne</span><span class="H1823 s"> <i>was</i> the likeness</span><span class="H4758 s"> as the appearance</span><span class="H120 s"> of a man</span><span class="H4605 s"> above</span> upon it.</div> 
<div id="v330.1.27"><span class="H7200 s">And I saw</span><span class="H5869 s"> as the colour</span><span class="H2830 s"> of amber</span><span class="H4758 s">, as the appearance</span><span class="H784 s"> of fire</span><span class="H5439 s"> round about</span><span class="H1004 s"> within</span><span class="H4758 s"> it, from the appearance</span><span class="H4975 s"> of his loins</span><span class="H4605 s"> even upward</span><span class="H4758 s">, and from the appearance</span><span class="H4975 s"> of his loins</span><span class="H4295 s"> even downward</span><span class="H7200 s">, I saw</span><span class="H4758 s"> as it were the appearance</span><span class="H784 s"> of fire</span><span class="H5051 s">, and it had brightness</span><span class="H5439 s"> round about</span>.</div> 
<div id="v330.1.28"><span class="H4758 s">As the appearance</span><span class="H7198 s"> of the bow</span><span class="H6051 s"> that is in the cloud</span><span class="H3117 s"> in the day</span><span class="H1653 s"> of rain</span><span class="H4758 s">, so <i>was</i> the appearance</span><span class="H5051 s"> of the brightness</span><span class="H5439 s"> round about</span><span class="H4758 s">. This <i>was</i> the appearance</span><span class="H1823 s"> of the likeness</span><span class="H3519 s"> of the glory</span><span class="H3068 s"> of the LORD</span><span class="H7200 s">. And when I saw</span><span class="H5307 s"> <i>it</i>, I fell</span><span class="H6440 s"> upon my face</span><span class="H8085 s">, and I heard</span><span class="H6963 s"> a voice</span><span class="H1696 s"> of one that spake</span>.</div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
