<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c330_5"> 
<div id="v330.5.1"><span class="H1121 s">And thou, son</span><span class="H120 s"> of man</span><span class="H3947 s">, take</span><span class="H2299 s"> thee a sharp</span><span class="H2719 s"> knife</span><span class="H3947 s">, take</span><span class="H1532 s"> thee a barber's</span><span class="H8593 s"> razor</span><span class="H5674 s">, and cause <i>it</i> to pass</span><span class="H7218 s"> upon thine head</span><span class="H2206 s"> and upon thy beard</span><span class="H3947 s">: then take</span><span class="H3976 s"> thee balances</span><span class="H4948 s"> to weigh</span><span class="H2505 s">, and divide</span> the <i>hair</i>.</div> 
<div id="v330.5.2"><span class="H1197 s">Thou shalt burn</span><span class="H217 s"> with fire</span><span class="H7992 s"> a third part</span><span class="H8432 s"> in the midst</span><span class="H5892 s"> of the city</span><span class="H3117 s">, when the days</span><span class="H4692 s"> of the siege</span><span class="H4390 s"> are fulfilled</span><span class="H3947 s">: and thou shalt take</span><span class="H7992 s"> a third part</span><span class="H5221 s">, <i>and</i> smite</span><span class="H5439 s"> about</span><span class="H2719 s"> it with a knife</span><span class="H7992 s">: and a third part</span><span class="H2219 s"> thou shalt scatter</span><span class="H7307 s"> in the wind</span><span class="H7324 s">; and I will draw out</span><span class="H2719 s"> a sword</span><span class="H310 s"> after</span> them.</div> 
<div id="v330.5.3"><span class="H3947 s">Thou shalt also take</span><span class="H4592 s"> thereof a few</span><span class="H4557 s"> in number</span><span class="H6696 s">, and bind</span><span class="H3671 s"> them in thy skirts</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (skirts: Heb. wings)</span></div> 
<div id="v330.5.4"><span class="H3947 s">Then take of them again</span><span class="H7993 s">, and cast</span><span class="H8432 s"> them into the midst</span><span class="H784 s"> of the fire</span><span class="H8313 s">, and burn</span><span class="H784 s"> them in the fire</span><span class="H784 s">; <i>for</i> thereof shall a fire</span><span class="H3318 s"> come forth</span><span class="H1004 s"> into all the house</span><span class="H3478 s"> of Israel</span>.</div> 
<div id="v330.5.5"><span class="H559 s">Thus saith</span><span class="H136 s"> the Lord</span><span class="H3069 s"> GOD</span><span class="H3389 s">; This <i>is</i> Jerusalem</span><span class="H7760 s">: I have set</span><span class="H8432 s"> it in the midst</span><span class="H1471 s"> of the nations</span><span class="H776 s"> and countries</span><span class="H5439 s"> <i>that are</i> round about</span> her.</div> 
<div id="v330.5.6"><span class="H4784 s">And she hath changed</span><span class="H4941 s"> my judgments</span><span class="H7564 s"> into wickedness</span><span class="H1471 s"> more than the nations</span><span class="H2708 s">, and my statutes</span><span class="H776 s"> more than the countries</span><span class="H5439 s"> that <i>are</i> round about</span><span class="H3988 s"> her: for they have refused</span><span class="H4941 s"> my judgments</span><span class="H2708 s"> and my statutes</span><span class="H1980 s">, they have not walked</span> in them.</div> 
<div id="v330.5.7"><span class="H559 s">Therefore thus saith</span><span class="H136 s"> the Lord</span><span class="H3069 s"> GOD</span><span class="H1995 s">; Because ye multiplied</span><span class="H1471 s"> more than the nations</span><span class="H5439 s"> that <i>are</i> round about</span><span class="H1980 s"> you, <i>and</i> have not walked</span><span class="H2708 s"> in my statutes</span><span class="H6213 s">, neither have kept</span><span class="H4941 s"> my judgments</span><span class="H6213 s">, neither have done</span><span class="H4941 s"> according to the judgments</span><span class="H1471 s"> of the nations</span><span class="H5439 s"> that <i>are</i> round about</span> you;</div> 
<div id="v330.5.8"><span class="H559 s">Therefore thus saith</span><span class="H136 s"> the Lord</span><span class="H3069 s"> GOD</span><span class="H6213 s">; Behold, I, even I, <i>am</i> against thee, and will execute</span><span class="H4941 s"> judgments</span><span class="H8432 s"> in the midst</span><span class="H5869 s"> of thee in the sight</span><span class="H1471 s"> of the nations</span>.</div> 
<div id="v330.5.9"><span class="H6213 s">And I will do</span><span class="H6213 s"> in thee that which I have not done</span><span class="H6213 s">, and whereunto I will not do</span><span class="H3282 s"> any more the like, because</span><span class="H8441 s"> of all thine abominations</span>.</div> 
<div id="v330.5.10"><span class="H1 s">Therefore the fathers</span><span class="H398 s"> shall eat</span><span class="H1121 s"> the sons</span><span class="H8432 s"> in the midst</span><span class="H1121 s"> of thee, and the sons</span><span class="H398 s"> shall eat</span><span class="H1 s"> their fathers</span><span class="H6213 s">; and I will execute</span><span class="H8201 s"> judgments</span><span class="H7611 s"> in thee, and the whole remnant</span><span class="H2219 s"> of thee will I scatter</span><span class="H7307 s"> into all the winds</span>.</div> 
<div id="v330.5.11"><span class="H2416 s">Wherefore, <i>as</i> I live</span><span class="H5002 s">, saith</span><span class="H136 s"> the Lord</span><span class="H3069 s"> GOD</span><span class="H2930 s">; Surely, because thou hast defiled</span><span class="H4720 s"> my sanctuary</span><span class="H8251 s"> with all thy detestable things</span><span class="H8441 s">, and with all thine abominations</span><span class="H1639 s">, therefore will I also diminish</span><span class="H5869 s"> <i>thee</i>; neither shall mine eye</span><span class="H2347 s"> spare</span><span class="H2550 s">, neither will I have any pity</span>.</div> 
<div id="v330.5.12"><span class="H7992 s">A third part</span><span class="H4191 s"> of thee shall die</span><span class="H1698 s"> with the pestilence</span><span class="H7458 s">, and with famine</span><span class="H3615 s"> shall they be consumed</span><span class="H8432 s"> in the midst</span><span class="H7992 s"> of thee: and a third part</span><span class="H5307 s"> shall fall</span><span class="H2719 s"> by the sword</span><span class="H5439 s"> round about</span><span class="H2219 s"> thee; and I will scatter</span><span class="H7992 s"> a third part</span><span class="H7307 s"> into all the winds</span><span class="H7324 s">, and I will draw out</span><span class="H2719 s"> a sword</span><span class="H310 s"> after</span> them.</div> 
<div id="v330.5.13"><span class="H639 s">Thus shall mine anger</span><span class="H3615 s"> be accomplished</span><span class="H2534 s">, and I will cause my fury</span><span class="H5117 s"> to rest</span><span class="H5162 s"> upon them, and I will be comforted</span><span class="H3045 s">: and they shall know</span><span class="H3068 s"> that I the LORD</span><span class="H1696 s"> have spoken</span><span class="H7068 s"> <i>it</i> in my zeal</span><span class="H3615 s">, when I have accomplished</span><span class="H2534 s"> my fury</span> in them.</div> 
<div id="v330.5.14"><span class="H5414 s">Moreover I will make</span><span class="H2723 s"> thee waste</span><span class="H2781 s">, and a reproach</span><span class="H1471 s"> among the nations</span><span class="H5439 s"> that <i>are</i> round about</span><span class="H5869 s"> thee, in the sight</span><span class="H5674 s"> of all that pass by</span>.</div> 
<div id="v330.5.15"><span class="H2781 s">So it shall be a reproach</span><span class="H1422 s"> and a taunt</span><span class="H4148 s">, an instruction</span><span class="H4923 s"> and an astonishment</span><span class="H1471 s"> unto the nations</span><span class="H5439 s"> that <i>are</i> round about</span><span class="H6213 s"> thee, when I shall execute</span><span class="H8201 s"> judgments</span><span class="H639 s"> in thee in anger</span><span class="H2534 s"> and in fury</span><span class="H2534 s"> and in furious</span><span class="H8433 s"> rebukes</span><span class="H3068 s">. I the LORD</span><span class="H1696 s"> have spoken</span> <i>it</i>.</div> 
<div id="v330.5.16"><span class="H7971 s">When I shall send</span><span class="H7451 s"> upon them the evil</span><span class="H2671 s"> arrows</span><span class="H7458 s"> of famine</span><span class="H4889 s">, which shall be for <i>their</i> destruction</span><span class="H7971 s">, <i>and</i> which I will send</span><span class="H7843 s"> to destroy</span><span class="H3254 s"> you: and I will increase</span><span class="H7458 s"> the famine</span><span class="H7665 s"> upon you, and will break</span><span class="H4294 s"> your staff</span><span class="H3899 s"> of bread</span>:</div> 
<div id="v330.5.17"><span class="H7971 s">So will I send</span><span class="H7458 s"> upon you famine</span><span class="H7451 s"> and evil</span><span class="H2416 s"> beasts</span><span class="H7921 s">, and they shall bereave</span><span class="H1698 s"> thee; and pestilence</span><span class="H1818 s"> and blood</span><span class="H5674 s"> shall pass through</span><span class="H935 s"> thee; and I will bring</span><span class="H2719 s"> the sword</span><span class="H3068 s"> upon thee. I the LORD</span><span class="H1696 s"> have spoken</span> <i>it</i>.</div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
