<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c230_62"> 
<div id="v230.62.1"><span class="H5329 s">To the chief Musician</span><span class="H3038 s">, to Jeduthun</span><span class="H4210 s">, A Psalm</span><span class="H1732 s"> of David</span><span class="H5315 s">. Truly my soul</span><span class="H1747 s"> waiteth</span><span class="H430 s"> upon God</span><span class="H3444 s">: from him <i>cometh</i> my salvation</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (Truly: or, Only) (waiteth: Heb. is silent)</span></div> 
<div id="v230.62.2"><span class="H6697 s">He only <i>is</i> my rock</span><span class="H3444 s"> and my salvation</span><span class="H4869 s">; <i>he is</i> my defence</span><span class="H7227 s">; I shall not be greatly</span><span class="H4131 s"> moved</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (defence: Heb. high place)</span></div> 
<div id="v230.62.3"><span class="H2050 s">How long will ye imagine mischief</span><span class="H376 s"> against a man</span><span class="H7523 s">? ye shall be slain</span><span class="H5186 s"> all of you: as a bowing</span><span class="H7023 s"> wall</span><span class="H1760 s"> <i>shall ye be, and as</i> a tottering</span><span class="H1447 s"> fence</span>.</div> 
<div id="v230.62.4"><span class="H3289 s">They only consult</span><span class="H5080 s"> to cast <i>him</i> down</span><span class="H7613 s"> from his excellency</span><span class="H7521 s">: they delight</span><span class="H3577 s"> in lies</span><span class="H1288 s">: they bless</span><span class="H6310 s"> with their mouth</span><span class="H7043 s">, but they curse</span><span class="H7130 s"> inwardly</span><span class="H5542 s">. Selah</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (inwardly: Heb. in their inward parts)</span></div> 
<div id="v230.62.5"><span class="H5315 s">My soul</span><span class="H1826 s">, wait</span><span class="H430 s"> thou only upon God</span><span class="H8615 s">; for my expectation</span> <i>is</i> from him.</div> 
<div id="v230.62.6"><span class="H6697 s">He only <i>is</i> my rock</span><span class="H3444 s"> and my salvation</span><span class="H4869 s">: <i>he is</i> my defence</span><span class="H4131 s">; I shall not be moved</span>.</div> 
<div id="v230.62.7"><span class="H430 s">In God</span><span class="H3468 s"> <i>is</i> my salvation</span><span class="H3519 s"> and my glory</span><span class="H6697 s">: the rock</span><span class="H5797 s"> of my strength</span><span class="H4268 s">, <i>and</i> my refuge</span><span class="H430 s">, <i>is</i> in God</span>.</div> 
<div id="v230.62.8"><span class="H982 s">Trust</span><span class="H6256 s"> in him at all times</span><span class="H5971 s">; <i>ye</i> people</span><span class="H8210 s">, pour out</span><span class="H3824 s"> your heart</span><span class="H6440 s"> before</span><span class="H430 s"> him: God</span><span class="H4268 s"> <i>is</i> a refuge</span><span class="H5542 s"> for us. Selah</span>.</div> 
<div id="v230.62.9"><span class="H120 s">Surely men</span><span class="H1121 s"> †</span><span class="H1892 s"> of low degree <i>are</i> vanity</span><span class="H376 s">, <i>and</i> men</span><span class="H3577 s"> of high degree <i>are</i> a lie</span><span class="H5927 s">: to be laid</span><span class="H3976 s"> in the balance</span><span class="H3162 s">, they <i>are</i> altogether</span><span class="H1892 s"> <i>lighter</i> than vanity</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (altogether: or, alike)</span></div> 
<div id="v230.62.10"><span class="H982 s">Trust</span><span class="H6233 s"> not in oppression</span><span class="H1891 s">, and become not vain</span><span class="H1498 s"> in robbery</span><span class="H2428 s">: if riches</span><span class="H5107 s"> increase</span><span class="H7896 s">, set</span><span class="H3820 s"> not your heart</span> <i>upon them</i>.</div> 
<div id="v230.62.11"><span class="H430 s">God</span><span class="H1696 s"> hath spoken</span><span class="H259 s"> once</span><span class="H8147 s">; twice</span><span class="H8085 s"> have I heard</span><span class="H2098 s"> this</span><span class="H5797 s">; that power</span><span class="H430 s"> <i>belongeth</i> unto God</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (power: or, strength)</span></div> 
<div id="v230.62.12"><span class="H136 s">Also unto thee, O Lord</span><span class="H2617 s">, <i>belongeth</i> mercy</span><span class="H7999 s">: for thou renderest</span><span class="H376 s"> to every man</span><span class="H4639 s"> according to his work</span>.</div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
