<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c290_17"> 
<div id="v290.17.1"><span class="H4853 s">The burden</span><span class="H1834 s"> of Damascus</span><span class="H1834 s">. Behold, Damascus</span><span class="H5493 s"> is taken away</span><span class="H5892 s"> from <i>being</i> a city</span><span class="H4654 s">, and it shall be a ruinous</span><span class="H4596 s"> heap</span>.</div> 
<div id="v290.17.2"><span class="H5892 s">The cities</span><span class="H6177 s"> of Aroer</span><span class="H5800 s"> <i>are</i> forsaken</span><span class="H5739 s">: they shall be for flocks</span><span class="H7257 s">, which shall lie down</span><span class="H2729 s">, and none shall make <i>them</i> afraid</span>.</div> 
<div id="v290.17.3"><span class="H4013 s">The fortress</span><span class="H7673 s"> also shall cease</span><span class="H669 s"> from Ephraim</span><span class="H4467 s">, and the kingdom</span><span class="H1834 s"> from Damascus</span><span class="H7605 s">, and the remnant</span><span class="H758 s"> of Syria</span><span class="H3519 s">: they shall be as the glory</span><span class="H1121 s"> of the children</span><span class="H3478 s"> of Israel</span><span class="H5002 s">, saith</span><span class="H3068 s"> the LORD</span><span class="H6635 s"> of hosts</span>.</div> 
<div id="v290.17.4"><span class="H3117 s">And in that day</span><span class="H3519 s"> it shall come to pass, <i>that</i> the glory</span><span class="H3290 s"> of Jacob</span><span class="H1809 s"> shall be made thin</span><span class="H4924 s">, and the fatness</span><span class="H1320 s"> of his flesh</span><span class="H7329 s"> shall wax lean</span>.</div> 
<div id="v290.17.5"><span class="H7105 s">And it shall be as when the harvestman</span><span class="H622 s"> gathereth</span><span class="H7054 s"> the corn</span><span class="H7114 s">, and reapeth</span><span class="H7641 s"> the ears</span><span class="H2220 s"> with his arm</span><span class="H3950 s">; and it shall be as he that gathereth</span><span class="H7641 s"> ears</span><span class="H6010 s"> in the valley</span><span class="H7497 s"> of Rephaim</span>.</div> 
<div id="v290.17.6"><span class="H5955 s">Yet gleaning grapes</span><span class="H7604 s"> shall be left</span><span class="H5363 s"> in it, as the shaking</span><span class="H2132 s"> of an olive tree</span><span class="H8147 s">, two</span><span class="H7969 s"> <i>or</i> three</span><span class="H1620 s"> berries</span><span class="H7218 s"> in the top</span><span class="H534 s"> of the uppermost bough</span><span class="H702 s">, four</span><span class="H2568 s"> <i>or</i> five</span><span class="H6509 s"> in the outmost fruitful</span><span class="H5585 s"> branches</span><span class="H5002 s"> thereof, saith</span><span class="H3068 s"> the LORD</span><span class="H430 s"> God</span><span class="H3478 s"> of Israel</span>.</div> 
<div id="v290.17.7"><span class="H3117 s">At that day</span><span class="H120 s"> shall a man</span><span class="H8159 s"> look</span><span class="H6213 s"> to his Maker</span><span class="H5869 s">, and his eyes</span><span class="H7200 s"> shall have respect</span><span class="H6918 s"> to the Holy</span><span class="H3478 s"> One of Israel</span>.</div> 
<div id="v290.17.8"><span class="H8159 s">And he shall not look</span><span class="H4196 s"> to the altars</span><span class="H4639 s">, the work</span><span class="H3027 s"> of his hands</span><span class="H7200 s">, neither shall respect</span><span class="H676 s"> <i>that</i> which his fingers</span><span class="H6213 s"> have made</span><span class="H842 s">, either the groves</span><span class="H2553 s">, or the images</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (images: or, sun images)</span></div> 
<div id="v290.17.9"><span class="H3117 s">In that day</span><span class="H4581 s"> shall his strong</span><span class="H5892 s"> cities</span><span class="H5800 s"> be as a forsaken</span><span class="H2793 s"> bough</span><span class="H534 s">, and an uppermost branch</span><span class="H5800 s">, which they left</span><span class="H6440 s"> because</span><span class="H1121 s"> of the children</span><span class="H3478 s"> of Israel</span><span class="H8077 s">: and there shall be desolation</span>.</div> 
<div id="v290.17.10"><span class="H7911 s">Because thou hast forgotten</span><span class="H430 s"> the God</span><span class="H3468 s"> of thy salvation</span><span class="H2142 s">, and hast not been mindful</span><span class="H6697 s"> of the rock</span><span class="H4581 s"> of thy strength</span><span class="H5193 s">, therefore shalt thou plant</span><span class="H5282 s"> pleasant</span><span class="H5194 s"> plants</span><span class="H2232 s">, and shalt set</span><span class="H2114 s"> it with strange</span><span class="H2156 s"> slips</span>:</div> 
<div id="v290.17.11"><span class="H3117 s">In the day</span><span class="H5194 s"> shalt thou make thy plant</span><span class="H7735 s"> to grow</span><span class="H1242 s">, and in the morning</span><span class="H2233 s"> shalt thou make thy seed</span><span class="H6524 s"> to flourish</span><span class="H7105 s">: <i>but</i> the harvest</span><span class="H5067 s"> <i>shall be</i> a heap</span><span class="H3117 s"> in the day</span><span class="H2470 s"> of grief</span><span class="H605 s"> and of desperate</span><span class="H3511 s"> sorrow</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (a heap…: or, removed in the day of inheritance, and there shall be deadly sorrow)</span></div> 
<div id="v290.17.12"><span class="H1945 s">Woe</span><span class="H1995 s"> to the multitude</span><span class="H7227 s"> of many</span><span class="H5971 s"> people</span><span class="H1993 s">, <i>which</i> make a noise</span><span class="H1993 s"> like the noise</span><span class="H3220 s"> of the seas</span><span class="H7588 s">; and to the rushing</span><span class="H3816 s"> of nations</span><span class="H7582 s">, <i>that</i> make a rushing like the rushing</span><span class="H3524 s"> of mighty</span><span class="H4325 s"> waters</span>! <span class="notes">Notes by the 1611 King James Bible Translators: (multitude: or, noise) (mighty: or, many)</span></div> 
<div id="v290.17.13"><span class="H3816 s">The nations</span><span class="H7582 s"> shall rush</span><span class="H7588 s"> like the rushing</span><span class="H7227 s"> of many</span><span class="H4325 s"> waters</span><span class="H1605 s">: but <i>God</i> shall rebuke</span><span class="H5127 s"> them, and they shall flee</span><span class="H4801 s"> far off</span><span class="H7291 s">, and shall be chased</span><span class="H4671 s"> as the chaff</span><span class="H2022 s"> of the mountains</span><span class="H6440 s"> before</span><span class="H7307 s"> the wind</span><span class="H1534 s">, and like a rolling thing</span><span class="H6440 s"> before</span><span class="H5492 s"> the whirlwind</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (a rolling…: or, thistledown)</span></div> 
<div id="v290.17.14"><span class="H6256 s">And behold at eveningtide</span><span class="H6153 s"> †</span><span class="H1091 s"> trouble</span><span class="H1242 s">; <i>and</i> before the morning</span><span class="H2506 s"> he <i>is</i> not. This <i>is</i> the portion</span><span class="H8154 s"> of them that spoil</span><span class="H1486 s"> us, and the lot</span><span class="H962 s"> of them that rob</span> us.</div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
