<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c40_20"> 
<div id="v40.20.1"><span class="H935 s">Then came</span><span class="H1121 s"> the children</span><span class="H3478 s"> of Israel</span><span class="H5712 s">, <i>even</i> the whole congregation</span><span class="H4057 s">, into the desert</span><span class="H6790 s"> of Zin</span><span class="H7223 s"> in the first</span><span class="H2320 s"> month</span><span class="H5971 s">: and the people</span><span class="H3427 s"> abode</span><span class="H6946 s"> in Kadesh</span><span class="H4813 s">; and Miriam</span><span class="H4191 s"> died</span><span class="H6912 s"> there, and was buried</span> there.</div> 
<div id="v40.20.2"><span class="H4325 s">And there was no water</span><span class="H5712 s"> for the congregation</span><span class="H6950 s">: and they gathered</span><span class="H4872 s"> themselves together against Moses</span><span class="H175 s"> and against Aaron</span>.</div> 
<div id="v40.20.3"><span class="H5971 s">And the people</span><span class="H7378 s"> chode</span><span class="H4872 s"> with Moses</span><span class="H559 s">, and spake</span><span class="H559 s">, saying</span><span class="H3863 s">, Would God that</span><span class="H1478 s"> we had died</span><span class="H251 s"> when our brethren</span><span class="H1478 s"> died</span><span class="H6440 s"> before</span><span class="H3068 s"> the LORD</span>!</div> 
<div id="v40.20.4"><span class="H935 s">And why have ye brought up</span><span class="H6951 s"> the congregation</span><span class="H3068 s"> of the LORD</span><span class="H4057 s"> into this wilderness</span><span class="H1165 s">, that we and our cattle</span><span class="H4191 s"> should die</span> there?</div> 
<div id="v40.20.5"><span class="H5927 s">And wherefore have ye made us to come up</span><span class="H4714 s"> out of Egypt</span><span class="H935 s">, to bring</span><span class="H7451 s"> us in unto this evil</span><span class="H4725 s"> place</span><span class="H4725 s">? it <i>is</i> no place</span><span class="H2233 s"> of seed</span><span class="H8384 s">, or of figs</span><span class="H1612 s">, or of vines</span><span class="H7416 s">, or of pomegranates</span><span class="H4325 s">; neither <i>is</i> there any water</span><span class="H8354 s"> to drink</span>.</div> 
<div id="v40.20.6"><span class="H4872 s">And Moses</span><span class="H175 s"> and Aaron</span><span class="H935 s"> went</span><span class="H6440 s"> from the presence</span><span class="H6951 s"> of the assembly</span><span class="H6607 s"> unto the door</span><span class="H168 s"> of the tabernacle</span><span class="H4150 s"> of the congregation</span><span class="H5307 s">, and they fell</span><span class="H6440 s"> upon their faces</span><span class="H3519 s">: and the glory</span><span class="H3068 s"> of the LORD</span><span class="H7200 s"> appeared</span> unto them.</div> 
<div id="v40.20.7"><span class="H3068 s">And the LORD</span><span class="H1696 s"> spake</span><span class="H4872 s"> unto Moses</span><span class="H559 s">, saying</span>,</div> 
<div id="v40.20.8"><span class="H3947 s">Take</span><span class="H4294 s"> the rod</span><span class="H6950 s">, and gather</span><span class="H5712 s"> thou the assembly</span><span class="H175 s"> together, thou, and Aaron</span><span class="H251 s"> thy brother</span><span class="H1696 s">, and speak</span><span class="H5553 s"> ye unto the rock</span><span class="H5869 s"> before their eyes</span><span class="H5414 s">; and it shall give forth</span><span class="H4325 s"> his water</span><span class="H3318 s">, and thou shalt bring forth</span><span class="H4325 s"> to them water</span><span class="H5553 s"> out of the rock</span><span class="H8248 s">: so thou shalt give</span><span class="H5712 s"> the congregation</span><span class="H1165 s"> and their beasts</span><span class="H8248 s"> drink</span>.</div> 
<div id="v40.20.9"><span class="H4872 s">And Moses</span><span class="H3947 s"> took</span><span class="H4294 s"> the rod</span><span class="H6440 s"> from before</span><span class="H3068 s"> the LORD</span><span class="H6680 s">, as he commanded</span> him.</div> 
<div id="v40.20.10"><span class="H4872 s">And Moses</span><span class="H175 s"> and Aaron</span><span class="H6950 s"> gathered</span><span class="H6951 s"> the congregation</span><span class="H6440 s"> together before</span><span class="H5553 s"> the rock</span><span class="H559 s">, and he said</span><span class="H8085 s"> unto them, Hear</span><span class="H4784 s"> now, ye rebels</span><span class="H3318 s">; must we fetch</span><span class="H4325 s"> you water</span><span class="H5553 s"> out of this rock</span>?</div> 
<div id="v40.20.11"><span class="H4872 s">And Moses</span><span class="H7311 s"> lifted up</span><span class="H3027 s"> his hand</span><span class="H4294 s">, and with his rod</span><span class="H5221 s"> he smote</span><span class="H5553 s"> the rock</span><span class="H6471 s"> twice</span><span class="H4325 s">: and the water</span><span class="H3318 s"> came out</span><span class="H7227 s"> abundantly</span><span class="H5712 s">, and the congregation</span><span class="H8354 s"> drank</span><span class="H1165 s">, and their beasts</span> <i>also</i>.</div> 
<div id="v40.20.12"><span class="H3068 s">And the LORD</span><span class="H559 s"> spake</span><span class="H4872 s"> unto Moses</span><span class="H175 s"> and Aaron</span><span class="H539 s">, Because ye believed</span><span class="H6942 s"> me not, to sanctify</span><span class="H5869 s"> me in the eyes</span><span class="H1121 s"> of the children</span><span class="H3478 s"> of Israel</span><span class="H935 s">, therefore ye shall not bring</span><span class="H6951 s"> this congregation</span><span class="H776 s"> into the land</span><span class="H5414 s"> which I have given</span> them.</div> 
<div id="v40.20.13"><span class="H1992 s">This <i>is</i></span><span class="H4325 s"> the water</span><span class="H4809 s"> of Meribah</span><span class="H1121 s">; because the children</span><span class="H3478 s"> of Israel</span><span class="H7378 s"> strove</span><span class="H3068 s"> with the LORD</span><span class="H6942 s">, and he was sanctified</span> in them. <span class="notes">Notes by the 1611 King James Bible Translators: (Meribah: that is, Strife)</span></div> 
<div id="v40.20.14"><span class="H4872 s">And Moses</span><span class="H7971 s"> sent</span><span class="H4397 s"> messengers</span><span class="H6946 s"> from Kadesh</span><span class="H4428 s"> unto the king</span><span class="H123 s"> of Edom</span><span class="H559 s">, Thus saith</span><span class="H251 s"> thy brother</span><span class="H3478 s"> Israel</span><span class="H3045 s">, Thou knowest</span><span class="H8513 s"> all the travail</span><span class="H4672 s"> that hath befallen</span> us: <span class="notes">Notes by the 1611 King James Bible Translators: (befallen…: Heb. found us)</span></div> 
<div id="v40.20.15"><span class="H1 s">How our fathers</span><span class="H3381 s"> went down</span><span class="H4714 s"> into Egypt</span><span class="H3427 s">, and we have dwelt</span><span class="H4714 s"> in Egypt</span><span class="H7227 s"> a long</span><span class="H3117 s"> time</span><span class="H4714 s">; and the Egyptians</span><span class="H7489 s"> vexed</span><span class="H1 s"> us, and our fathers</span>:</div> 
<div id="v40.20.16"><span class="H6817 s">And when we cried</span><span class="H3068 s"> unto the LORD</span><span class="H8085 s">, he heard</span><span class="H6963 s"> our voice</span><span class="H7971 s">, and sent</span><span class="H4397 s"> an angel</span><span class="H3318 s">, and hath brought us forth</span><span class="H4714 s"> out of Egypt</span><span class="H6946 s">: and, behold, we <i>are</i> in Kadesh</span><span class="H5892 s">, a city</span><span class="H7097 s"> in the uttermost</span><span class="H1366 s"> of thy border</span>:</div> 
<div id="v40.20.17"><span class="H5674 s">Let us pass</span><span class="H776 s">, I pray thee, through thy country</span><span class="H5674 s">: we will not pass</span><span class="H7704 s"> through the fields</span><span class="H3754 s">, or through the vineyards</span><span class="H8354 s">, neither will we drink</span><span class="H4325 s"> <i>of</i> the water</span><span class="H875 s"> of the wells</span><span class="H3212 s">: we will go</span><span class="H4428 s"> by the king's</span><span class="H1870 s"> <i>high</i> way</span><span class="H5186 s">, we will not turn</span><span class="H3225 s"> to the right hand</span><span class="H8040 s"> nor to the left</span><span class="H5674 s">, until we have passed</span><span class="H1366 s"> thy borders</span>.</div> 
<div id="v40.20.18"><span class="H123 s">And Edom</span><span class="H559 s"> said</span><span class="H5674 s"> unto him, Thou shalt not pass</span><span class="H3318 s"> by me, lest I come out</span><span class="H7125 s"> against</span><span class="H2719 s"> thee with the sword</span>.</div> 
<div id="v40.20.19"><span class="H1121 s">And the children</span><span class="H3478 s"> of Israel</span><span class="H559 s"> said</span><span class="H5927 s"> unto him, We will go</span><span class="H4546 s"> by the high way</span><span class="H4735 s">: and if I and my cattle</span><span class="H8354 s"> drink</span><span class="H4325 s"> of thy water</span><span class="H5414 s">, then I will pay</span><span class="H4377 s"> †</span><span class="H1697 s"> for it: I will only, without <i>doing</i> any thing</span><span class="H5674 s"> <i>else</i>, go through</span><span class="H7272 s"> on my feet</span>.</div> 
<div id="v40.20.20"><span class="H559 s">And he said</span><span class="H5674 s">, Thou shalt not go through</span><span class="H123 s">. And Edom</span><span class="H3318 s"> came out</span><span class="H7125 s"> against</span><span class="H3515 s"> him with much</span><span class="H5971 s"> people</span><span class="H2389 s">, and with a strong</span><span class="H3027 s"> hand</span>.</div> 
<div id="v40.20.21"><span class="H123 s">Thus Edom</span><span class="H3985 s"> refused</span><span class="H5414 s"> to give</span><span class="H3478 s"> Israel</span><span class="H5674 s"> passage</span><span class="H1366 s"> through his border</span><span class="H3478 s">: wherefore Israel</span><span class="H5186 s"> turned away</span> from him.</div> 
<div id="v40.20.22"><span class="H1121 s">And the children</span><span class="H3478 s"> of Israel</span><span class="H5712 s">, <i>even</i> the whole congregation</span><span class="H5265 s">, journeyed</span><span class="H6946 s"> from Kadesh</span><span class="H935 s">, and came</span><span class="H2022 s"> unto mount</span><span class="H2023 s"> Hor</span>.</div> 
<div id="v40.20.23"><span class="H3068 s">And the LORD</span><span class="H559 s"> spake</span><span class="H4872 s"> unto Moses</span><span class="H175 s"> and Aaron</span><span class="H2022 s"> in mount</span><span class="H2023 s"> Hor</span><span class="H1366 s">, by the coast</span><span class="H776 s"> of the land</span><span class="H123 s"> of Edom</span><span class="H559 s">, saying</span>,</div> 
<div id="v40.20.24"><span class="H175 s">Aaron</span><span class="H622 s"> shall be gathered</span><span class="H5971 s"> unto his people</span><span class="H935 s">: for he shall not enter</span><span class="H776 s"> into the land</span><span class="H5414 s"> which I have given</span><span class="H1121 s"> unto the children</span><span class="H3478 s"> of Israel</span><span class="H4784 s">, because ye rebelled against</span><span class="H6310 s"> my word</span><span class="H4325 s"> at the water</span><span class="H4809 s"> of Meribah</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (word: Heb. mouth)</span></div> 
<div id="v40.20.25"><span class="H3947 s">Take</span><span class="H175 s"> Aaron</span><span class="H499 s"> and Eleazar</span><span class="H1121 s"> his son</span><span class="H5927 s">, and bring them up</span><span class="H2022 s"> unto mount</span><span class="H2023 s"> Hor</span>:</div> 
<div id="v40.20.26"><span class="H6584 s">And strip</span><span class="H175 s"> Aaron</span><span class="H899 s"> of his garments</span><span class="H3847 s">, and put</span><span class="H499 s"> them upon Eleazar</span><span class="H1121 s"> his son</span><span class="H175 s">: and Aaron</span><span class="H622 s"> shall be gathered</span><span class="H4191 s"> <i>unto his people</i>, and shall die</span> there.</div> 
<div id="v40.20.27"><span class="H4872 s">And Moses</span><span class="H6213 s"> did</span><span class="H3068 s"> as the LORD</span><span class="H6680 s"> commanded</span><span class="H5927 s">: and they went up</span><span class="H2022 s"> into mount</span><span class="H2023 s"> Hor</span><span class="H5869 s"> in the sight</span><span class="H5712 s"> of all the congregation</span>.</div> 
<div id="v40.20.28"><span class="H4872 s">And Moses</span><span class="H6584 s"> stripped</span><span class="H175 s"> Aaron</span><span class="H899 s"> of his garments</span><span class="H3847 s">, and put</span><span class="H499 s"> them upon Eleazar</span><span class="H1121 s"> his son</span><span class="H175 s">; and Aaron</span><span class="H4191 s"> died</span><span class="H7218 s"> there in the top</span><span class="H2022 s"> of the mount</span><span class="H4872 s">: and Moses</span><span class="H499 s"> and Eleazar</span><span class="H3381 s"> came down</span><span class="H2022 s"> from the mount</span>.</div> 
<div id="v40.20.29"><span class="H5712 s">And when all the congregation</span><span class="H7200 s"> saw</span><span class="H175 s"> that Aaron</span><span class="H1478 s"> was dead</span><span class="H1058 s">, they mourned</span><span class="H175 s"> for Aaron</span><span class="H7970 s"> thirty</span><span class="H3117 s"> days</span><span class="H1004 s">, <i>even</i> all the house</span><span class="H3478 s"> of Israel</span>.</div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
