<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c300_17"> 
<div id="v300.17.1"><span class="H2403 s">The sin</span><span class="H3063 s"> of Judah</span><span class="H3789 s"> <i>is</i> written</span><span class="H5842 s"> with a pen</span><span class="H1270 s"> of iron</span><span class="H6856 s">, <i>and</i> with the point</span><span class="H8068 s"> of a diamond</span><span class="H2790 s">: <i>it is</i> graven</span><span class="H3871 s"> upon the table</span><span class="H3820 s"> of their heart</span><span class="H7161 s">, and upon the horns</span><span class="H4196 s"> of your altars</span>; <span class="notes">Notes by the 1611 King James Bible Translators: (point: Heb. nail)</span></div> 
<div id="v300.17.2"><span class="H1121 s">Whilst their children</span><span class="H2142 s"> remember</span><span class="H4196 s"> their altars</span><span class="H842 s"> and their groves</span><span class="H7488 s"> by the green</span><span class="H6086 s"> trees</span><span class="H1364 s"> upon the high</span><span class="H1389 s"> hills</span>.</div> 
<div id="v300.17.3"><span class="H2042 s">O my mountain</span><span class="H7704 s"> in the field</span><span class="H5414 s">, I will give</span><span class="H2428 s"> thy substance</span><span class="H214 s"> <i>and</i> all thy treasures</span><span class="H957 s"> to the spoil</span><span class="H1116 s">, <i>and</i> thy high places</span><span class="H2403 s"> for sin</span><span class="H1366 s">, throughout all thy borders</span>.</div> 
<div id="v300.17.4"><span class="H8058 s">And thou, even thyself, shalt discontinue</span><span class="H5159 s"> from thine heritage</span><span class="H5414 s"> that I gave</span><span class="H5647 s"> thee; and I will cause thee to serve</span><span class="H341 s"> thine enemies</span><span class="H776 s"> in the land</span><span class="H3045 s"> which thou knowest</span><span class="H6919 s"> not: for ye have kindled</span><span class="H784 s"> a fire</span><span class="H639 s"> in mine anger</span><span class="H3344 s">, <i>which</i> shall burn</span><span class="H5704 s"> for</span><span class="H5769 s"> ever</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (thyself: Heb. in thyself)</span></div> 
<div id="v300.17.5"><span class="H559 s">Thus saith</span><span class="H3068 s"> the LORD</span><span class="H779 s">; Cursed</span><span class="H1397 s"> <i>be</i> the man</span><span class="H982 s"> that trusteth</span><span class="H120 s"> in man</span><span class="H7760 s">, and maketh</span><span class="H1320 s"> flesh</span><span class="H2220 s"> his arm</span><span class="H3820 s">, and whose heart</span><span class="H5493 s"> departeth</span><span class="H3068 s"> from the LORD</span>.</div> 
<div id="v300.17.6"><span class="H6199 s">For he shall be like the heath</span><span class="H6160 s"> in the desert</span><span class="H7200 s">, and shall not see</span><span class="H2896 s"> when good</span><span class="H935 s"> cometh</span><span class="H7931 s">; but shall inhabit</span><span class="H2788 s"> the parched places</span><span class="H4057 s"> in the wilderness</span><span class="H4420 s">, <i>in</i> a salt</span><span class="H776 s"> land</span><span class="H3427 s"> and not inhabited</span>.</div> 
<div id="v300.17.7"><span class="H1288 s">Blessed</span><span class="H1397 s"> <i>is</i> the man</span><span class="H982 s"> that trusteth</span><span class="H3068 s"> in the LORD</span><span class="H4009 s">, and whose hope</span><span class="H3068 s"> the LORD</span> is.</div> 
<div id="v300.17.8"><span class="H6086 s">For he shall be as a tree</span><span class="H8362 s"> planted</span><span class="H4325 s"> by the waters</span><span class="H7971 s">, and <i>that</i> spreadeth out</span><span class="H8328 s"> her roots</span><span class="H3105 s"> by the river</span><span class="H7200 s">, and shall not see</span><span class="H2527 s"> when heat</span><span class="H935 s"> cometh</span><span class="H5929 s">, but her leaf</span><span class="H7488 s"> shall be green</span><span class="H1672 s">; and shall not be careful</span><span class="H8141 s"> in the year</span><span class="H1226 s"> of drought</span><span class="H4185 s">, neither shall cease</span><span class="H6213 s"> from yielding</span><span class="H6529 s"> fruit</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (drought: or, restraint)</span></div> 
<div id="v300.17.9"><span class="H3820 s">The heart</span><span class="H6121 s"> <i>is</i> deceitful</span><span class="H605 s"> above all <i>things</i>, and desperately wicked</span><span class="H3045 s">: who can know</span> it?</div> 
<div id="v300.17.10"><span class="H3068 s">I the LORD</span><span class="H2713 s"> search</span><span class="H3820 s"> the heart</span><span class="H974 s">, <i>I</i> try</span><span class="H3629 s"> the reins</span><span class="H5414 s">, even to give</span><span class="H376 s"> every man</span><span class="H1870 s"> according to his ways</span><span class="H6529 s">, <i>and</i> according to the fruit</span><span class="H4611 s"> of his doings</span>.</div> 
<div id="v300.17.11"><span class="H7124 s"><i>As</i> the partridge</span><span class="H1716 s"> sitteth</span><span class="H3205 s"> <i>on eggs</i>, and hatcheth</span><span class="H6213 s"> <i>them</i> not; <i>so</i> he that getteth</span><span class="H6239 s"> riches</span><span class="H4941 s">, and not by right</span><span class="H5800 s">, shall leave</span><span class="H2677 s"> them in the midst</span><span class="H3117 s"> of his days</span><span class="H319 s">, and at his end</span><span class="H5036 s"> shall be a fool</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (sitteth…: or, gathereth young which she hath not brought forth)</span></div> 
<div id="v300.17.12"><span class="H3519 s">A glorious</span><span class="H4791 s"> high</span><span class="H3678 s"> throne</span><span class="H7223 s"> from the beginning</span><span class="H4725 s"> <i>is</i> the place</span><span class="H4720 s"> of our sanctuary</span>.</div> 
<div id="v300.17.13"><span class="H3068 s">O LORD</span><span class="H4723 s">, the hope</span><span class="H3478 s"> of Israel</span><span class="H5800 s">, all that forsake</span><span class="H954 s"> thee shall be ashamed</span><span class="H3249 s">, <i>and</i> they that depart</span><span class="H5493 s"> from me</span><span class="H3789 s"> shall be written</span><span class="H776 s"> in the earth</span><span class="H5800 s">, because they have forsaken</span><span class="H3068 s"> the LORD</span><span class="H4726 s">, the fountain</span><span class="H2416 s"> of living</span><span class="H4325 s"> waters</span>.</div> 
<div id="v300.17.14"><span class="H7495 s">Heal</span><span class="H3068 s"> me, O LORD</span><span class="H7495 s">, and I shall be healed</span><span class="H3467 s">; save</span><span class="H3467 s"> me, and I shall be saved</span><span class="H8416 s">: for thou <i>art</i> my praise</span>.</div> 
<div id="v300.17.15"><span class="H559 s">Behold, they say</span><span class="H1697 s"> unto me, Where <i>is</i> the word</span><span class="H3068 s"> of the LORD</span><span class="H935 s">? let it come</span> now.</div> 
<div id="v300.17.16"><span class="H213 s">As for me, I have not hastened</span><span class="H7462 s"> from <i>being</i> a pastor</span><span class="H310 s"> to follow</span><span class="H183 s"> thee: neither have I desired</span><span class="H605 s"> the woeful</span><span class="H3117 s"> day</span><span class="H3045 s">; thou knowest</span><span class="H4161 s">: that which came out</span><span class="H8193 s"> of my lips</span><span class="H5227 s"> was <i>right</i> before</span><span class="H6440 s"> thee</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (to…: Heb. after thee)</span></div> 
<div id="v300.17.17"><span class="H4288 s">Be not a terror</span><span class="H4268 s"> unto me: thou <i>art</i> my hope</span><span class="H3117 s"> in the day</span><span class="H7451 s"> of evil</span>.</div> 
<div id="v300.17.18"><span class="H954 s">Let them be confounded</span><span class="H7291 s"> that persecute</span><span class="H954 s"> me, but let not me be confounded</span><span class="H2865 s">: let them be dismayed</span><span class="H2865 s">, but let not me be dismayed</span><span class="H935 s">: bring</span><span class="H3117 s"> upon them the day</span><span class="H7451 s"> of evil</span><span class="H7665 s">, and destroy</span><span class="H4932 s"> them with double</span><span class="H7670 s"> destruction</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (destroy…: Heb. break them with a double breach)</span></div> 
<div id="v300.17.19"><span class="H559 s">Thus said</span><span class="H3068 s"> the LORD</span><span class="H1980 s"> unto me; Go</span><span class="H5975 s"> and stand</span><span class="H8179 s"> in the gate</span><span class="H1121 s"> of the children</span><span class="H5971 s"> of the people</span><span class="H4428 s">, whereby the kings</span><span class="H3063 s"> of Judah</span><span class="H935 s"> come in</span><span class="H3318 s">, and by the which they go out</span><span class="H8179 s">, and in all the gates</span><span class="H3389 s"> of Jerusalem</span>;</div> 
<div id="v300.17.20"><span class="H559 s">And say</span><span class="H8085 s"> unto them, Hear</span><span class="H1697 s"> ye the word</span><span class="H3068 s"> of the LORD</span><span class="H4428 s">, ye kings</span><span class="H3063 s"> of Judah</span><span class="H3063 s">, and all Judah</span><span class="H3427 s">, and all the inhabitants</span><span class="H3389 s"> of Jerusalem</span><span class="H935 s">, that enter in</span><span class="H8179 s"> by these gates</span>:</div> 
<div id="v300.17.21"><span class="H559 s">Thus saith</span><span class="H3068 s"> the LORD</span><span class="H8104 s">; Take heed</span><span class="H5315 s"> to yourselves</span><span class="H5375 s">, and bear</span><span class="H4853 s"> no burden</span><span class="H7676 s"> on the sabbath</span><span class="H3117 s"> day</span><span class="H935 s">, nor bring</span><span class="H8179 s"> <i>it</i> in by the gates</span><span class="H3389 s"> of Jerusalem</span>;</div> 
<div id="v300.17.22"><span class="H3318 s">Neither carry forth</span><span class="H4853 s"> a burden</span><span class="H1004 s"> out of your houses</span><span class="H7676 s"> on the sabbath</span><span class="H3117 s"> day</span><span class="H6213 s">, neither do</span><span class="H4399 s"> ye any work</span><span class="H6942 s">, but hallow</span><span class="H7676 s"> ye the sabbath</span><span class="H3117 s"> day</span><span class="H6680 s">, as I commanded</span><span class="H1 s"> your fathers</span>.</div> 
<div id="v300.17.23"><span class="H8085 s">But they obeyed</span><span class="H5186 s"> not, neither inclined</span><span class="H241 s"> their ear</span><span class="H6203 s">, but made their neck</span><span class="H7185 s"> stiff</span><span class="H8085 s">, that they might not hear</span><span class="H3947 s">, nor receive</span><span class="H4148 s"> instruction</span>.</div> 
<div id="v300.17.24"><span class="H8085 s">And it shall come to pass, if ye diligently</span><span class="H8085 s"> hearken</span><span class="H5002 s"> unto me, saith</span><span class="H3068 s"> the LORD</span><span class="H935 s">, to bring</span><span class="H4853 s"> in no burden</span><span class="H8179 s"> through the gates</span><span class="H5892 s"> of this city</span><span class="H7676 s"> on the sabbath</span><span class="H3117 s"> day</span><span class="H6942 s">, but hallow</span><span class="H7676 s"> the sabbath</span><span class="H3117 s"> day</span><span class="H6213 s">, to do</span><span class="H1115 s"> no</span><span class="H4399 s"> work</span> therein;</div> 
<div id="v300.17.25"><span class="H935 s">Then shall there enter</span><span class="H8179 s"> into the gates</span><span class="H5892 s"> of this city</span><span class="H4428 s"> kings</span><span class="H8269 s"> and princes</span><span class="H3427 s"> sitting</span><span class="H3678 s"> upon the throne</span><span class="H1732 s"> of David</span><span class="H7392 s">, riding</span><span class="H7393 s"> in chariots</span><span class="H5483 s"> and on horses</span><span class="H8269 s">, they, and their princes</span><span class="H376 s">, the men</span><span class="H3063 s"> of Judah</span><span class="H3427 s">, and the inhabitants</span><span class="H3389 s"> of Jerusalem</span><span class="H5892 s">: and this city</span><span class="H3427 s"> shall remain</span><span class="H5769 s"> for ever</span>.</div> 
<div id="v300.17.26"><span class="H935 s">And they shall come</span><span class="H5892 s"> from the cities</span><span class="H3063 s"> of Judah</span><span class="H5439 s">, and from the places about</span><span class="H3389 s"> Jerusalem</span><span class="H776 s">, and from the land</span><span class="H1144 s"> of Benjamin</span><span class="H8219 s">, and from the plain</span><span class="H2022 s">, and from the mountains</span><span class="H5045 s">, and from the south</span><span class="H935 s">, bringing</span><span class="H5930 s"> burnt offerings</span><span class="H2077 s">, and sacrifices</span><span class="H4503 s">, and meat offerings</span><span class="H3828 s">, and incense</span><span class="H935 s">, and bringing</span><span class="H8426 s"> sacrifices of praise</span><span class="H1004 s">, unto the house</span><span class="H3068 s"> of the LORD</span>.</div> 
<div id="v300.17.27"><span class="H8085 s">But if ye will not hearken</span><span class="H6942 s"> unto me to hallow</span><span class="H7676 s"> the sabbath</span><span class="H3117 s"> day</span><span class="H5375 s">, and not to bear</span><span class="H4853 s"> a burden</span><span class="H935 s">, even entering in</span><span class="H8179 s"> at the gates</span><span class="H3389 s"> of Jerusalem</span><span class="H7676 s"> on the sabbath</span><span class="H3117 s"> day</span><span class="H3341 s">; then will I kindle</span><span class="H784 s"> a fire</span><span class="H8179 s"> in the gates</span><span class="H398 s"> thereof, and it shall devour</span><span class="H759 s"> the palaces</span><span class="H3389 s"> of Jerusalem</span><span class="H3518 s">, and it shall not be quenched</span>.</div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
