<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c240_10"> 
<div id="v240.10.1"><span class="H4912 s">The proverbs</span><span class="H8010 s"> of Solomon</span><span class="H2450 s">. A wise</span><span class="H1121 s"> son</span><span class="H8055 s"> maketh a glad</span><span class="H1 s"> father</span><span class="H3684 s">: but a foolish</span><span class="H1121 s"> son</span><span class="H8424 s"> <i>is</i> the heaviness</span><span class="H517 s"> of his mother</span>.</div> 
<div id="v240.10.2"><span class="H214 s">Treasures</span><span class="H7562 s"> of wickedness</span><span class="H3276 s"> profit</span><span class="H6666 s"> nothing: but righteousness</span><span class="H5337 s"> delivereth</span><span class="H4194 s"> from death</span>.</div> 
<div id="v240.10.3"><span class="H3068 s">The LORD</span><span class="H7456 s"> will not suffer</span><span class="H5315 s"> the soul</span><span class="H6662 s"> of the righteous</span><span class="H7456 s"> to famish</span><span class="H1920 s">: but he casteth away</span><span class="H1942 s"> the substance</span><span class="H7563 s"> of the wicked</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (the substance…: or, the wicked for their wickedness)</span></div> 
<div id="v240.10.4"><span class="H7326 s">He becometh poor</span><span class="H6213 s"> that dealeth</span><span class="H7423 s"> <i>with</i> a slack</span><span class="H3709 s"> hand</span><span class="H3027 s">: but the hand</span><span class="H2742 s"> of the diligent</span><span class="H6238 s"> maketh rich</span>.</div> 
<div id="v240.10.5"><span class="H103 s">He that gathereth</span><span class="H7019 s"> in summer</span><span class="H7919 s"> <i>is</i> a wise</span><span class="H1121 s"> son</span><span class="H7290 s">: <i>but</i> he that sleepeth</span><span class="H7105 s"> in harvest</span><span class="H1121 s"> <i>is</i> a son</span><span class="H954 s"> that causeth shame</span>.</div> 
<div id="v240.10.6"><span class="H1293 s">Blessings</span><span class="H7218 s"> <i>are</i> upon the head</span><span class="H6662 s"> of the just</span><span class="H2555 s">: but violence</span><span class="H3680 s"> covereth</span><span class="H6310 s"> the mouth</span><span class="H7563 s"> of the wicked</span>.</div> 
<div id="v240.10.7"><span class="H2143 s">The memory</span><span class="H6662 s"> of the just</span><span class="H1293 s"> <i>is</i> blessed</span><span class="H8034 s">: but the name</span><span class="H7563 s"> of the wicked</span><span class="H7537 s"> shall rot</span>.</div> 
<div id="v240.10.8"><span class="H2450 s">The wise</span><span class="H3820 s"> in heart</span><span class="H3947 s"> will receive</span><span class="H4687 s"> commandments</span><span class="H8193 s">: but a prating</span><span class="H191 s"> fool</span><span class="H3832 s"> shall fall</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (a prating…: Heb. a fool of lips) (fall: Heb. be beaten)</span></div> 
<div id="v240.10.9"><span class="H3212 s">He that walketh</span><span class="H8537 s"> uprightly</span><span class="H1980 s"> walketh</span><span class="H983 s"> surely</span><span class="H6140 s">: but he that perverteth</span><span class="H1870 s"> his ways</span><span class="H3045 s"> shall be known</span>.</div> 
<div id="v240.10.10"><span class="H7169 s">He that winketh</span><span class="H5869 s"> with the eye</span><span class="H5414 s"> causeth</span><span class="H6094 s"> sorrow</span><span class="H8193 s">: but a prating</span><span class="H191 s"> fool</span><span class="H3832 s"> shall fall</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (fall: Heb. be beaten)</span></div> 
<div id="v240.10.11"><span class="H6310 s">The mouth</span><span class="H6662 s"> of a righteous</span><span class="H4726 s"> <i>man is</i> a well</span><span class="H2416 s"> of life</span><span class="H2555 s">: but violence</span><span class="H3680 s"> covereth</span><span class="H6310 s"> the mouth</span><span class="H7563 s"> of the wicked</span>.</div> 
<div id="v240.10.12"><span class="H8135 s">Hatred</span><span class="H5782 s"> stirreth up</span><span class="H4090 s"> strifes</span><span class="H160 s">: but love</span><span class="H3680 s"> covereth</span><span class="H6588 s"> all sins</span>.</div> 
<div id="v240.10.13"><span class="H8193 s">In the lips</span><span class="H995 s"> of him that hath understanding</span><span class="H2451 s"> wisdom</span><span class="H4672 s"> is found</span><span class="H7626 s">: but a rod</span><span class="H1460 s"> <i>is</i> for the back</span><span class="H2638 s"> of him that is void</span><span class="H3820 s"> of understanding</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (of understanding: Heb. of heart)</span></div> 
<div id="v240.10.14"><span class="H2450 s">Wise</span><span class="H6845 s"> <i>men</i> lay up</span><span class="H1847 s"> knowledge</span><span class="H6310 s">: but the mouth</span><span class="H191 s"> of the foolish</span><span class="H7138 s"> <i>is</i> near</span><span class="H4288 s"> destruction</span>.</div> 
<div id="v240.10.15"><span class="H6223 s">The rich man's</span><span class="H1952 s"> wealth</span><span class="H5797 s"> <i>is</i> his strong</span><span class="H7151 s"> city</span><span class="H4288 s">: the destruction</span><span class="H1800 s"> of the poor</span><span class="H7389 s"> <i>is</i> their poverty</span>.</div> 
<div id="v240.10.16"><span class="H6468 s">The labour</span><span class="H6662 s"> of the righteous</span><span class="H2416 s"> <i>tendeth</i> to life</span><span class="H8393 s">: the fruit</span><span class="H7563 s"> of the wicked</span><span class="H2403 s"> to sin</span>.</div> 
<div id="v240.10.17"><span class="H734 s">He <i>is in</i> the way</span><span class="H2416 s"> of life</span><span class="H8104 s"> that keepeth</span><span class="H4148 s"> instruction</span><span class="H5800 s">: but he that refuseth</span><span class="H8433 s"> reproof</span><span class="H8582 s"> erreth</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (erreth: or, causeth to err)</span></div> 
<div id="v240.10.18"><span class="H3680 s">He that hideth</span><span class="H8135 s"> hatred</span><span class="H8267 s"> <i>with</i> lying</span><span class="H8193 s"> lips</span><span class="H3318 s">, and he that uttereth</span><span class="H1681 s"> a slander</span><span class="H3684 s">, <i>is</i> a fool</span>.</div> 
<div id="v240.10.19"><span class="H7230 s">In the multitude</span><span class="H1697 s"> of words</span><span class="H2308 s"> there wanteth</span><span class="H6588 s"> not sin</span><span class="H2820 s">: but he that refraineth</span><span class="H8193 s"> his lips</span><span class="H7919 s"> <i>is</i> wise</span>.</div> 
<div id="v240.10.20"><span class="H3956 s">The tongue</span><span class="H6662 s"> of the just</span><span class="H977 s"> <i>is as</i> choice</span><span class="H3701 s"> silver</span><span class="H3820 s">: the heart</span><span class="H7563 s"> of the wicked</span><span class="H4592 s"> <i>is</i> little worth</span>.</div> 
<div id="v240.10.21"><span class="H8193 s">The lips</span><span class="H6662 s"> of the righteous</span><span class="H7462 s"> feed</span><span class="H7227 s"> many</span><span class="H191 s">: but fools</span><span class="H4191 s"> die</span><span class="H2638 s"> for want</span><span class="H3820 s"> of wisdom</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (of wisdom: Heb. of heart)</span></div> 
<div id="v240.10.22"><span class="H1293 s">The blessing</span><span class="H3068 s"> of the LORD</span><span class="H6238 s">, it maketh rich</span><span class="H3254 s">, and he addeth</span><span class="H6089 s"> no sorrow</span> with it.</div> 
<div id="v240.10.23"><span class="H7814 s"><i>It is</i> as sport</span><span class="H3684 s"> to a fool</span><span class="H6213 s"> to do</span><span class="H2154 s"> mischief</span><span class="H376 s">: but a man</span><span class="H8394 s"> of understanding</span><span class="H2451 s"> hath wisdom</span>.</div> 
<div id="v240.10.24"><span class="H4034 s">The fear</span><span class="H7563 s"> of the wicked</span><span class="H935 s">, it shall come</span><span class="H8378 s"> upon him: but the desire</span><span class="H6662 s"> of the righteous</span><span class="H5414 s"> shall be granted</span>.</div> 
<div id="v240.10.25"><span class="H5492 s">As the whirlwind</span><span class="H5674 s"> passeth</span><span class="H7563 s">, so <i>is</i> the wicked</span><span class="H6662 s"> no <i>more</i>: but the righteous</span><span class="H5769 s"> <i>is</i> an everlasting</span><span class="H3247 s"> foundation</span>.</div> 
<div id="v240.10.26"><span class="H2558 s">As vinegar</span><span class="H8127 s"> to the teeth</span><span class="H6227 s">, and as smoke</span><span class="H5869 s"> to the eyes</span><span class="H6102 s">, so <i>is</i> the sluggard</span><span class="H7971 s"> to them that send</span> him.</div> 
<div id="v240.10.27"><span class="H3374 s">The fear</span><span class="H3068 s"> of the LORD</span><span class="H3254 s"> prolongeth</span><span class="H3117 s"> days</span><span class="H8141 s">: but the years</span><span class="H7563 s"> of the wicked</span><span class="H7114 s"> shall be shortened</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (prolongeth: Heb. addeth)</span></div> 
<div id="v240.10.28"><span class="H8431 s">The hope</span><span class="H6662 s"> of the righteous</span><span class="H8057 s"> <i>shall be</i> gladness</span><span class="H8615 s">: but the expectation</span><span class="H7563 s"> of the wicked</span><span class="H6 s"> shall perish</span>.</div> 
<div id="v240.10.29"><span class="H1870 s">The way</span><span class="H3068 s"> of the LORD</span><span class="H4581 s"> <i>is</i> strength</span><span class="H8537 s"> to the upright</span><span class="H4288 s">: but destruction</span><span class="H6466 s"> <i>shall be</i> to the workers</span><span class="H205 s"> of iniquity</span>.</div> 
<div id="v240.10.30"><span class="H6662 s">The righteous</span><span class="H5769 s"> shall never</span><span class="H4131 s"> be removed</span><span class="H7563 s">: but the wicked</span><span class="H7931 s"> shall not inhabit</span><span class="H776 s"> the earth</span>.</div> 
<div id="v240.10.31"><span class="H6310 s">The mouth</span><span class="H6662 s"> of the just</span><span class="H5107 s"> bringeth forth</span><span class="H2451 s"> wisdom</span><span class="H8419 s">: but the froward</span><span class="H3956 s"> tongue</span><span class="H3772 s"> shall be cut out</span>.</div> 
<div id="v240.10.32"><span class="H8193 s">The lips</span><span class="H6662 s"> of the righteous</span><span class="H3045 s"> know</span><span class="H7522 s"> what is acceptable</span><span class="H6310 s">: but the mouth</span><span class="H7563 s"> of the wicked</span><span class="H8419 s"> <i>speaketh</i> frowardness</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (frowardness: Heb. frowardnesses)</span></div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
