<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c10_48"> 
<div id="v10.48.1"><span class="H310 s">And it came to pass after</span><span class="H1697 s"> these things</span><span class="H559 s">, that <i>one</i> told</span><span class="H3130 s"> Joseph</span><span class="H1 s">, Behold, thy father</span><span class="H2470 s"> <i>is</i> sick</span><span class="H3947 s">: and he took</span><span class="H8147 s"> with him his two</span><span class="H1121 s"> sons</span><span class="H4519 s">, Manasseh</span><span class="H669 s"> and Ephraim</span>.</div> 
<div id="v10.48.2"><span class="H5046 s">And <i>one</i> told</span><span class="H3290 s"> Jacob</span><span class="H559 s">, and said</span><span class="H1121 s">, Behold, thy son</span><span class="H3130 s"> Joseph</span><span class="H935 s"> cometh</span><span class="H3478 s"> unto thee: and Israel</span><span class="H2388 s"> strengthened</span><span class="H3427 s"> himself, and sat</span><span class="H4296 s"> upon the bed</span>.</div> 
<div id="v10.48.3"><span class="H3290 s">And Jacob</span><span class="H559 s"> said</span><span class="H3130 s"> unto Joseph</span><span class="H410 s">, God</span><span class="H7706 s"> Almighty</span><span class="H7200 s"> appeared</span><span class="H3870 s"> unto me at Luz</span><span class="H776 s"> in the land</span><span class="H3667 s"> of Canaan</span><span class="H1288 s">, and blessed</span> me,</div> 
<div id="v10.48.4"><span class="H559 s">And said</span><span class="H6509 s"> unto me, Behold, I will make thee fruitful</span><span class="H7235 s">, and multiply</span><span class="H5414 s"> thee, and I will make</span><span class="H6951 s"> of thee a multitude</span><span class="H5971 s"> of people</span><span class="H5414 s">; and will give</span><span class="H776 s"> this land</span><span class="H2233 s"> to thy seed</span><span class="H310 s"> after thee</span><span class="H5769 s"> <i>for</i> an everlasting</span><span class="H272 s"> possession</span>.</div> 
<div id="v10.48.5"><span class="H8147 s">And now thy two</span><span class="H1121 s"> sons</span><span class="H669 s">, Ephraim</span><span class="H4519 s"> and Manasseh</span><span class="H3205 s">, which were born</span><span class="H776 s"> unto thee in the land</span><span class="H4714 s"> of Egypt</span><span class="H5704 s"> before</span><span class="H935 s"> I came</span><span class="H4714 s"> unto thee into Egypt</span><span class="H7205 s">, <i>are</i> mine; as Reuben</span><span class="H8095 s"> and Simeon</span>, they shall be mine.</div> 
<div id="v10.48.6"><span class="H4138 s">And thy issue</span><span class="H3205 s">, which thou begettest</span><span class="H310 s"> after</span><span class="H7121 s"> them, shall be thine, <i>and</i> shall be called</span><span class="H5921 s"> after</span><span class="H8034 s"> the name</span><span class="H251 s"> of their brethren</span><span class="H5159 s"> in their inheritance</span>.</div> 
<div id="v10.48.7"><span class="H935 s">And as for me, when I came</span><span class="H6307 s"> from Padan</span><span class="H7354 s">, Rachel</span><span class="H4191 s"> died</span><span class="H776 s"> by me in the land</span><span class="H3667 s"> of Canaan</span><span class="H1870 s"> in the way</span><span class="H5750 s">, when</span><span class="H3530 s"> yet <i>there was</i> but a little</span><span class="H776 s"> way</span><span class="H935 s"> to come</span><span class="H672 s"> unto Ephrath</span><span class="H6912 s">: and I buried her</span><span class="H1870 s"> there in the way</span><span class="H672 s"> of Ephrath</span><span class="H1035 s">; the same <i>is</i> Bethlehem</span>.</div> 
<div id="v10.48.8"><span class="H3478 s">And Israel</span><span class="H7200 s"> beheld</span><span class="H3130 s"> Joseph's</span><span class="H1121 s"> sons</span><span class="H559 s">, and said</span>, Who <i>are</i> these?</div> 
<div id="v10.48.9"><span class="H3130 s">And Joseph</span><span class="H559 s"> said</span><span class="H1 s"> unto his father</span><span class="H1121 s">, They <i>are</i> my sons</span><span class="H430 s">, whom God</span><span class="H5414 s"> hath given</span><span class="H559 s"> me in this <i>place</i>. And he said</span><span class="H3947 s">, Bring them</span><span class="H1288 s">, I pray thee, unto me, and I will bless</span> them.</div> 
<div id="v10.48.10"><span class="H5869 s">Now the eyes</span><span class="H3478 s"> of Israel</span><span class="H3513 s"> were dim</span><span class="H2207 s"> for age</span><span class="H3201 s">, <i>so that</i> he could</span><span class="H7200 s"> not see</span><span class="H5066 s">. And he brought them near</span><span class="H5401 s"> unto him; and he kissed</span><span class="H2263 s"> them, and embraced</span> them. <span class="notes">Notes by the 1611 King James Bible Translators: (dim: Heb. heavy)</span></div> 
<div id="v10.48.11"><span class="H3478 s">And Israel</span><span class="H559 s"> said</span><span class="H3130 s"> unto Joseph</span><span class="H6419 s">, I had not thought</span><span class="H7200 s"> to see</span><span class="H6440 s"> thy face</span><span class="H430 s">: and, lo, God</span><span class="H7200 s"> hath shewed</span><span class="H2233 s"> me also thy seed</span>.</div> 
<div id="v10.48.12"><span class="H3130 s">And Joseph</span><span class="H3318 s"> brought them out</span><span class="H5973 s"> from between</span><span class="H1290 s"> his knees</span><span class="H7812 s">, and he bowed</span><span class="H639 s"> himself with his face</span><span class="H776 s"> to the earth</span>.</div> 
<div id="v10.48.13"><span class="H3130 s">And Joseph</span><span class="H3947 s"> took</span><span class="H8147 s"> them both</span><span class="H669 s">, Ephraim</span><span class="H3225 s"> in his right hand</span><span class="H3478 s"> toward Israel's</span><span class="H8040 s"> left hand</span><span class="H4519 s">, and Manasseh</span><span class="H8040 s"> in his left hand</span><span class="H3478 s"> toward Israel's</span><span class="H3225 s"> right hand</span><span class="H5066 s">, and brought <i>them</i> near</span> unto him.</div> 
<div id="v10.48.14"><span class="H3478 s">And Israel</span><span class="H7971 s"> stretched out</span><span class="H3225 s"> his right hand</span><span class="H7896 s">, and laid</span><span class="H669 s"> <i>it</i> upon Ephraim's</span><span class="H7218 s"> head</span><span class="H6810 s">, who <i>was</i> the younger</span><span class="H8040 s">, and his left hand</span><span class="H4519 s"> upon Manasseh's</span><span class="H7218 s"> head</span><span class="H7919 s">, guiding</span><span class="H3027 s"> his hands</span><span class="H7919 s"> wittingly</span><span class="H4519 s">; for Manasseh</span><span class="H1060 s"> <i>was</i> the firstborn</span>.</div> 
<div id="v10.48.15"><span class="H1288 s">And he blessed</span><span class="H3130 s"> Joseph</span><span class="H559 s">, and said</span><span class="H430 s">, God</span><span class="H6440 s">, before</span><span class="H1 s"> whom my fathers</span><span class="H85 s"> Abraham</span><span class="H3327 s"> and Isaac</span><span class="H1980 s"> did walk</span><span class="H430 s">, the God</span><span class="H7462 s"> which fed</span><span class="H5750 s"> me all my life long</span><span class="H3117 s"> unto this day</span>,</div> 
<div id="v10.48.16"><span class="H4397 s">The Angel</span><span class="H1350 s"> which redeemed</span><span class="H7451 s"> me from all evil</span><span class="H1288 s">, bless</span><span class="H5288 s"> the lads</span><span class="H8034 s">; and let my name</span><span class="H7121 s"> be named</span><span class="H8034 s"> on them, and the name</span><span class="H1 s"> of my fathers</span><span class="H85 s"> Abraham</span><span class="H3327 s"> and Isaac</span><span class="H1711 s">; and let them grow</span><span class="H7230 s"> into a multitude</span><span class="H7130 s"> in the midst</span><span class="H776 s"> of the earth</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (grow: Heb. as fishes do increase)</span></div> 
<div id="v10.48.17"><span class="H3130 s">And when Joseph</span><span class="H7200 s"> saw</span><span class="H1 s"> that his father</span><span class="H7896 s"> laid</span><span class="H3225 s"> his right</span><span class="H3027 s"> hand</span><span class="H7218 s"> upon the head</span><span class="H669 s"> of Ephraim</span><span class="H3415 s">, it displeased</span><span class="H5869 s"> †</span><span class="H8551 s"> him: and he held up</span><span class="H1 s"> his father's</span><span class="H3027 s"> hand</span><span class="H5493 s">, to remove</span><span class="H669 s"> it from Ephraim's</span><span class="H7218 s"> head</span><span class="H4519 s"> unto Manasseh's</span><span class="H7218 s"> head</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (displeased…: was evil in his eyes)</span></div> 
<div id="v10.48.18"><span class="H3130 s">And Joseph</span><span class="H559 s"> said</span><span class="H1 s"> unto his father</span><span class="H1 s">, Not so, my father</span><span class="H1060 s">: for this <i>is</i> the firstborn</span><span class="H7760 s">; put</span><span class="H3225 s"> thy right hand</span><span class="H7218 s"> upon his head</span>.</div> 
<div id="v10.48.19"><span class="H1 s">And his father</span><span class="H3985 s"> refused</span><span class="H559 s">, and said</span><span class="H3045 s">, I know</span><span class="H1121 s"> <i>it</i>, my son</span><span class="H3045 s">, I know</span><span class="H5971 s"> <i>it</i>: he also shall become a people</span><span class="H1431 s">, and he also shall be great</span><span class="H199 s">: but truly</span><span class="H6996 s"> his younger</span><span class="H251 s"> brother</span><span class="H1431 s"> shall be greater</span><span class="H2233 s"> than he, and his seed</span><span class="H4393 s"> shall become a multitude</span><span class="H1471 s"> of nations</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (multitude: Heb. fulness)</span></div> 
<div id="v10.48.20"><span class="H1288 s">And he blessed</span><span class="H3117 s"> them that day</span><span class="H559 s">, saying</span><span class="H3478 s">, In thee shall Israel</span><span class="H1288 s"> bless</span><span class="H559 s">, saying</span><span class="H430 s">, God</span><span class="H7760 s"> make</span><span class="H669 s"> thee as Ephraim</span><span class="H4519 s"> and as Manasseh</span><span class="H7760 s">: and he set</span><span class="H669 s"> Ephraim</span><span class="H6440 s"> before</span><span class="H4519 s"> Manasseh</span>.</div> 
<div id="v10.48.21"><span class="H3478 s">And Israel</span><span class="H559 s"> said</span><span class="H3130 s"> unto Joseph</span><span class="H4191 s">, Behold, I die</span><span class="H430 s">: but God</span><span class="H7725 s"> shall be with you, and bring you again</span><span class="H776 s"> unto the land</span><span class="H1 s"> of your fathers</span>.</div> 
<div id="v10.48.22"><span class="H5414 s">Moreover I have given</span><span class="H259 s"> to thee one</span><span class="H7926 s"> portion</span><span class="H251 s"> above thy brethren</span><span class="H3947 s">, which I took</span><span class="H3027 s"> out of the hand</span><span class="H567 s"> of the Amorite</span><span class="H2719 s"> with my sword</span><span class="H7198 s"> and with my bow</span>.</div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
