<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c100_22"> 
<div id="v100.22.1"><span class="H1732 s">And David</span><span class="H1696 s"> spake</span><span class="H3068 s"> unto the LORD</span><span class="H1697 s"> the words</span><span class="H7892 s"> of this song</span><span class="H3117 s"> in the day</span><span class="H3068 s"> <i>that</i> the LORD</span><span class="H5337 s"> had delivered</span><span class="H3709 s"> him out of the hand</span><span class="H341 s"> of all his enemies</span><span class="H3709 s">, and out of the hand</span><span class="H7586 s"> of Saul</span>:</div> 
<div id="v100.22.2"><span class="H559 s">And he said</span><span class="H3068 s">, The LORD</span><span class="H5553 s"> <i>is</i> my rock</span><span class="H4686 s">, and my fortress</span><span class="H6403 s">, and my deliverer</span>;</div> 
<div id="v100.22.3"><span class="H430 s">The God</span><span class="H6697 s"> of my rock</span><span class="H2620 s">; in him will I trust</span><span class="H4043 s">: <i>he is</i> my shield</span><span class="H7161 s">, and the horn</span><span class="H3468 s"> of my salvation</span><span class="H4869 s">, my high tower</span><span class="H4498 s">, and my refuge</span><span class="H3467 s">, my saviour</span><span class="H3467 s">; thou savest</span><span class="H2555 s"> me from violence</span>.</div> 
<div id="v100.22.4"><span class="H7121 s">I will call</span><span class="H3068 s"> on the LORD</span><span class="H1984 s">, <i>who is</i> worthy to be praised</span><span class="H3467 s">: so shall I be saved</span><span class="H341 s"> from mine enemies</span>.</div> 
<div id="v100.22.5"><span class="H4867 s">When the waves</span><span class="H4194 s"> of death</span><span class="H661 s"> compassed</span><span class="H5158 s"> me, the floods</span><span class="H1100 s"> of ungodly men</span><span class="H1204 s"> made me afraid</span>; <span class="notes">Notes by the 1611 King James Bible Translators: (waves: or, pangs) (ungodly…: Heb. Belial)</span></div> 
<div id="v100.22.6"><span class="H2256 s">The sorrows</span><span class="H7585 s"> of hell</span><span class="H5437 s"> compassed me about</span><span class="H4170 s">; the snares</span><span class="H4194 s"> of death</span><span class="H6923 s"> prevented</span> me; <span class="notes">Notes by the 1611 King James Bible Translators: (sorrows: or, cords)</span></div> 
<div id="v100.22.7"><span class="H6862 s">In my distress</span><span class="H7121 s"> I called</span><span class="H3068 s"> upon the LORD</span><span class="H7121 s">, and cried</span><span class="H430 s"> to my God</span><span class="H8085 s">: and he did hear</span><span class="H6963 s"> my voice</span><span class="H1964 s"> out of his temple</span><span class="H7775 s">, and my cry</span><span class="H241 s"> <i>did enter</i> into his ears</span>.</div> 
<div id="v100.22.8"><span class="H776 s">Then the earth</span><span class="H1607 s"> shook</span><span class="H1607 s"> †</span><span class="H7493 s"> and trembled</span><span class="H4146 s">; the foundations</span><span class="H8064 s"> of heaven</span><span class="H7264 s"> moved</span><span class="H1607 s"> and shook</span><span class="H2734 s">, because he was wroth</span>.</div> 
<div id="v100.22.9"><span class="H5927 s">There went up</span><span class="H6227 s"> a smoke</span><span class="H639 s"> out of his nostrils</span><span class="H784 s">, and fire</span><span class="H6310 s"> out of his mouth</span><span class="H398 s"> devoured</span><span class="H1513 s">: coals</span><span class="H1197 s"> were kindled</span> by it. <span class="notes">Notes by the 1611 King James Bible Translators: (out of his nostrils: Heb. by, etc)</span></div> 
<div id="v100.22.10"><span class="H5186 s">He bowed</span><span class="H8064 s"> the heavens</span><span class="H3381 s"> also, and came down</span><span class="H6205 s">; and darkness</span><span class="H7272 s"> <i>was</i> under his feet</span>.</div> 
<div id="v100.22.11"><span class="H7392 s">And he rode</span><span class="H3742 s"> upon a cherub</span><span class="H5774 s">, and did fly</span><span class="H7200 s">: and he was seen</span><span class="H3671 s"> upon the wings</span><span class="H7307 s"> of the wind</span>.</div> 
<div id="v100.22.12"><span class="H7896 s">And he made</span><span class="H2822 s"> darkness</span><span class="H5521 s"> pavilions</span><span class="H5439 s"> round about</span><span class="H2841 s"> him, dark</span><span class="H4325 s"> waters</span><span class="H5645 s">, <i>and</i> thick clouds</span><span class="H7834 s"> of the skies</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (dark…: Heb. binding of waters)</span></div> 
<div id="v100.22.13"><span class="H5051 s">Through the brightness</span><span class="H1513 s"> before him were coals</span><span class="H784 s"> of fire</span><span class="H1197 s"> kindled</span>.</div> 
<div id="v100.22.14"><span class="H3068 s">The LORD</span><span class="H7481 s"> thundered</span><span class="H8064 s"> from heaven</span><span class="H5945 s">, and the most High</span><span class="H5414 s"> uttered</span><span class="H6963 s"> his voice</span>.</div> 
<div id="v100.22.15"><span class="H7971 s">And he sent out</span><span class="H2671 s"> arrows</span><span class="H6327 s">, and scattered</span><span class="H1300 s"> them; lightning</span><span class="H2000 s">, and discomfited</span> them.</div> 
<div id="v100.22.16"><span class="H650 s">And the channels</span><span class="H3220 s"> of the sea</span><span class="H7200 s"> appeared</span><span class="H4146 s">, the foundations</span><span class="H8398 s"> of the world</span><span class="H1540 s"> were discovered</span><span class="H1606 s">, at the rebuking</span><span class="H3068 s"> of the LORD</span><span class="H5397 s">, at the blast</span><span class="H7307 s"> of the breath</span><span class="H639 s"> of his nostrils</span>.</div> 
<div id="v100.22.17"><span class="H7971 s">He sent</span><span class="H4791 s"> from above</span><span class="H3947 s">, he took</span><span class="H4871 s"> me; he drew</span><span class="H7227 s"> me out of many</span><span class="H4325 s"> waters</span>; <span class="notes">Notes by the 1611 King James Bible Translators: (many: or, great)</span></div> 
<div id="v100.22.18"><span class="H5337 s">He delivered</span><span class="H5794 s"> me from my strong</span><span class="H341 s"> enemy</span><span class="H8130 s">, <i>and</i> from them that hated</span><span class="H553 s"> me: for they were too strong</span> for me.</div> 
<div id="v100.22.19"><span class="H6923 s">They prevented</span><span class="H3117 s"> me in the day</span><span class="H343 s"> of my calamity</span><span class="H3068 s">: but the LORD</span><span class="H4937 s"> was my stay</span>.</div> 
<div id="v100.22.20"><span class="H3318 s">He brought me forth</span><span class="H4800 s"> also into a large place</span><span class="H2502 s">: he delivered</span><span class="H2654 s"> me, because he delighted</span> in me.</div> 
<div id="v100.22.21"><span class="H3068 s">The LORD</span><span class="H1580 s"> rewarded</span><span class="H6666 s"> me according to my righteousness</span><span class="H1252 s">: according to the cleanness</span><span class="H3027 s"> of my hands</span><span class="H7725 s"> hath he recompensed</span> me.</div> 
<div id="v100.22.22"><span class="H8104 s">For I have kept</span><span class="H1870 s"> the ways</span><span class="H3068 s"> of the LORD</span><span class="H7561 s">, and have not wickedly departed</span><span class="H430 s"> from my God</span>.</div> 
<div id="v100.22.23"><span class="H4941 s">For all his judgments</span><span class="H2708 s"> <i>were</i> before me: and <i>as for</i> his statutes</span><span class="H5493 s">, I did not depart</span> from them.</div> 
<div id="v100.22.24"><span class="H8549 s">I was also upright</span><span class="H8104 s"> before him, and have kept</span><span class="H5771 s"> myself from mine iniquity</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (before: Heb. to)</span></div> 
<div id="v100.22.25"><span class="H3068 s">Therefore the LORD</span><span class="H7725 s"> hath recompensed</span><span class="H6666 s"> me according to my righteousness</span><span class="H1252 s">; according to my cleanness</span><span class="H5048 s"> in his eye sight</span><span class="H5869 s"> †</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (in…: Heb. before his eyes)</span></div> 
<div id="v100.22.26"><span class="H2623 s">With the merciful</span><span class="H2616 s"> thou wilt shew thyself merciful</span><span class="H8549 s">, <i>and</i> with the upright</span><span class="H1368 s"> man</span><span class="H8552 s"> thou wilt shew thyself upright</span>.</div> 
<div id="v100.22.27"><span class="H1305 s">With the pure</span><span class="H1305 s"> thou wilt shew thyself pure</span><span class="H6141 s">; and with the froward</span><span class="H6617 s"> thou wilt shew thyself unsavoury</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (shew thyself unsavoury: or, wrestle)</span></div> 
<div id="v100.22.28"><span class="H6041 s">And the afflicted</span><span class="H5971 s"> people</span><span class="H3467 s"> thou wilt save</span><span class="H5869 s">: but thine eyes</span><span class="H7311 s"> <i>are</i> upon the haughty</span><span class="H8213 s">, <i>that</i> thou mayest bring <i>them</i> down</span>.</div> 
<div id="v100.22.29"><span class="H5216 s">For thou <i>art</i> my lamp</span><span class="H3068 s">, O LORD</span><span class="H3068 s">: and the LORD</span><span class="H5050 s"> will lighten</span><span class="H2822 s"> my darkness</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (lamp: or, candle)</span></div> 
<div id="v100.22.30"><span class="H7323 s">For by thee I have run</span><span class="H1416 s"> through a troop</span><span class="H430 s">: by my God</span><span class="H1801 s"> have I leaped over</span><span class="H7791 s"> a wall</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (run: or, broken)</span></div> 
<div id="v100.22.31"><span class="H410 s"><i>As for</i> God</span><span class="H1870 s">, his way</span><span class="H8549 s"> <i>is</i> perfect</span><span class="H565 s">; the word</span><span class="H3068 s"> of the LORD</span><span class="H6884 s"> <i>is</i> tried</span><span class="H4043 s">: he <i>is</i> a buckler</span><span class="H2620 s"> to all them that trust</span> in him. <span class="notes">Notes by the 1611 King James Bible Translators: (tried: or, refined)</span></div> 
<div id="v100.22.32"><span class="H410 s">For who <i>is</i> God</span><span class="H1107 s">, save</span><span class="H3068 s"> the LORD</span><span class="H6697 s">? and who <i>is</i> a rock</span><span class="H1107 s">, save</span><span class="H430 s"> our God</span>?</div> 
<div id="v100.22.33"><span class="H410 s">God</span><span class="H4581 s"> <i>is</i> my strength</span><span class="H2428 s"> <i>and</i> power</span><span class="H5425 s">: and he maketh</span><span class="H1870 s"> my way</span><span class="H8549 s"> perfect</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (maketh: Heb. riddeth, or, looseth)</span></div> 
<div id="v100.22.34"><span class="H7737 s">He maketh</span><span class="H7272 s"> my feet</span><span class="H7737 s"> like</span><span class="H355 s fixed"> hinds'</span><span class="H5975 s"> <i>feet</i>: and setteth</span><span class="H1116 s"> me upon my high places</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (maketh: Heb. equalleth)</span></div> 
<div id="v100.22.35"><span class="H3925 s">He teacheth</span><span class="H3027 s"> my hands</span><span class="H4421 s"> to war</span><span class="H7198 s">; so that a bow</span><span class="H5154 s"> of steel</span><span class="H5181 s"> is broken</span><span class="H2220 s"> by mine arms</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (to war: Heb. for the war)</span></div> 
<div id="v100.22.36"><span class="H5414 s">Thou hast also given</span><span class="H4043 s"> me the shield</span><span class="H3468 s"> of thy salvation</span><span class="H6031 s">: and thy gentleness</span><span class="H6038 s"> †</span><span class="H7235 s"> hath made me great</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (made…: Heb. multiplied me)</span></div> 
<div id="v100.22.37"><span class="H7337 s">Thou hast enlarged</span><span class="H6806 s"> my steps</span><span class="H7166 s"> under me; so that my feet</span><span class="H4571 s"> did not slip</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (feet: Heb. ankles)</span></div> 
<div id="v100.22.38"><span class="H7291 s">I have pursued</span><span class="H341 s"> mine enemies</span><span class="H8045 s">, and destroyed</span><span class="H7725 s"> them; and turned not again</span><span class="H3615 s"> until I had consumed</span> them.</div> 
<div id="v100.22.39"><span class="H3615 s">And I have consumed</span><span class="H4272 s"> them, and wounded</span><span class="H6965 s"> them, that they could not arise</span><span class="H5307 s">: yea, they are fallen</span><span class="H7272 s"> under my feet</span>.</div> 
<div id="v100.22.40"><span class="H247 s">For thou hast girded</span><span class="H2428 s"> me with strength</span><span class="H4421 s"> to battle</span><span class="H6965 s">: them that rose up</span><span class="H3766 s"> against me hast thou subdued</span> under me. <span class="notes">Notes by the 1611 King James Bible Translators: (subdued: Heb. caused to bow)</span></div> 
<div id="v100.22.41"><span class="H5414 s">Thou hast also given</span><span class="H6203 s"> me the necks</span><span class="H341 s"> of mine enemies</span><span class="H6789 s">, that I might destroy</span><span class="H8130 s"> them that hate</span> me.</div> 
<div id="v100.22.42"><span class="H8159 s">They looked</span><span class="H3467 s">, but <i>there was</i> none to save</span><span class="H3068 s">; <i>even</i> unto the LORD</span><span class="H6030 s">, but he answered</span> them not.</div> 
<div id="v100.22.43"><span class="H7833 s">Then did I beat</span><span class="H6083 s"> them as small as the dust</span><span class="H776 s"> of the earth</span><span class="H1854 s">, I did stamp</span><span class="H2916 s"> them as the mire</span><span class="H2351 s"> of the street</span><span class="H7554 s">, <i>and</i> did spread them abroad</span>.</div> 
<div id="v100.22.44"><span class="H6403 s">Thou also hast delivered</span><span class="H7379 s"> me from the strivings</span><span class="H5971 s"> of my people</span><span class="H8104 s">, thou hast kept</span><span class="H7218 s"> me <i>to be</i> head</span><span class="H1471 s"> of the heathen</span><span class="H5971 s">: a people</span><span class="H3045 s"> <i>which</i> I knew</span><span class="H5647 s"> not shall serve</span> me.</div> 
<div id="v100.22.45"><span class="H1121 s">Strangers</span><span class="H5236 s"> †</span><span class="H3584 s"> shall submit</span><span class="H8085 s"> themselves unto me: as soon as they hear</span><span class="H241 s"> †</span><span class="H8085 s">, they shall be obedient</span> unto me. <span class="notes">Notes by the 1611 King James Bible Translators: (Strangers: Heb. Sons of the stranger) (submit…: or, yield feigned obedience: Heb. lie)</span></div> 
<div id="v100.22.46"><span class="H1121 s">Strangers</span><span class="H5236 s"> †</span><span class="H5034 s"> shall fade away</span><span class="H2296 s">, and they shall be afraid</span><span class="H4526 s"> out of their close places</span>.</div> 
<div id="v100.22.47"><span class="H3068 s">The LORD</span><span class="H2416 s"> liveth</span><span class="H1288 s">; and blessed</span><span class="H6697 s"> <i>be</i> my rock</span><span class="H7311 s">; and exalted</span><span class="H430 s"> be the God</span><span class="H6697 s"> of the rock</span><span class="H3468 s"> of my salvation</span>.</div> 
<div id="v100.22.48"><span class="H410 s">It <i>is</i> God</span><span class="H5414 s"> that avengeth</span><span class="H5360 s"> †</span><span class="H3381 s"> me, and that bringeth down</span><span class="H5971 s"> the people</span> under me, <span class="notes">Notes by the 1611 King James Bible Translators: (avengeth: Heb. giveth avengement for)</span></div> 
<div id="v100.22.49"><span class="H3318 s">And that bringeth me forth</span><span class="H341 s"> from mine enemies</span><span class="H7311 s">: thou also hast lifted me up on high</span><span class="H6965 s"> above them that rose up</span><span class="H5337 s"> against me: thou hast delivered</span><span class="H2555 s"> me from the violent</span><span class="H376 s"> man</span>.</div> 
<div id="v100.22.50"><span class="H3034 s">Therefore I will give thanks</span><span class="H3068 s"> unto thee, O LORD</span><span class="H1471 s">, among the heathen</span><span class="H2167 s">, and I will sing praises</span><span class="H8034 s"> unto thy name</span>.</div> 
<div id="v100.22.51"><span class="H4024 s"><i>He is</i> the tower</span><span class="H1431 s"> †</span><span class="H3444 s"> of salvation</span><span class="H4428 s"> for his king</span><span class="H6213 s">: and sheweth</span><span class="H2617 s"> mercy</span><span class="H4899 s"> to his anointed</span><span class="H1732 s">, unto David</span><span class="H2233 s">, and to his seed</span><span class="H5704 s"> for</span><span class="H5769 s"> evermore</span>.</div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
