<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c160_3"> 
<div id="v160.3.1"><span class="H475 s">Then Eliashib</span><span class="H1419 s"> the high</span><span class="H3548 s"> priest</span><span class="H6965 s"> rose up</span><span class="H251 s"> with his brethren</span><span class="H3548 s"> the priests</span><span class="H1129 s">, and they builded</span><span class="H6629 s"> the sheep</span><span class="H8179 s"> gate</span><span class="H6942 s">; they sanctified</span><span class="H5975 s"> it, and set up</span><span class="H1817 s"> the doors</span><span class="H4026 s"> of it; even unto the tower</span><span class="H3968 s"> of Meah</span><span class="H6942 s"> they sanctified</span><span class="H4026 s"> it, unto the tower</span><span class="H2606 s"> of Hananeel</span>.</div> 
<div id="v160.3.2"><span class="H3027 s">And next unto him</span><span class="H1129 s"> builded</span><span class="H582 s"> the men</span><span class="H3405 s"> of Jericho</span><span class="H1129 s">. And next to them builded</span><span class="H2139 s"> Zaccur</span><span class="H1121 s"> the son</span><span class="H566 s"> of Imri</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (next unto…: Heb. at his hand)</span></div> 
<div id="v160.3.3"><span class="H1709 s">But the fish</span><span class="H8179 s"> gate</span><span class="H1121 s"> did the sons</span><span class="H5570 s"> of Hassenaah</span><span class="H1129 s"> build</span><span class="H7136 s">, who <i>also</i> laid the beams</span><span class="H5975 s"> thereof, and set up</span><span class="H1817 s"> the doors</span><span class="H4514 s"> thereof, the locks</span><span class="H1280 s"> thereof, and the bars</span> thereof.</div> 
<div id="v160.3.4"><span class="H3027 s">And next unto them</span><span class="H2388 s"> repaired</span><span class="H4822 s"> Meremoth</span><span class="H1121 s"> the son</span><span class="H223 s"> of Urijah</span><span class="H1121 s">, the son</span><span class="H6976 s"> of Koz</span><span class="H3027 s">. And next unto them</span><span class="H2388 s"> repaired</span><span class="H4918 s"> Meshullam</span><span class="H1121 s"> the son</span><span class="H1296 s"> of Berechiah</span><span class="H1121 s">, the son</span><span class="H4898 s"> of Meshezabeel</span><span class="H3027 s">. And next unto them</span><span class="H2388 s"> repaired</span><span class="H6659 s"> Zadok</span><span class="H1121 s"> the son</span><span class="H1195 s"> of Baana</span>.</div> 
<div id="v160.3.5"><span class="H3027 s">And next unto them</span><span class="H8621 s"> the Tekoites</span><span class="H2388 s"> repaired</span><span class="H117 s">; but their nobles</span><span class="H935 s"> put</span><span class="H6677 s"> not their necks</span><span class="H5656 s"> to the work</span><span class="H113 s"> of their Lord</span>.</div> 
<div id="v160.3.6"><span class="H3465 s">Moreover the old</span><span class="H8179 s"> gate</span><span class="H2388 s"> repaired</span><span class="H3111 s"> Jehoiada</span><span class="H1121 s"> the son</span><span class="H6454 s"> of Paseah</span><span class="H4918 s">, and Meshullam</span><span class="H1121 s"> the son</span><span class="H1152 s"> of Besodeiah</span><span class="H7136 s">; they laid the beams</span><span class="H5975 s"> thereof, and set up</span><span class="H1817 s"> the doors</span><span class="H4514 s"> thereof, and the locks</span><span class="H1280 s"> thereof, and the bars</span> thereof.</div> 
<div id="v160.3.7"><span class="H3027 s">And next unto them</span><span class="H2388 s"> repaired</span><span class="H4424 s"> Melatiah</span><span class="H1393 s"> the Gibeonite</span><span class="H3036 s">, and Jadon</span><span class="H4824 s"> the Meronothite</span><span class="H582 s">, the men</span><span class="H1391 s"> of Gibeon</span><span class="H4709 s">, and of Mizpah</span><span class="H3678 s">, unto the throne</span><span class="H6346 s"> of the governor</span><span class="H5676 s"> on this side</span><span class="H5104 s"> the river</span>.</div> 
<div id="v160.3.8"><span class="H3027 s">Next unto him</span><span class="H2388 s"> repaired</span><span class="H5816 s"> Uzziel</span><span class="H1121 s"> the son</span><span class="H2736 s"> of Harhaiah</span><span class="H6884 s">, of the goldsmiths</span><span class="H3027 s">. Next unto him</span><span class="H2388 s"> also repaired</span><span class="H2608 s"> Hananiah</span><span class="H1121 s"> the son</span><span class="H7546 s"> of <i>one of</i> the apothecaries</span><span class="H5800 s">, and they fortified</span><span class="H3389 s"> Jerusalem</span><span class="H7342 s"> unto the broad</span><span class="H2346 s"> wall</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (fortified…: or, left Jerusalem unto the broad wall)</span></div> 
<div id="v160.3.9"><span class="H3027 s">And next unto them</span><span class="H2388 s"> repaired</span><span class="H7509 s"> Rephaiah</span><span class="H1121 s"> the son</span><span class="H2354 s"> of Hur</span><span class="H8269 s">, the ruler</span><span class="H2677 s"> of the half</span><span class="H6418 s"> part</span><span class="H3389 s"> of Jerusalem</span>.</div> 
<div id="v160.3.10"><span class="H3027 s">And next unto them</span><span class="H2388 s"> repaired</span><span class="H3042 s"> Jedaiah</span><span class="H1121 s"> the son</span><span class="H2739 s"> of Harumaph</span><span class="H1004 s">, even over against his house</span><span class="H3027 s">. And next unto him</span><span class="H2388 s"> repaired</span><span class="H2407 s"> Hattush</span><span class="H1121 s"> the son</span><span class="H2813 s"> of Hashabniah</span>.</div> 
<div id="v160.3.11"><span class="H4441 s">Malchijah</span><span class="H1121 s"> the son</span><span class="H2766 s"> of Harim</span><span class="H2815 s">, and Hashub</span><span class="H1121 s"> the son</span><span class="H6355 s"> of Pahathmoab</span><span class="H2388 s">, repaired</span><span class="H8145 s"> the other</span><span class="H4060 s"> piece</span><span class="H4026 s">, and the tower</span><span class="H8574 s"> of the furnaces</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (other…: Heb. second measure)</span></div> 
<div id="v160.3.12"><span class="H3027 s">And next unto him</span><span class="H2388 s"> repaired</span><span class="H7967 s"> Shallum</span><span class="H1121 s"> the son</span><span class="H3873 s"> of Halohesh</span><span class="H8269 s">, the ruler</span><span class="H2677 s"> of the half</span><span class="H6418 s"> part</span><span class="H3389 s"> of Jerusalem</span><span class="H1323 s">, he and his daughters</span>.</div> 
<div id="v160.3.13"><span class="H1516 s">The valley</span><span class="H8179 s"> gate</span><span class="H2388 s"> repaired</span><span class="H2586 s"> Hanun</span><span class="H3427 s">, and the inhabitants</span><span class="H2182 s"> of Zanoah</span><span class="H1129 s">; they built</span><span class="H5975 s"> it, and set up</span><span class="H1817 s"> the doors</span><span class="H4514 s"> thereof, the locks</span><span class="H1280 s"> thereof, and the bars</span><span class="H505 s"> thereof, and a thousand</span><span class="H520 s"> cubits</span><span class="H2346 s"> on the wall</span><span class="H830 s"> unto the dung</span><span class="H8179 s"> gate</span>.</div> 
<div id="v160.3.14"><span class="H830 s">But the dung</span><span class="H8179 s"> gate</span><span class="H2388 s"> repaired</span><span class="H4441 s"> Malchiah</span><span class="H1121 s"> the son</span><span class="H7394 s"> of Rechab</span><span class="H8269 s">, the ruler</span><span class="H6418 s"> of part</span><span class="H1021 s"> of Bethhaccerem</span><span class="H1129 s">; he built</span><span class="H5975 s"> it, and set up</span><span class="H1817 s"> the doors</span><span class="H4514 s"> thereof, the locks</span><span class="H1280 s"> thereof, and the bars</span> thereof.</div> 
<div id="v160.3.15"><span class="H8179 s">But the gate</span><span class="H5869 s"> of the fountain</span><span class="H2388 s"> repaired</span><span class="H7968 s"> Shallun</span><span class="H1121 s"> the son</span><span class="H3626 s"> of Colhozeh</span><span class="H8269 s">, the ruler</span><span class="H6418 s"> of part</span><span class="H4709 s"> of Mizpah</span><span class="H1129 s">; he built</span><span class="H2926 s"> it, and covered</span><span class="H5975 s"> it, and set up</span><span class="H1817 s"> the doors</span><span class="H4514 s"> thereof, the locks</span><span class="H1280 s"> thereof, and the bars</span><span class="H2346 s"> thereof, and the wall</span><span class="H1295 s"> of the pool</span><span class="H7975 s"> of Siloah</span><span class="H4428 s"> by the king's</span><span class="H1588 s"> garden</span><span class="H4609 s">, and unto the stairs</span><span class="H3381 s"> that go down</span><span class="H5892 s"> from the city</span><span class="H1732 s"> of David</span>.</div> 
<div id="v160.3.16"><span class="H310 s">After</span><span class="H2388 s"> him repaired</span><span class="H5166 s"> Nehemiah</span><span class="H1121 s"> the son</span><span class="H5802 s"> of Azbuk</span><span class="H8269 s">, the ruler</span><span class="H2677 s"> of the half</span><span class="H6418 s"> part</span><span class="H1049 s"> of Bethzur</span><span class="H6913 s">, unto <i>the place</i> over against the sepulchres</span><span class="H1732 s"> of David</span><span class="H1295 s">, and to the pool</span><span class="H6213 s"> that was made</span><span class="H1004 s">, and unto the house</span><span class="H1368 s"> of the mighty</span>.</div> 
<div id="v160.3.17"><span class="H310 s">After</span><span class="H2388 s"> him repaired</span><span class="H3881 s"> the Levites</span><span class="H7348 s">, Rehum</span><span class="H1121 s"> the son</span><span class="H1137 s"> of Bani</span><span class="H3027 s">. Next unto him</span><span class="H2388 s"> repaired</span><span class="H2811 s"> Hashabiah</span><span class="H8269 s">, the ruler</span><span class="H2677 s"> of the half</span><span class="H6418 s"> part</span><span class="H7084 s"> of Keilah</span><span class="H6418 s">, in his part</span>.</div> 
<div id="v160.3.18"><span class="H310 s">After</span><span class="H2388 s"> him repaired</span><span class="H251 s"> their brethren</span><span class="H942 s">, Bavai</span><span class="H1121 s"> the son</span><span class="H2582 s"> of Henadad</span><span class="H8269 s">, the ruler</span><span class="H2677 s"> of the half</span><span class="H6418 s"> part</span><span class="H7084 s"> of Keilah</span>.</div> 
<div id="v160.3.19"><span class="H3027 s">And next to him</span><span class="H2388 s"> repaired</span><span class="H5829 s"> Ezer</span><span class="H1121 s"> the son</span><span class="H3442 s"> of Jeshua</span><span class="H8269 s">, the ruler</span><span class="H4709 s"> of Mizpah</span><span class="H8145 s">, another</span><span class="H4060 s"> piece</span><span class="H5927 s"> over against the going up</span><span class="H5402 s"> to the armoury</span><span class="H4740 s"> at the turning</span> <i>of the wall</i>.</div> 
<div id="v160.3.20"><span class="H310 s">After</span><span class="H1263 s"> him Baruch</span><span class="H1121 s"> the son</span><span class="H2079 s"> of Zabbai</span><span class="H2734 s"> earnestly</span><span class="H2388 s"> repaired</span><span class="H8145 s"> the other</span><span class="H4060 s"> piece</span><span class="H4740 s">, from the turning</span><span class="H6607 s"> <i>of the wall</i> unto the door</span><span class="H1004 s"> of the house</span><span class="H475 s"> of Eliashib</span><span class="H1419 s"> the high</span><span class="H3548 s"> priest</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (Zabbai: or, Zaccai)</span></div> 
<div id="v160.3.21"><span class="H310 s">After</span><span class="H2388 s"> him repaired</span><span class="H4822 s"> Meremoth</span><span class="H1121 s"> the son</span><span class="H223 s"> of Urijah</span><span class="H1121 s"> the son</span><span class="H6976 s"> of Koz</span><span class="H8145 s"> another</span><span class="H4060 s"> piece</span><span class="H6607 s">, from the door</span><span class="H1004 s"> of the house</span><span class="H475 s"> of Eliashib</span><span class="H8503 s"> even to the end</span><span class="H1004 s"> of the house</span><span class="H475 s"> of Eliashib</span>.</div> 
<div id="v160.3.22"><span class="H310 s">And after</span><span class="H2388 s"> him repaired</span><span class="H3548 s"> the priests</span><span class="H582 s">, the men</span><span class="H3603 s"> of the plain</span>.</div> 
<div id="v160.3.23"><span class="H310 s">After</span><span class="H2388 s"> him repaired</span><span class="H1144 s"> Benjamin</span><span class="H2815 s"> and Hashub</span><span class="H1004 s"> over against their house</span><span class="H310 s">. After</span><span class="H2388 s"> him repaired</span><span class="H5838 s"> Azariah</span><span class="H1121 s"> the son</span><span class="H4641 s"> of Maaseiah</span><span class="H1121 s"> the son</span><span class="H6055 s"> of Ananiah</span><span class="H681 s"> by</span><span class="H1004 s"> his house</span>.</div> 
<div id="v160.3.24"><span class="H310 s">After</span><span class="H2388 s"> him repaired</span><span class="H1131 s"> Binnui</span><span class="H1121 s"> the son</span><span class="H2582 s"> of Henadad</span><span class="H8145 s"> another</span><span class="H4060 s"> piece</span><span class="H1004 s">, from the house</span><span class="H5838 s"> of Azariah</span><span class="H4740 s"> unto the turning</span><span class="H6438 s"> <i>of the wall</i>, even unto the corner</span>.</div> 
<div id="v160.3.25"><span class="H6420 s">Palal</span><span class="H1121 s"> the son</span><span class="H186 s"> of Uzai</span><span class="H4740 s">, over against the turning</span><span class="H4026 s"> <i>of the wall</i>, and the tower</span><span class="H3318 s"> which lieth out</span><span class="H4428 s"> from the king's</span><span class="H5945 s"> high</span><span class="H1004 s"> house</span><span class="H2691 s">, that <i>was</i> by the court</span><span class="H4307 s"> of the prison</span><span class="H310 s">. After</span><span class="H6305 s"> him Pedaiah</span><span class="H1121 s"> the son</span><span class="H6551 s"> of Parosh</span>.</div> 
<div id="v160.3.26"><span class="H5411 s">Moreover the Nethinims</span><span class="H3427 s"> dwelt</span><span class="H6077 s"> in Ophel</span><span class="H4325 s">, unto <i>the place</i> over against the water</span><span class="H8179 s"> gate</span><span class="H4217 s"> toward the east</span><span class="H4026 s">, and the tower</span><span class="H3318 s"> that lieth out</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (dwelt…: or, which dwelt in Ophel, repaired unto) (Ophel: or, tower)</span></div> 
<div id="v160.3.27"><span class="H310 s">After</span><span class="H8621 s"> them the Tekoites</span><span class="H2388 s"> repaired</span><span class="H8145 s"> another</span><span class="H4060 s"> piece</span><span class="H1419 s">, over against the great</span><span class="H4026 s"> tower</span><span class="H3318 s"> that lieth out</span><span class="H2346 s">, even unto the wall</span><span class="H6077 s"> of Ophel</span>.</div> 
<div id="v160.3.28"><span class="H5483 s">From above the horse</span><span class="H8179 s"> gate</span><span class="H2388 s"> repaired</span><span class="H3548 s"> the priests</span><span class="H376 s">, every one</span><span class="H5048 s"> over against</span><span class="H1004 s"> his house</span>.</div> 
<div id="v160.3.29"><span class="H310 s">After</span><span class="H2388 s"> them repaired</span><span class="H6659 s"> Zadok</span><span class="H1121 s"> the son</span><span class="H564 s"> of Immer</span><span class="H1004 s"> over against his house</span><span class="H310 s">. After</span><span class="H2388 s"> him repaired</span><span class="H8098 s"> also Shemaiah</span><span class="H1121 s"> the son</span><span class="H7935 s"> of Shechaniah</span><span class="H8104 s">, the keeper</span><span class="H4217 s"> of the east</span><span class="H8179 s"> gate</span>.</div> 
<div id="v160.3.30"><span class="H310 s">After</span><span class="H2388 s"> him repaired</span><span class="H2608 s"> Hananiah</span><span class="H1121 s"> the son</span><span class="H8018 s"> of Shelemiah</span><span class="H2586 s">, and Hanun</span><span class="H8345 s"> the sixth</span><span class="H1121 s"> son</span><span class="H6764 s"> of Zalaph</span><span class="H8145 s">, another</span><span class="H4060 s"> piece</span><span class="H310 s">. After</span><span class="H2388 s"> him repaired</span><span class="H4918 s"> Meshullam</span><span class="H1121 s"> the son</span><span class="H1296 s"> of Berechiah</span><span class="H5393 s"> over against his chamber</span>.</div> 
<div id="v160.3.31"><span class="H310 s">After</span><span class="H2388 s"> him repaired</span><span class="H4441 s"> Malchiah</span><span class="H6885 s"> the goldsmith's</span><span class="H1121 s"> son</span><span class="H1004 s"> unto the place</span><span class="H5411 s"> of the Nethinims</span><span class="H7402 s">, and of the merchants</span><span class="H8179 s">, over against the gate</span><span class="H4663 s"> Miphkad</span><span class="H5944 s">, and to the going up</span><span class="H6438 s"> of the corner</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (going…: or, corner chamber)</span></div> 
<div id="v160.3.32"><span class="H5944 s">And between the going up</span><span class="H6438 s"> of the corner</span><span class="H6629 s"> unto the sheep</span><span class="H8179 s"> gate</span><span class="H2388 s"> repaired</span><span class="H6884 s"> the goldsmiths</span><span class="H7402 s"> and the merchants</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (going…: or, corner chamber)</span></div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
