<html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"><link type="text/css" rel="stylesheet" href="_TheLordTitlesAndRL.css" /></head><body>

<div class="c330_8"> 
<div id="v330.8.1"><span class="H8345 s">And it came to pass in the sixth</span><span class="H8141 s"> year</span><span class="H8345 s">, in the sixth</span><span class="H2568 s"> <i>month</i>, in the fifth</span><span class="H2320 s"> <i>day</i> of the month</span><span class="H3427 s">, <i>as</i> I sat</span><span class="H1004 s"> in mine house</span><span class="H2205 s">, and the elders</span><span class="H3063 s"> of Judah</span><span class="H3427 s"> sat</span><span class="H6440 s"> before</span><span class="H3027 s"> me, that the hand</span><span class="H136 s"> of the Lord</span><span class="H3069 s"> GOD</span><span class="H5307 s"> fell</span> there upon me.</div> 
<div id="v330.8.2"><span class="H7200 s">Then I beheld</span><span class="H1823 s">, and lo a likeness</span><span class="H4758 s"> as the appearance</span><span class="H784 s"> of fire</span><span class="H4758 s">: from the appearance</span><span class="H4975 s"> of his loins</span><span class="H4295 s"> even downward</span><span class="H784 s">, fire</span><span class="H4975 s">; and from his loins</span><span class="H4605 s"> even upward</span><span class="H4758 s">, as the appearance</span><span class="H2096 s"> of brightness</span><span class="H5869 s">, as the colour</span><span class="H2830 s"> of amber</span>.</div> 
<div id="v330.8.3"><span class="H7971 s">And he put forth</span><span class="H8403 s"> the form</span><span class="H3027 s"> of an hand</span><span class="H3947 s">, and took</span><span class="H6734 s"> me by a lock</span><span class="H7218 s"> of mine head</span><span class="H7307 s">; and the spirit</span><span class="H5375 s"> lifted me up</span><span class="H776 s"> between the earth</span><span class="H8064 s"> and the heaven</span><span class="H935 s">, and brought</span><span class="H4759 s"> me in the visions</span><span class="H430 s"> of God</span><span class="H3389 s"> to Jerusalem</span><span class="H6607 s">, to the door</span><span class="H6442 s"> of the inner</span><span class="H8179 s"> gate</span><span class="H6437 s"> that looketh</span><span class="H6828 s"> toward the north</span><span class="H4186 s">; where <i>was</i> the seat</span><span class="H5566 s"> of the image</span><span class="H7068 s"> of jealousy</span><span class="H7069 s">, which provoketh to jealousy</span>.</div> 
<div id="v330.8.4"><span class="H3519 s">And, behold, the glory</span><span class="H430 s"> of the God</span><span class="H3478 s"> of Israel</span><span class="H4758 s"> <i>was</i> there, according to the vision</span><span class="H7200 s"> that I saw</span><span class="H1237 s"> in the plain</span>.</div> 
<div id="v330.8.5"><span class="H559 s">Then said</span><span class="H1121 s"> he unto me, Son</span><span class="H120 s"> of man</span><span class="H5375 s">, lift up</span><span class="H5869 s"> thine eyes</span><span class="H1870 s"> now the way</span><span class="H6828 s"> toward the north</span><span class="H5375 s">. So I lifted up</span><span class="H5869 s"> mine eyes</span><span class="H1870 s"> the way</span><span class="H6828 s"> toward the north</span><span class="H6828 s">, and behold northward</span><span class="H8179 s"> at the gate</span><span class="H4196 s"> of the altar</span><span class="H5566 s"> this image</span><span class="H7068 s"> of jealousy</span><span class="H872 s"> in the entry</span>.</div> 
<div id="v330.8.6"><span class="H559 s">He said</span><span class="H1121 s"> furthermore unto me, Son</span><span class="H120 s"> of man</span><span class="H7200 s">, seest</span><span class="H6213 s"> thou what they do</span><span class="H1419 s">? <i>even</i> the great</span><span class="H8441 s"> abominations</span><span class="H1004 s"> that the house</span><span class="H3478 s"> of Israel</span><span class="H6213 s"> committeth</span><span class="H7368 s"> here, that I should go far off</span><span class="H4720 s"> from my sanctuary</span><span class="H7725 s">? but turn</span><span class="H7200 s"> thee yet again, <i>and</i> thou shalt see</span><span class="H1419 s"> greater</span><span class="H8441 s"> abominations</span>.</div> 
<div id="v330.8.7"><span class="H935 s">And he brought</span><span class="H6607 s"> me to the door</span><span class="H2691 s"> of the court</span><span class="H7200 s">; and when I looked</span><span class="H259 s">, behold a</span><span class="H2356 s"> hole</span><span class="H7023 s"> in the wall</span>.</div> 
<div id="v330.8.8"><span class="H559 s">Then said</span><span class="H1121 s"> he unto me, Son</span><span class="H120 s"> of man</span><span class="H2864 s">, dig</span><span class="H7023 s"> now in the wall</span><span class="H2864 s">: and when I had digged</span><span class="H7023 s"> in the wall</span><span class="H259 s">, behold a</span><span class="H6607 s"> door</span>.</div> 
<div id="v330.8.9"><span class="H559 s">And he said</span><span class="H935 s"> unto me, Go in</span><span class="H7200 s">, and behold</span><span class="H7451 s"> the wicked</span><span class="H8441 s"> abominations</span><span class="H6213 s"> that they do</span> here.</div> 
<div id="v330.8.10"><span class="H935 s">So I went in</span><span class="H7200 s"> and saw</span><span class="H8403 s">; and behold every form</span><span class="H7431 s"> of creeping things</span><span class="H8263 s">, and abominable</span><span class="H929 s"> beasts</span><span class="H1544 s">, and all the idols</span><span class="H1004 s"> of the house</span><span class="H3478 s"> of Israel</span><span class="H2707 s">, pourtrayed</span><span class="H7023 s"> upon the wall</span><span class="H5439 s"> round about</span>.</div> 
<div id="v330.8.11"><span class="H5975 s">And there stood</span><span class="H6440 s"> before</span><span class="H7657 s"> them seventy</span><span class="H376 s"> men</span><span class="H2205 s"> of the ancients</span><span class="H1004 s"> of the house</span><span class="H3478 s"> of Israel</span><span class="H8432 s">, and in the midst</span><span class="H5975 s"> of them stood</span><span class="H2970 s"> Jaazaniah</span><span class="H1121 s"> the son</span><span class="H8227 s"> of Shaphan</span><span class="H376 s">, with every man</span><span class="H4730 s"> his censer</span><span class="H3027 s"> in his hand</span><span class="H6282 s">; and a thick</span><span class="H6051 s"> cloud</span><span class="H7004 s"> of incense</span><span class="H5927 s"> went up</span>.</div> 
<div id="v330.8.12"><span class="H559 s">Then said</span><span class="H1121 s"> he unto me, Son</span><span class="H120 s"> of man</span><span class="H7200 s">, hast thou seen</span><span class="H2205 s"> what the ancients</span><span class="H1004 s"> of the house</span><span class="H3478 s"> of Israel</span><span class="H6213 s"> do</span><span class="H2822 s"> in the dark</span><span class="H376 s">, every man</span><span class="H2315 s"> in the chambers</span><span class="H4906 s"> of his imagery</span><span class="H559 s">? for they say</span><span class="H3068 s">, The LORD</span><span class="H7200 s"> seeth</span><span class="H3068 s"> us not; the LORD</span><span class="H5800 s"> hath forsaken</span><span class="H776 s"> the earth</span>.</div> 
<div id="v330.8.13"><span class="H559 s">He said</span><span class="H7725 s"> also unto me, Turn</span><span class="H7200 s"> thee yet again, <i>and</i> thou shalt see</span><span class="H1419 s"> greater</span><span class="H8441 s"> abominations</span><span class="H6213 s"> that they do</span>.</div> 
<div id="v330.8.14"><span class="H935 s">Then he brought</span><span class="H6607 s"> me to the door</span><span class="H8179 s"> of the gate</span><span class="H3068 s"> of the LORD'S</span><span class="H1004 s"> house</span><span class="H6828 s"> which <i>was</i> toward the north</span><span class="H3427 s">; and, behold, there sat</span><span class="H802 s"> women</span><span class="H1058 s"> weeping</span><span class="H8542 s"> for Tammuz</span>.</div> 
<div id="v330.8.15"><span class="H559 s">Then said</span><span class="H7200 s"> he unto me, Hast thou seen</span><span class="H1121 s"> <i>this</i>, O son</span><span class="H120 s"> of man</span><span class="H7725 s">? turn</span><span class="H7200 s"> thee yet again, <i>and</i> thou shalt see</span><span class="H1419 s"> greater</span><span class="H8441 s"> abominations</span> than these.</div> 
<div id="v330.8.16"><span class="H935 s">And he brought</span><span class="H6442 s"> me into the inner</span><span class="H2691 s"> court</span><span class="H3068 s"> of the LORD'S</span><span class="H1004 s"> house</span><span class="H6607 s">, and, behold, at the door</span><span class="H1964 s"> of the temple</span><span class="H3068 s"> of the LORD</span><span class="H197 s">, between the porch</span><span class="H4196 s"> and the altar</span><span class="H2568 s">, <i>were</i> about five</span><span class="H6242 s"> and twenty</span><span class="H376 s"> men</span><span class="H268 s">, with their backs</span><span class="H1964 s"> toward the temple</span><span class="H3068 s"> of the LORD</span><span class="H6440 s">, and their faces</span><span class="H6924 s"> toward the east</span><span class="H7812 s">; and they worshipped</span><span class="H8121 s"> the sun</span><span class="H6924 s"> toward the east</span>.</div> 
<div id="v330.8.17"><span class="H559 s">Then he said</span><span class="H7200 s"> unto me, Hast thou seen</span><span class="H1121 s"> <i>this</i>, O son</span><span class="H120 s"> of man</span><span class="H7043 s">? Is it a light thing</span><span class="H1004 s"> to the house</span><span class="H3063 s"> of Judah</span><span class="H6213 s"> that they commit</span><span class="H8441 s"> the abominations</span><span class="H6213 s"> which they commit</span><span class="H4390 s"> here? for they have filled</span><span class="H776 s"> the land</span><span class="H2555 s"> with violence</span><span class="H7725 s">, and have returned</span><span class="H3707 s"> to provoke me to anger</span><span class="H7971 s">: and, lo, they put</span><span class="H2156 s"> the branch</span><span class="H639 s"> to their nose</span>. <span class="notes">Notes by the 1611 King James Bible Translators: (Is it…: or, Is there any thing lighter than to commit)</span></div> 
<div id="v330.8.18"><span class="H6213 s">Therefore will I also deal</span><span class="H2534 s"> in fury</span><span class="H5869 s">: mine eye</span><span class="H2347 s"> shall not spare</span><span class="H2550 s">, neither will I have pity</span><span class="H7121 s">: and though they cry</span><span class="H241 s"> in mine ears</span><span class="H1419 s"> with a loud</span><span class="H6963 s"> voice</span><span class="H8085 s">, <i>yet</i> will I not hear</span> them.</div></div>

<div id="adding_titles_RL_save_changes">Save Changes</div><script src="../../dependencies/offline_dependency_2017-11-16_jquery-3.2.1.min.js" type="text/javascript"></script><script type="text/javascript" src="_TheLordTitlesAndRL.js"></script></body></html> 
